// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: common/common_v3.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Modulation int32

const (
	// LoRa
	Modulation_LORA Modulation = 0
	// FSK
	Modulation_FSK Modulation = 1
	// LR-FHSS
	Modulation_LR_FHSS Modulation = 2
)

// Enum value maps for Modulation.
var (
	Modulation_name = map[int32]string{
		0: "LORA",
		1: "FSK",
		2: "LR_FHSS",
	}
	Modulation_value = map[string]int32{
		"LORA":    0,
		"FSK":     1,
		"LR_FHSS": 2,
	}
)

func (x Modulation) Enum() *Modulation {
	p := new(Modulation)
	*p = x
	return p
}

func (x Modulation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Modulation) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_v3_proto_enumTypes[0].Descriptor()
}

func (Modulation) Type() protoreflect.EnumType {
	return &file_common_common_v3_proto_enumTypes[0]
}

func (x Modulation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Modulation.Descriptor instead.
func (Modulation) EnumDescriptor() ([]byte, []int) {
	return file_common_common_v3_proto_rawDescGZIP(), []int{0}
}

type Region int32

const (
	// EU868
	Region_EU868 Region = 0
	// US915
	Region_US915 Region = 2
	// CN779
	Region_CN779 Region = 3
	// EU433
	Region_EU433 Region = 4
	// AU915
	Region_AU915 Region = 5
	// CN470
	Region_CN470 Region = 6
	// AS923
	Region_AS923 Region = 7
	// AS923 with -1.80 MHz frequency offset
	Region_AS923_2 Region = 12
	// AS923 with -6.60 MHz frequency offset
	Region_AS923_3 Region = 13
	// AS923 with -5.90 MHz frequency offset
	Region_AS923_4 Region = 14
	// KR920
	Region_KR920 Region = 8
	// IN865
	Region_IN865 Region = 9
	// RU864
	Region_RU864 Region = 10
	// ISM2400 (LoRaWAN 2.4 GHz)
	Region_ISM2400 Region = 11
)

// Enum value maps for Region.
var (
	Region_name = map[int32]string{
		0:  "EU868",
		2:  "US915",
		3:  "CN779",
		4:  "EU433",
		5:  "AU915",
		6:  "CN470",
		7:  "AS923",
		12: "AS923_2",
		13: "AS923_3",
		14: "AS923_4",
		8:  "KR920",
		9:  "IN865",
		10: "RU864",
		11: "ISM2400",
	}
	Region_value = map[string]int32{
		"EU868":   0,
		"US915":   2,
		"CN779":   3,
		"EU433":   4,
		"AU915":   5,
		"CN470":   6,
		"AS923":   7,
		"AS923_2": 12,
		"AS923_3": 13,
		"AS923_4": 14,
		"KR920":   8,
		"IN865":   9,
		"RU864":   10,
		"ISM2400": 11,
	}
)

func (x Region) Enum() *Region {
	p := new(Region)
	*p = x
	return p
}

func (x Region) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Region) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_v3_proto_enumTypes[1].Descriptor()
}

func (Region) Type() protoreflect.EnumType {
	return &file_common_common_v3_proto_enumTypes[1]
}

func (x Region) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Region.Descriptor instead.
func (Region) EnumDescriptor() ([]byte, []int) {
	return file_common_common_v3_proto_rawDescGZIP(), []int{1}
}

type MType int32

const (
	// JoinRequest.
	MType_JoinRequest MType = 0
	// JoinAccept.
	MType_JoinAccept MType = 1
	// UnconfirmedDataUp.
	MType_UnconfirmedDataUp MType = 2
	// UnconfirmedDataDown.
	MType_UnconfirmedDataDown MType = 3
	// ConfirmedDataUp.
	MType_ConfirmedDataUp MType = 4
	// ConfirmedDataDown.
	MType_ConfirmedDataDown MType = 5
	// RejoinRequest.
	MType_RejoinRequest MType = 6
	// Proprietary.
	MType_Proprietary MType = 7
)

// Enum value maps for MType.
var (
	MType_name = map[int32]string{
		0: "JoinRequest",
		1: "JoinAccept",
		2: "UnconfirmedDataUp",
		3: "UnconfirmedDataDown",
		4: "ConfirmedDataUp",
		5: "ConfirmedDataDown",
		6: "RejoinRequest",
		7: "Proprietary",
	}
	MType_value = map[string]int32{
		"JoinRequest":         0,
		"JoinAccept":          1,
		"UnconfirmedDataUp":   2,
		"UnconfirmedDataDown": 3,
		"ConfirmedDataUp":     4,
		"ConfirmedDataDown":   5,
		"RejoinRequest":       6,
		"Proprietary":         7,
	}
)

func (x MType) Enum() *MType {
	p := new(MType)
	*p = x
	return p
}

func (x MType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_v3_proto_enumTypes[2].Descriptor()
}

func (MType) Type() protoreflect.EnumType {
	return &file_common_common_v3_proto_enumTypes[2]
}

func (x MType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MType.Descriptor instead.
func (MType) EnumDescriptor() ([]byte, []int) {
	return file_common_common_v3_proto_rawDescGZIP(), []int{2}
}

type LocationSource int32

const (
	// Unknown.
	LocationSource_UNKNOWN LocationSource = 0
	// GPS.
	LocationSource_GPS LocationSource = 1
	// Manually configured.
	LocationSource_CONFIG LocationSource = 2
	// Geo resolver (TDOA).
	LocationSource_GEO_RESOLVER_TDOA LocationSource = 3
	// Geo resolver (RSSI).
	LocationSource_GEO_RESOLVER_RSSI LocationSource = 4
	// Geo resolver (GNSS).
	LocationSource_GEO_RESOLVER_GNSS LocationSource = 5
	// Geo resolver (WIFI).
	LocationSource_GEO_RESOLVER_WIFI LocationSource = 6
)

// Enum value maps for LocationSource.
var (
	LocationSource_name = map[int32]string{
		0: "UNKNOWN",
		1: "GPS",
		2: "CONFIG",
		3: "GEO_RESOLVER_TDOA",
		4: "GEO_RESOLVER_RSSI",
		5: "GEO_RESOLVER_GNSS",
		6: "GEO_RESOLVER_WIFI",
	}
	LocationSource_value = map[string]int32{
		"UNKNOWN":           0,
		"GPS":               1,
		"CONFIG":            2,
		"GEO_RESOLVER_TDOA": 3,
		"GEO_RESOLVER_RSSI": 4,
		"GEO_RESOLVER_GNSS": 5,
		"GEO_RESOLVER_WIFI": 6,
	}
)

func (x LocationSource) Enum() *LocationSource {
	p := new(LocationSource)
	*p = x
	return p
}

func (x LocationSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationSource) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_v3_proto_enumTypes[3].Descriptor()
}

func (LocationSource) Type() protoreflect.EnumType {
	return &file_common_common_v3_proto_enumTypes[3]
}

func (x LocationSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationSource.Descriptor instead.
func (LocationSource) EnumDescriptor() ([]byte, []int) {
	return file_common_common_v3_proto_rawDescGZIP(), []int{3}
}

type KeyEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// KEK label.
	KekLabel string `protobuf:"bytes,1,opt,name=kek_label,json=kekLabel,proto3" json:"kek_label,omitempty"`
	// AES key (when the kek_label is set, this key is encrypted using a key
	// known to the join-server and application-server.
	// For more information please refer to the LoRaWAN Backend Interface
	// 'Key Transport Security' section.
	AesKey        []byte `protobuf:"bytes,2,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEnvelope) Reset() {
	*x = KeyEnvelope{}
	mi := &file_common_common_v3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEnvelope) ProtoMessage() {}

func (x *KeyEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_v3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEnvelope.ProtoReflect.Descriptor instead.
func (*KeyEnvelope) Descriptor() ([]byte, []int) {
	return file_common_common_v3_proto_rawDescGZIP(), []int{0}
}

func (x *KeyEnvelope) GetKekLabel() string {
	if x != nil {
		return x.KekLabel
	}
	return ""
}

func (x *KeyEnvelope) GetAesKey() []byte {
	if x != nil {
		return x.AesKey
	}
	return nil
}

type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Latitude.
	Latitude float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// Longitude.
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// Altitude.
	Altitude float64 `protobuf:"fixed64,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	// Location source.
	Source LocationSource `protobuf:"varint,4,opt,name=source,proto3,enum=common_v3.LocationSource" json:"source,omitempty"`
	// Accuracy (in meters).
	Accuracy      uint32 `protobuf:"varint,5,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_common_common_v3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_v3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_common_common_v3_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *Location) GetSource() LocationSource {
	if x != nil {
		return x.Source
	}
	return LocationSource_UNKNOWN
}

func (x *Location) GetAccuracy() uint32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

var File_common_common_v3_proto protoreflect.FileDescriptor

const file_common_common_v3_proto_rawDesc = "" +
	"\n" +
	"\x16common/common_v3.proto\x12\tcommon_v3\"C\n" +
	"\vKeyEnvelope\x12\x1b\n" +
	"\tkek_label\x18\x01 \x01(\tR\bkekLabel\x12\x17\n" +
	"\aaes_key\x18\x02 \x01(\fR\x06aesKey\"\xaf\x01\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\baltitude\x18\x03 \x01(\x01R\baltitude\x121\n" +
	"\x06source\x18\x04 \x01(\x0e2\x19.common_v3.LocationSourceR\x06source\x12\x1a\n" +
	"\baccuracy\x18\x05 \x01(\rR\baccuracy*,\n" +
	"\n" +
	"Modulation\x12\b\n" +
	"\x04LORA\x10\x00\x12\a\n" +
	"\x03FSK\x10\x01\x12\v\n" +
	"\aLR_FHSS\x10\x02*\xaa\x01\n" +
	"\x06Region\x12\t\n" +
	"\x05EU868\x10\x00\x12\t\n" +
	"\x05US915\x10\x02\x12\t\n" +
	"\x05CN779\x10\x03\x12\t\n" +
	"\x05EU433\x10\x04\x12\t\n" +
	"\x05AU915\x10\x05\x12\t\n" +
	"\x05CN470\x10\x06\x12\t\n" +
	"\x05AS923\x10\a\x12\v\n" +
	"\aAS923_2\x10\f\x12\v\n" +
	"\aAS923_3\x10\r\x12\v\n" +
	"\aAS923_4\x10\x0e\x12\t\n" +
	"\x05KR920\x10\b\x12\t\n" +
	"\x05IN865\x10\t\x12\t\n" +
	"\x05RU864\x10\n" +
	"\x12\v\n" +
	"\aISM2400\x10\v*\xa8\x01\n" +
	"\x05MType\x12\x0f\n" +
	"\vJoinRequest\x10\x00\x12\x0e\n" +
	"\n" +
	"JoinAccept\x10\x01\x12\x15\n" +
	"\x11UnconfirmedDataUp\x10\x02\x12\x17\n" +
	"\x13UnconfirmedDataDown\x10\x03\x12\x13\n" +
	"\x0fConfirmedDataUp\x10\x04\x12\x15\n" +
	"\x11ConfirmedDataDown\x10\x05\x12\x11\n" +
	"\rRejoinRequest\x10\x06\x12\x0f\n" +
	"\vProprietary\x10\a*\x8e\x01\n" +
	"\x0eLocationSource\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03GPS\x10\x01\x12\n" +
	"\n" +
	"\x06CONFIG\x10\x02\x12\x15\n" +
	"\x11GEO_RESOLVER_TDOA\x10\x03\x12\x15\n" +
	"\x11GEO_RESOLVER_RSSI\x10\x04\x12\x15\n" +
	"\x11GEO_RESOLVER_GNSS\x10\x05\x12\x15\n" +
	"\x11GEO_RESOLVER_WIFI\x10\x06B_\n" +
	"\x1bio.chirpstack.api_v3.commonB\vCommonProtoP\x01Z1github.com/IoTOpen/chirpstack-v3-api/go/v3/commonb\x06proto3"

var (
	file_common_common_v3_proto_rawDescOnce sync.Once
	file_common_common_v3_proto_rawDescData []byte
)

func file_common_common_v3_proto_rawDescGZIP() []byte {
	file_common_common_v3_proto_rawDescOnce.Do(func() {
		file_common_common_v3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_common_v3_proto_rawDesc), len(file_common_common_v3_proto_rawDesc)))
	})
	return file_common_common_v3_proto_rawDescData
}

var file_common_common_v3_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_common_common_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_common_v3_proto_goTypes = []any{
	(Modulation)(0),     // 0: common_v3.Modulation
	(Region)(0),         // 1: common_v3.Region
	(MType)(0),          // 2: common_v3.MType
	(LocationSource)(0), // 3: common_v3.LocationSource
	(*KeyEnvelope)(nil), // 4: common_v3.KeyEnvelope
	(*Location)(nil),    // 5: common_v3.Location
}
var file_common_common_v3_proto_depIdxs = []int32{
	3, // 0: common_v3.Location.source:type_name -> common_v3.LocationSource
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_common_v3_proto_init() }
func file_common_common_v3_proto_init() {
	if File_common_common_v3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_common_v3_proto_rawDesc), len(file_common_common_v3_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_v3_proto_goTypes,
		DependencyIndexes: file_common_common_v3_proto_depIdxs,
		EnumInfos:         file_common_common_v3_proto_enumTypes,
		MessageInfos:      file_common_common_v3_proto_msgTypes,
	}.Build()
	File_common_common_v3_proto = out.File
	file_common_common_v3_proto_goTypes = nil
	file_common_common_v3_proto_depIdxs = nil
}
