// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: as/integration/integration_v3.proto

package integration

import (
	common "github.com/brocaar/chirpstack-api/go/v3/common"
	gw "github.com/brocaar/chirpstack-api/go/v3/gw"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorType int32

const (
	// Unknown type.
	ErrorType_UNKNOWN ErrorType = 0
	// Error related to the downlink payload size.
	// Usually seen when the payload exceeded the maximum allowed payload size.
	ErrorType_DOWNLINK_PAYLOAD_SIZE ErrorType = 1
	// Error related to the downlink frame-counter.
	// Usually seen when the frame-counter has already been used.
	ErrorType_DOWNLINK_FCNT ErrorType = 2
	// Uplink codec error.
	ErrorType_UPLINK_CODEC ErrorType = 3
	// Downlink codec error.
	ErrorType_DOWNLINK_CODEC ErrorType = 4
	// OTAA error.
	ErrorType_OTAA ErrorType = 5
	// Uplink frame-counter was reset.
	ErrorType_UPLINK_FCNT_RESET ErrorType = 6
	// Uplink MIC error.
	ErrorType_UPLINK_MIC ErrorType = 7
	// Uplink frame-counter retransmission.
	ErrorType_UPLINK_FCNT_RETRANSMISSION ErrorType = 8
	// Downlink gateway error.
	ErrorType_DOWNLINK_GATEWAY ErrorType = 9
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "UNKNOWN",
		1: "DOWNLINK_PAYLOAD_SIZE",
		2: "DOWNLINK_FCNT",
		3: "UPLINK_CODEC",
		4: "DOWNLINK_CODEC",
		5: "OTAA",
		6: "UPLINK_FCNT_RESET",
		7: "UPLINK_MIC",
		8: "UPLINK_FCNT_RETRANSMISSION",
		9: "DOWNLINK_GATEWAY",
	}
	ErrorType_value = map[string]int32{
		"UNKNOWN":                    0,
		"DOWNLINK_PAYLOAD_SIZE":      1,
		"DOWNLINK_FCNT":              2,
		"UPLINK_CODEC":               3,
		"DOWNLINK_CODEC":             4,
		"OTAA":                       5,
		"UPLINK_FCNT_RESET":          6,
		"UPLINK_MIC":                 7,
		"UPLINK_FCNT_RETRANSMISSION": 8,
		"DOWNLINK_GATEWAY":           9,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_as_integration_integration_v3_proto_enumTypes[0].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_as_integration_integration_v3_proto_enumTypes[0]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_as_integration_integration_v3_proto_rawDescGZIP(), []int{0}
}

// UplinkEvent is the message sent when an uplink payload has been received.
type UplinkEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Receiving gateway RX info.
	RxInfo []*gw.UplinkRXInfo `protobuf:"bytes,5,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	// TX info.
	TxInfo *gw.UplinkTXInfo `protobuf:"bytes,6,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// Device has ADR bit set.
	Adr bool `protobuf:"varint,7,opt,name=adr,proto3" json:"adr,omitempty"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,8,opt,name=dr,proto3" json:"dr,omitempty"`
	// Frame counter.
	FCnt uint32 `protobuf:"varint,9,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// Frame port.
	FPort uint32 `protobuf:"varint,10,opt,name=f_port,json=fPort,proto3" json:"f_port,omitempty"`
	// FRMPayload data.
	Data []byte `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`
	// JSON string containing the decoded object.
	// Note that this is only set when a codec is configured in the Device Profile.
	ObjectJson string `protobuf:"bytes,12,opt,name=object_json,json=objectJSON,proto3" json:"object_json,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Uplink was of type confirmed.
	ConfirmedUplink bool `protobuf:"varint,14,opt,name=confirmed_uplink,json=confirmedUplink,proto3" json:"confirmed_uplink,omitempty"`
	// Device address.
	DevAddr []byte `protobuf:"bytes,15,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	// Published at timestamp.
	PublishedAt *timestamp.Timestamp `protobuf:"bytes,16,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// Device Profile UUID as string
	DeviceProfileId string `protobuf:"bytes,17,opt,name=device_profile_id,json=deviceProfileID,proto3" json:"device_profile_id,omitempty"`
	// Device Profile name
	DeviceProfileName string `protobuf:"bytes,18,opt,name=device_profile_name,json=deviceProfileName,proto3" json:"device_profile_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UplinkEvent) Reset() {
	*x = UplinkEvent{}
	mi := &file_as_integration_integration_v3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UplinkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UplinkEvent) ProtoMessage() {}

func (x *UplinkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_as_integration_integration_v3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UplinkEvent.ProtoReflect.Descriptor instead.
func (*UplinkEvent) Descriptor() ([]byte, []int) {
	return file_as_integration_integration_v3_proto_rawDescGZIP(), []int{0}
}

func (x *UplinkEvent) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *UplinkEvent) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *UplinkEvent) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *UplinkEvent) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *UplinkEvent) GetRxInfo() []*gw.UplinkRXInfo {
	if x != nil {
		return x.RxInfo
	}
	return nil
}

func (x *UplinkEvent) GetTxInfo() *gw.UplinkTXInfo {
	if x != nil {
		return x.TxInfo
	}
	return nil
}

func (x *UplinkEvent) GetAdr() bool {
	if x != nil {
		return x.Adr
	}
	return false
}

func (x *UplinkEvent) GetDr() uint32 {
	if x != nil {
		return x.Dr
	}
	return 0
}

func (x *UplinkEvent) GetFCnt() uint32 {
	if x != nil {
		return x.FCnt
	}
	return 0
}

func (x *UplinkEvent) GetFPort() uint32 {
	if x != nil {
		return x.FPort
	}
	return 0
}

func (x *UplinkEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UplinkEvent) GetObjectJson() string {
	if x != nil {
		return x.ObjectJson
	}
	return ""
}

func (x *UplinkEvent) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UplinkEvent) GetConfirmedUplink() bool {
	if x != nil {
		return x.ConfirmedUplink
	}
	return false
}

func (x *UplinkEvent) GetDevAddr() []byte {
	if x != nil {
		return x.DevAddr
	}
	return nil
}

func (x *UplinkEvent) GetPublishedAt() *timestamp.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *UplinkEvent) GetDeviceProfileId() string {
	if x != nil {
		return x.DeviceProfileId
	}
	return ""
}

func (x *UplinkEvent) GetDeviceProfileName() string {
	if x != nil {
		return x.DeviceProfileName
	}
	return ""
}

// JoinEvent is the message sent when a device joined the network.
// Note that this is only sent after the first received uplink after the
// device (re)activation.
type JoinEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Device address.
	DevAddr []byte `protobuf:"bytes,5,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	// Receiving gateway RX info.
	RxInfo []*gw.UplinkRXInfo `protobuf:"bytes,6,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	// TX info.
	TxInfo *gw.UplinkTXInfo `protobuf:"bytes,7,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,8,opt,name=dr,proto3" json:"dr,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Published at timestamp.
	PublishedAt   *timestamp.Timestamp `protobuf:"bytes,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinEvent) Reset() {
	*x = JoinEvent{}
	mi := &file_as_integration_integration_v3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinEvent) ProtoMessage() {}

func (x *JoinEvent) ProtoReflect() protoreflect.Message {
	mi := &file_as_integration_integration_v3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinEvent.ProtoReflect.Descriptor instead.
func (*JoinEvent) Descriptor() ([]byte, []int) {
	return file_as_integration_integration_v3_proto_rawDescGZIP(), []int{1}
}

func (x *JoinEvent) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *JoinEvent) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *JoinEvent) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *JoinEvent) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *JoinEvent) GetDevAddr() []byte {
	if x != nil {
		return x.DevAddr
	}
	return nil
}

func (x *JoinEvent) GetRxInfo() []*gw.UplinkRXInfo {
	if x != nil {
		return x.RxInfo
	}
	return nil
}

func (x *JoinEvent) GetTxInfo() *gw.UplinkTXInfo {
	if x != nil {
		return x.TxInfo
	}
	return nil
}

func (x *JoinEvent) GetDr() uint32 {
	if x != nil {
		return x.Dr
	}
	return 0
}

func (x *JoinEvent) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *JoinEvent) GetPublishedAt() *timestamp.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

// AckEvent is the message sent when a confirmation on a confirmed downlink
// has been received -or- when the downlink timed out.
type AckEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Frame was acknowledged.
	Acknowledged bool `protobuf:"varint,5,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// Downlink frame counter to which the acknowledgement relates.
	FCnt uint32 `protobuf:"varint,6,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Published at timestamp.
	PublishedAt   *timestamp.Timestamp `protobuf:"bytes,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckEvent) Reset() {
	*x = AckEvent{}
	mi := &file_as_integration_integration_v3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckEvent) ProtoMessage() {}

func (x *AckEvent) ProtoReflect() protoreflect.Message {
	mi := &file_as_integration_integration_v3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckEvent.ProtoReflect.Descriptor instead.
func (*AckEvent) Descriptor() ([]byte, []int) {
	return file_as_integration_integration_v3_proto_rawDescGZIP(), []int{2}
}

func (x *AckEvent) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *AckEvent) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *AckEvent) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *AckEvent) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *AckEvent) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *AckEvent) GetFCnt() uint32 {
	if x != nil {
		return x.FCnt
	}
	return 0
}

func (x *AckEvent) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AckEvent) GetPublishedAt() *timestamp.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

// TxAckEvent is the message sent when a downlink was acknowledged by the gateway
// for transmission. As a downlink can be scheduled in the future, this event
// does not confirm that the message has already been transmitted.
type TxAckEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Downlink frame-counter.
	FCnt uint32 `protobuf:"varint,5,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,7,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// TX info.
	TxInfo *gw.DownlinkTXInfo `protobuf:"bytes,8,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// Published at timestamp.
	PublishedAt   *timestamp.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxAckEvent) Reset() {
	*x = TxAckEvent{}
	mi := &file_as_integration_integration_v3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxAckEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxAckEvent) ProtoMessage() {}

func (x *TxAckEvent) ProtoReflect() protoreflect.Message {
	mi := &file_as_integration_integration_v3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxAckEvent.ProtoReflect.Descriptor instead.
func (*TxAckEvent) Descriptor() ([]byte, []int) {
	return file_as_integration_integration_v3_proto_rawDescGZIP(), []int{3}
}

func (x *TxAckEvent) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *TxAckEvent) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *TxAckEvent) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *TxAckEvent) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *TxAckEvent) GetFCnt() uint32 {
	if x != nil {
		return x.FCnt
	}
	return 0
}

func (x *TxAckEvent) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TxAckEvent) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *TxAckEvent) GetTxInfo() *gw.DownlinkTXInfo {
	if x != nil {
		return x.TxInfo
	}
	return nil
}

func (x *TxAckEvent) GetPublishedAt() *timestamp.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

// ErrorEvent is the message sent when an error occurred.
type ErrorEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Error type.
	Type ErrorType `protobuf:"varint,5,opt,name=type,proto3,enum=integration_v3.ErrorType" json:"type,omitempty"`
	// Error message.
	Error string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	// Downlink frame-counter (in case the downlink is related to a scheduled downlink).
	FCnt uint32 `protobuf:"varint,7,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Published at timestamp.
	PublishedAt   *timestamp.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_as_integration_integration_v3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_as_integration_integration_v3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_as_integration_integration_v3_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorEvent) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *ErrorEvent) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *ErrorEvent) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *ErrorEvent) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *ErrorEvent) GetType() ErrorType {
	if x != nil {
		return x.Type
	}
	return ErrorType_UNKNOWN
}

func (x *ErrorEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ErrorEvent) GetFCnt() uint32 {
	if x != nil {
		return x.FCnt
	}
	return 0
}

func (x *ErrorEvent) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ErrorEvent) GetPublishedAt() *timestamp.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

// StatusEvent is the message sent when a device-status mac-command was sent
// by the device.
type StatusEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// The demodulation signal-to-noise ratio in dB for the last successfully
	// received device-status request by the Network Server.
	Margin int32 `protobuf:"varint,5,opt,name=margin,proto3" json:"margin,omitempty"`
	// Device is connected to an external power source.
	ExternalPowerSource bool `protobuf:"varint,6,opt,name=external_power_source,json=externalPowerSource,proto3" json:"external_power_source,omitempty"`
	// Battery level is not available.
	BatteryLevelUnavailable bool `protobuf:"varint,7,opt,name=battery_level_unavailable,json=batteryLevelUnavailable,proto3" json:"battery_level_unavailable,omitempty"`
	// Battery level.
	BatteryLevel float32 `protobuf:"fixed32,8,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Published at timestamp.
	PublishedAt   *timestamp.Timestamp `protobuf:"bytes,10,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_as_integration_integration_v3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_as_integration_integration_v3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_as_integration_integration_v3_proto_rawDescGZIP(), []int{5}
}

func (x *StatusEvent) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *StatusEvent) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *StatusEvent) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *StatusEvent) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *StatusEvent) GetMargin() int32 {
	if x != nil {
		return x.Margin
	}
	return 0
}

func (x *StatusEvent) GetExternalPowerSource() bool {
	if x != nil {
		return x.ExternalPowerSource
	}
	return false
}

func (x *StatusEvent) GetBatteryLevelUnavailable() bool {
	if x != nil {
		return x.BatteryLevelUnavailable
	}
	return false
}

func (x *StatusEvent) GetBatteryLevel() float32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *StatusEvent) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *StatusEvent) GetPublishedAt() *timestamp.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

// LocationEvent is the message sent when a geolocation resolve was returned.
type LocationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Location.
	Location *common.Location `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Uplink IDs used for geolocation.
	// This is set in case the geolocation is based on the uplink meta-data.
	UplinkIds [][]byte `protobuf:"bytes,7,rep,name=uplink_ids,json=uplinkIDs,proto3" json:"uplink_ids,omitempty"`
	// Frame counter (in case the geolocation is based on the payload).
	// This is set in case the geolocation is based on the uplink payload content.
	FCnt uint32 `protobuf:"varint,8,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// Published at timestamp.
	PublishedAt   *timestamp.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationEvent) Reset() {
	*x = LocationEvent{}
	mi := &file_as_integration_integration_v3_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationEvent) ProtoMessage() {}

func (x *LocationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_as_integration_integration_v3_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationEvent.ProtoReflect.Descriptor instead.
func (*LocationEvent) Descriptor() ([]byte, []int) {
	return file_as_integration_integration_v3_proto_rawDescGZIP(), []int{6}
}

func (x *LocationEvent) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *LocationEvent) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *LocationEvent) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *LocationEvent) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *LocationEvent) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *LocationEvent) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *LocationEvent) GetUplinkIds() [][]byte {
	if x != nil {
		return x.UplinkIds
	}
	return nil
}

func (x *LocationEvent) GetFCnt() uint32 {
	if x != nil {
		return x.FCnt
	}
	return 0
}

func (x *LocationEvent) GetPublishedAt() *timestamp.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

// IntegrationEvent is the message that can be sent by an integration.
// It allows for sending events which are provided by an external integration
// which are "not native" to ChirpStack.
type IntegrationEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID.
	ApplicationId uint64 `protobuf:"varint,1,opt,name=application_id,json=applicationID,proto3" json:"application_id,omitempty"`
	// Application name.
	ApplicationName string `protobuf:"bytes,2,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	// Device name.
	DeviceName string `protobuf:"bytes,3,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	// Device EUI.
	DevEui []byte `protobuf:"bytes,4,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// User-defined device tags.
	Tags map[string]string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Integration name.
	IntegrationName string `protobuf:"bytes,6,opt,name=integration_name,json=integrationName,proto3" json:"integration_name,omitempty"`
	// Event type.
	EventType string `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// JSON string containing the event object.
	ObjectJson string `protobuf:"bytes,8,opt,name=object_json,json=objectJSON,proto3" json:"object_json,omitempty"`
	// Published at timestamp.
	PublishedAt   *timestamp.Timestamp `protobuf:"bytes,9,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationEvent) Reset() {
	*x = IntegrationEvent{}
	mi := &file_as_integration_integration_v3_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationEvent) ProtoMessage() {}

func (x *IntegrationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_as_integration_integration_v3_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationEvent.ProtoReflect.Descriptor instead.
func (*IntegrationEvent) Descriptor() ([]byte, []int) {
	return file_as_integration_integration_v3_proto_rawDescGZIP(), []int{7}
}

func (x *IntegrationEvent) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *IntegrationEvent) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *IntegrationEvent) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *IntegrationEvent) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *IntegrationEvent) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *IntegrationEvent) GetIntegrationName() string {
	if x != nil {
		return x.IntegrationName
	}
	return ""
}

func (x *IntegrationEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *IntegrationEvent) GetObjectJson() string {
	if x != nil {
		return x.ObjectJson
	}
	return ""
}

func (x *IntegrationEvent) GetPublishedAt() *timestamp.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

var File_as_integration_integration_v3_proto protoreflect.FileDescriptor

const file_as_integration_integration_v3_proto_rawDesc = "" +
	"\n" +
	"#as/integration/integration_v3.proto\x12\x0eintegration_v3\x1a\x16common/common_v3.proto\x1a\x0egw/gw_v3.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x05\n" +
	"\vUplinkEvent\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x04R\rapplicationID\x12)\n" +
	"\x10application_name\x18\x02 \x01(\tR\x0fapplicationName\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x17\n" +
	"\adev_eui\x18\x04 \x01(\fR\x06devEUI\x12,\n" +
	"\arx_info\x18\x05 \x03(\v2\x13.gw_v3.UplinkRXInfoR\x06rxInfo\x12,\n" +
	"\atx_info\x18\x06 \x01(\v2\x13.gw_v3.UplinkTXInfoR\x06txInfo\x12\x10\n" +
	"\x03adr\x18\a \x01(\bR\x03adr\x12\x0e\n" +
	"\x02dr\x18\b \x01(\rR\x02dr\x12\x13\n" +
	"\x05f_cnt\x18\t \x01(\rR\x04fCnt\x12\x15\n" +
	"\x06f_port\x18\n" +
	" \x01(\rR\x05fPort\x12\x12\n" +
	"\x04data\x18\v \x01(\fR\x04data\x12\x1f\n" +
	"\vobject_json\x18\f \x01(\tR\n" +
	"objectJSON\x129\n" +
	"\x04tags\x18\r \x03(\v2%.integration_v3.UplinkEvent.TagsEntryR\x04tags\x12)\n" +
	"\x10confirmed_uplink\x18\x0e \x01(\bR\x0fconfirmedUplink\x12\x19\n" +
	"\bdev_addr\x18\x0f \x01(\fR\adevAddr\x12=\n" +
	"\fpublished_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12*\n" +
	"\x11device_profile_id\x18\x11 \x01(\tR\x0fdeviceProfileID\x12.\n" +
	"\x13device_profile_name\x18\x12 \x01(\tR\x11deviceProfileName\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x03\n" +
	"\tJoinEvent\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x04R\rapplicationID\x12)\n" +
	"\x10application_name\x18\x02 \x01(\tR\x0fapplicationName\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x17\n" +
	"\adev_eui\x18\x04 \x01(\fR\x06devEUI\x12\x19\n" +
	"\bdev_addr\x18\x05 \x01(\fR\adevAddr\x12,\n" +
	"\arx_info\x18\x06 \x03(\v2\x13.gw_v3.UplinkRXInfoR\x06rxInfo\x12,\n" +
	"\atx_info\x18\a \x01(\v2\x13.gw_v3.UplinkTXInfoR\x06txInfo\x12\x0e\n" +
	"\x02dr\x18\b \x01(\rR\x02dr\x127\n" +
	"\x04tags\x18\t \x03(\v2#.integration_v3.JoinEvent.TagsEntryR\x04tags\x12=\n" +
	"\fpublished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x02\n" +
	"\bAckEvent\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x04R\rapplicationID\x12)\n" +
	"\x10application_name\x18\x02 \x01(\tR\x0fapplicationName\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x17\n" +
	"\adev_eui\x18\x04 \x01(\fR\x06devEUI\x12\"\n" +
	"\facknowledged\x18\x05 \x01(\bR\facknowledged\x12\x13\n" +
	"\x05f_cnt\x18\x06 \x01(\rR\x04fCnt\x126\n" +
	"\x04tags\x18\a \x03(\v2\".integration_v3.AckEvent.TagsEntryR\x04tags\x12=\n" +
	"\fpublished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x03\n" +
	"\n" +
	"TxAckEvent\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x04R\rapplicationID\x12)\n" +
	"\x10application_name\x18\x02 \x01(\tR\x0fapplicationName\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x17\n" +
	"\adev_eui\x18\x04 \x01(\fR\x06devEUI\x12\x13\n" +
	"\x05f_cnt\x18\x05 \x01(\rR\x04fCnt\x128\n" +
	"\x04tags\x18\x06 \x03(\v2$.integration_v3.TxAckEvent.TagsEntryR\x04tags\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\a \x01(\fR\tgatewayID\x12.\n" +
	"\atx_info\x18\b \x01(\v2\x15.gw_v3.DownlinkTXInfoR\x06txInfo\x12=\n" +
	"\fpublished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x03\n" +
	"\n" +
	"ErrorEvent\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x04R\rapplicationID\x12)\n" +
	"\x10application_name\x18\x02 \x01(\tR\x0fapplicationName\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x17\n" +
	"\adev_eui\x18\x04 \x01(\fR\x06devEUI\x12-\n" +
	"\x04type\x18\x05 \x01(\x0e2\x19.integration_v3.ErrorTypeR\x04type\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x13\n" +
	"\x05f_cnt\x18\a \x01(\rR\x04fCnt\x128\n" +
	"\x04tags\x18\b \x03(\v2$.integration_v3.ErrorEvent.TagsEntryR\x04tags\x12=\n" +
	"\fpublished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x03\n" +
	"\vStatusEvent\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x04R\rapplicationID\x12)\n" +
	"\x10application_name\x18\x02 \x01(\tR\x0fapplicationName\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x17\n" +
	"\adev_eui\x18\x04 \x01(\fR\x06devEUI\x12\x16\n" +
	"\x06margin\x18\x05 \x01(\x05R\x06margin\x122\n" +
	"\x15external_power_source\x18\x06 \x01(\bR\x13externalPowerSource\x12:\n" +
	"\x19battery_level_unavailable\x18\a \x01(\bR\x17batteryLevelUnavailable\x12#\n" +
	"\rbattery_level\x18\b \x01(\x02R\fbatteryLevel\x129\n" +
	"\x04tags\x18\t \x03(\v2%.integration_v3.StatusEvent.TagsEntryR\x04tags\x12=\n" +
	"\fpublished_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x03\n" +
	"\rLocationEvent\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x04R\rapplicationID\x12)\n" +
	"\x10application_name\x18\x02 \x01(\tR\x0fapplicationName\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x17\n" +
	"\adev_eui\x18\x04 \x01(\fR\x06devEUI\x12/\n" +
	"\blocation\x18\x05 \x01(\v2\x13.common_v3.LocationR\blocation\x12;\n" +
	"\x04tags\x18\x06 \x03(\v2'.integration_v3.LocationEvent.TagsEntryR\x04tags\x12\x1d\n" +
	"\n" +
	"uplink_ids\x18\a \x03(\fR\tuplinkIDs\x12\x13\n" +
	"\x05f_cnt\x18\b \x01(\rR\x04fCnt\x12=\n" +
	"\fpublished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x03\n" +
	"\x10IntegrationEvent\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x04R\rapplicationID\x12)\n" +
	"\x10application_name\x18\x02 \x01(\tR\x0fapplicationName\x12\x1f\n" +
	"\vdevice_name\x18\x03 \x01(\tR\n" +
	"deviceName\x12\x17\n" +
	"\adev_eui\x18\x04 \x01(\fR\x06devEUI\x12>\n" +
	"\x04tags\x18\x05 \x03(\v2*.integration_v3.IntegrationEvent.TagsEntryR\x04tags\x12)\n" +
	"\x10integration_name\x18\x06 \x01(\tR\x0fintegrationName\x12\x1d\n" +
	"\n" +
	"event_type\x18\a \x01(\tR\teventType\x12\x1f\n" +
	"\vobject_json\x18\b \x01(\tR\n" +
	"objectJSON\x12=\n" +
	"\fpublished_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xd3\x01\n" +
	"\tErrorType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x19\n" +
	"\x15DOWNLINK_PAYLOAD_SIZE\x10\x01\x12\x11\n" +
	"\rDOWNLINK_FCNT\x10\x02\x12\x10\n" +
	"\fUPLINK_CODEC\x10\x03\x12\x12\n" +
	"\x0eDOWNLINK_CODEC\x10\x04\x12\b\n" +
	"\x04OTAA\x10\x05\x12\x15\n" +
	"\x11UPLINK_FCNT_RESET\x10\x06\x12\x0e\n" +
	"\n" +
	"UPLINK_MIC\x10\a\x12\x1e\n" +
	"\x1aUPLINK_FCNT_RETRANSMISSION\x10\b\x12\x14\n" +
	"\x10DOWNLINK_GATEWAY\x10\tBt\n" +
	"&io.chirpstack.api_v3.as_v3.integrationB\x10IntegrationProtoP\x01Z6github.com/brocaar/chirpstack-api/go/v3/as/integrationb\x06proto3"

var (
	file_as_integration_integration_v3_proto_rawDescOnce sync.Once
	file_as_integration_integration_v3_proto_rawDescData []byte
)

func file_as_integration_integration_v3_proto_rawDescGZIP() []byte {
	file_as_integration_integration_v3_proto_rawDescOnce.Do(func() {
		file_as_integration_integration_v3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_as_integration_integration_v3_proto_rawDesc), len(file_as_integration_integration_v3_proto_rawDesc)))
	})
	return file_as_integration_integration_v3_proto_rawDescData
}

var file_as_integration_integration_v3_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_as_integration_integration_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_as_integration_integration_v3_proto_goTypes = []any{
	(ErrorType)(0),              // 0: integration_v3.ErrorType
	(*UplinkEvent)(nil),         // 1: integration_v3.UplinkEvent
	(*JoinEvent)(nil),           // 2: integration_v3.JoinEvent
	(*AckEvent)(nil),            // 3: integration_v3.AckEvent
	(*TxAckEvent)(nil),          // 4: integration_v3.TxAckEvent
	(*ErrorEvent)(nil),          // 5: integration_v3.ErrorEvent
	(*StatusEvent)(nil),         // 6: integration_v3.StatusEvent
	(*LocationEvent)(nil),       // 7: integration_v3.LocationEvent
	(*IntegrationEvent)(nil),    // 8: integration_v3.IntegrationEvent
	nil,                         // 9: integration_v3.UplinkEvent.TagsEntry
	nil,                         // 10: integration_v3.JoinEvent.TagsEntry
	nil,                         // 11: integration_v3.AckEvent.TagsEntry
	nil,                         // 12: integration_v3.TxAckEvent.TagsEntry
	nil,                         // 13: integration_v3.ErrorEvent.TagsEntry
	nil,                         // 14: integration_v3.StatusEvent.TagsEntry
	nil,                         // 15: integration_v3.LocationEvent.TagsEntry
	nil,                         // 16: integration_v3.IntegrationEvent.TagsEntry
	(*gw.UplinkRXInfo)(nil),     // 17: gw_v3.UplinkRXInfo
	(*gw.UplinkTXInfo)(nil),     // 18: gw_v3.UplinkTXInfo
	(*timestamp.Timestamp)(nil), // 19: google.protobuf.Timestamp
	(*gw.DownlinkTXInfo)(nil),   // 20: gw_v3.DownlinkTXInfo
	(*common.Location)(nil),     // 21: common_v3.Location
}
var file_as_integration_integration_v3_proto_depIdxs = []int32{
	17, // 0: integration_v3.UplinkEvent.rx_info:type_name -> gw_v3.UplinkRXInfo
	18, // 1: integration_v3.UplinkEvent.tx_info:type_name -> gw_v3.UplinkTXInfo
	9,  // 2: integration_v3.UplinkEvent.tags:type_name -> integration_v3.UplinkEvent.TagsEntry
	19, // 3: integration_v3.UplinkEvent.published_at:type_name -> google.protobuf.Timestamp
	17, // 4: integration_v3.JoinEvent.rx_info:type_name -> gw_v3.UplinkRXInfo
	18, // 5: integration_v3.JoinEvent.tx_info:type_name -> gw_v3.UplinkTXInfo
	10, // 6: integration_v3.JoinEvent.tags:type_name -> integration_v3.JoinEvent.TagsEntry
	19, // 7: integration_v3.JoinEvent.published_at:type_name -> google.protobuf.Timestamp
	11, // 8: integration_v3.AckEvent.tags:type_name -> integration_v3.AckEvent.TagsEntry
	19, // 9: integration_v3.AckEvent.published_at:type_name -> google.protobuf.Timestamp
	12, // 10: integration_v3.TxAckEvent.tags:type_name -> integration_v3.TxAckEvent.TagsEntry
	20, // 11: integration_v3.TxAckEvent.tx_info:type_name -> gw_v3.DownlinkTXInfo
	19, // 12: integration_v3.TxAckEvent.published_at:type_name -> google.protobuf.Timestamp
	0,  // 13: integration_v3.ErrorEvent.type:type_name -> integration_v3.ErrorType
	13, // 14: integration_v3.ErrorEvent.tags:type_name -> integration_v3.ErrorEvent.TagsEntry
	19, // 15: integration_v3.ErrorEvent.published_at:type_name -> google.protobuf.Timestamp
	14, // 16: integration_v3.StatusEvent.tags:type_name -> integration_v3.StatusEvent.TagsEntry
	19, // 17: integration_v3.StatusEvent.published_at:type_name -> google.protobuf.Timestamp
	21, // 18: integration_v3.LocationEvent.location:type_name -> common_v3.Location
	15, // 19: integration_v3.LocationEvent.tags:type_name -> integration_v3.LocationEvent.TagsEntry
	19, // 20: integration_v3.LocationEvent.published_at:type_name -> google.protobuf.Timestamp
	16, // 21: integration_v3.IntegrationEvent.tags:type_name -> integration_v3.IntegrationEvent.TagsEntry
	19, // 22: integration_v3.IntegrationEvent.published_at:type_name -> google.protobuf.Timestamp
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_as_integration_integration_v3_proto_init() }
func file_as_integration_integration_v3_proto_init() {
	if File_as_integration_integration_v3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_as_integration_integration_v3_proto_rawDesc), len(file_as_integration_integration_v3_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_as_integration_integration_v3_proto_goTypes,
		DependencyIndexes: file_as_integration_integration_v3_proto_depIdxs,
		EnumInfos:         file_as_integration_integration_v3_proto_enumTypes,
		MessageInfos:      file_as_integration_integration_v3_proto_msgTypes,
	}.Build()
	File_as_integration_integration_v3_proto = out.File
	file_as_integration_integration_v3_proto_goTypes = nil
	file_as_integration_integration_v3_proto_depIdxs = nil
}
