// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: fuota/fuota_v3.proto

package fuota

import (
	context "context"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MulticastGroupType int32

const (
	// Class-B.
	MulticastGroupType_CLASS_B MulticastGroupType = 0
	// Class-C.
	MulticastGroupType_CLASS_C MulticastGroupType = 1
)

// Enum value maps for MulticastGroupType.
var (
	MulticastGroupType_name = map[int32]string{
		0: "CLASS_B",
		1: "CLASS_C",
	}
	MulticastGroupType_value = map[string]int32{
		"CLASS_B": 0,
		"CLASS_C": 1,
	}
)

func (x MulticastGroupType) Enum() *MulticastGroupType {
	p := new(MulticastGroupType)
	*p = x
	return p
}

func (x MulticastGroupType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MulticastGroupType) Descriptor() protoreflect.EnumDescriptor {
	return file_fuota_fuota_v3_proto_enumTypes[0].Descriptor()
}

func (MulticastGroupType) Type() protoreflect.EnumType {
	return &file_fuota_fuota_v3_proto_enumTypes[0]
}

func (x MulticastGroupType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MulticastGroupType.Descriptor instead.
func (MulticastGroupType) EnumDescriptor() ([]byte, []int) {
	return file_fuota_fuota_v3_proto_rawDescGZIP(), []int{0}
}

type RequestFragmentationSessionStatus int32

const (
	// Enqueue the fragmentation-session status request command directly after
	// enqueueing the fragmentation-session fragments. This is the recommended
	// option for Class-A devices as the status request will stay in the
	// downlink queue until the device sends its next uplink.
	RequestFragmentationSessionStatus_AFTER_FRAGMENT_ENQUEUE RequestFragmentationSessionStatus = 0
	// Enqueue the fragmentation-session status request after the multicast
	// session-timeout. This is the recommended option for Class-B and -C
	// devices as selecting AFTER_FRAGMENT_ENQUEUE will likely cause the NS
	// to schedule the downlink frame during the FUOTA multicast-session.
	RequestFragmentationSessionStatus_AFTER_SESSION_TIMEOUT RequestFragmentationSessionStatus = 1
	// Do not request the fragmentation-session status.
	RequestFragmentationSessionStatus_NO_REQUEST RequestFragmentationSessionStatus = 2
)

// Enum value maps for RequestFragmentationSessionStatus.
var (
	RequestFragmentationSessionStatus_name = map[int32]string{
		0: "AFTER_FRAGMENT_ENQUEUE",
		1: "AFTER_SESSION_TIMEOUT",
		2: "NO_REQUEST",
	}
	RequestFragmentationSessionStatus_value = map[string]int32{
		"AFTER_FRAGMENT_ENQUEUE": 0,
		"AFTER_SESSION_TIMEOUT":  1,
		"NO_REQUEST":             2,
	}
)

func (x RequestFragmentationSessionStatus) Enum() *RequestFragmentationSessionStatus {
	p := new(RequestFragmentationSessionStatus)
	*p = x
	return p
}

func (x RequestFragmentationSessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestFragmentationSessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_fuota_fuota_v3_proto_enumTypes[1].Descriptor()
}

func (RequestFragmentationSessionStatus) Type() protoreflect.EnumType {
	return &file_fuota_fuota_v3_proto_enumTypes[1]
}

func (x RequestFragmentationSessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestFragmentationSessionStatus.Descriptor instead.
func (RequestFragmentationSessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_fuota_fuota_v3_proto_rawDescGZIP(), []int{1}
}

type DeploymentDevice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DevEUI.
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// McRootKey.
	McRootKey     []byte `protobuf:"bytes,2,opt,name=mc_root_key,json=mcRootKey,proto3" json:"mc_root_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentDevice) Reset() {
	*x = DeploymentDevice{}
	mi := &file_fuota_fuota_v3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentDevice) ProtoMessage() {}

func (x *DeploymentDevice) ProtoReflect() protoreflect.Message {
	mi := &file_fuota_fuota_v3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentDevice.ProtoReflect.Descriptor instead.
func (*DeploymentDevice) Descriptor() ([]byte, []int) {
	return file_fuota_fuota_v3_proto_rawDescGZIP(), []int{0}
}

func (x *DeploymentDevice) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *DeploymentDevice) GetMcRootKey() []byte {
	if x != nil {
		return x.McRootKey
	}
	return nil
}

type Deployment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Application ID.
	ApplicationId int64 `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	// Devices to include in this deployment.
	Devices []*DeploymentDevice `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	// Multicast-group type.
	MulticastGroupType MulticastGroupType `protobuf:"varint,3,opt,name=multicast_group_type,json=multicastGroupType,proto3,enum=fuota_v3.MulticastGroupType" json:"multicast_group_type,omitempty"`
	// Multicast data-rate.
	MulticastDr uint32 `protobuf:"varint,4,opt,name=multicast_dr,json=multicastDr,proto3" json:"multicast_dr,omitempty"`
	// Multicast ping-slot period (Class-B only).
	MulticastPingSlotPeriod uint32 `protobuf:"varint,5,opt,name=multicast_ping_slot_period,json=multicastPingSlotPeriod,proto3" json:"multicast_ping_slot_period,omitempty"`
	// Multicast frequency (Hz).
	MulticastFrequency uint32 `protobuf:"varint,6,opt,name=multicast_frequency,json=multicastFrequency,proto3" json:"multicast_frequency,omitempty"`
	// Multicast group ID.
	MulticastGroupId uint32 `protobuf:"varint,7,opt,name=multicast_group_id,json=multicastGroupId,proto3" json:"multicast_group_id,omitempty"`
	// Multicast timeout.
	// This defines the timeout of the multicast-session.
	// Please refer to the Remote Multicast Setup specification as this field
	// has a different meaning for Class-B and Class-C groups.
	MulticastTimeout uint32 `protobuf:"varint,8,opt,name=multicast_timeout,json=multicastTimeout,proto3" json:"multicast_timeout,omitempty"`
	// Unicast timeout.
	// Set this to the value in which you at least expect an uplink frame from
	// the device. The FUOTA server will wait for the given time before
	// attempting a retry or continuing with the next step.
	UnicastTimeout *duration.Duration `protobuf:"bytes,9,opt,name=unicast_timeout,json=unicastTimeout,proto3" json:"unicast_timeout,omitempty"`
	// Unicast attempt count.
	// The number of attempts before considering an unicast command
	// to be failed.
	UnicastAttemptCount uint32 `protobuf:"varint,10,opt,name=unicast_attempt_count,json=unicastAttemptCount,proto3" json:"unicast_attempt_count,omitempty"`
	// FragmentationFragmentSize.
	// This defines the size of each payload fragment. Please refer to the
	// Regional Parameters specification for the maximum payload sizes
	// per data-rate and region.
	FragmentationFragmentSize uint32 `protobuf:"varint,11,opt,name=fragmentation_fragment_size,json=fragmentationFragmentSize,proto3" json:"fragmentation_fragment_size,omitempty"`
	// Payload.
	Payload []byte `protobuf:"bytes,12,opt,name=payload,proto3" json:"payload,omitempty"`
	// Fragmentation redundancy.
	// The number represents the additional redundant frames to send.
	FragmentationRedundancy uint32 `protobuf:"varint,13,opt,name=fragmentation_redundancy,json=fragmentationRedundancy,proto3" json:"fragmentation_redundancy,omitempty"`
	// Fragmentation session index.
	FragmentationSessionIndex uint32 `protobuf:"varint,14,opt,name=fragmentation_session_index,json=fragmentationSessionIndex,proto3" json:"fragmentation_session_index,omitempty"`
	// Fragmentation matrix.
	FragmentationMatrix uint32 `protobuf:"varint,15,opt,name=fragmentation_matrix,json=fragmentationMatrix,proto3" json:"fragmentation_matrix,omitempty"`
	// Block ack delay.
	FragmentationBlockAckDelay uint32 `protobuf:"varint,16,opt,name=fragmentation_block_ack_delay,json=fragmentationBlockAckDelay,proto3" json:"fragmentation_block_ack_delay,omitempty"`
	// Descriptor (4 bytes).
	FragmentationDescriptor []byte `protobuf:"bytes,17,opt,name=fragmentation_descriptor,json=fragmentationDescriptor,proto3" json:"fragmentation_descriptor,omitempty"`
	// Request fragmentation session status.
	RequestFragmentationSessionStatus RequestFragmentationSessionStatus `protobuf:"varint,18,opt,name=request_fragmentation_session_status,json=requestFragmentationSessionStatus,proto3,enum=fuota_v3.RequestFragmentationSessionStatus" json:"request_fragmentation_session_status,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	mi := &file_fuota_fuota_v3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_fuota_fuota_v3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_fuota_fuota_v3_proto_rawDescGZIP(), []int{1}
}

func (x *Deployment) GetApplicationId() int64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *Deployment) GetDevices() []*DeploymentDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *Deployment) GetMulticastGroupType() MulticastGroupType {
	if x != nil {
		return x.MulticastGroupType
	}
	return MulticastGroupType_CLASS_B
}

func (x *Deployment) GetMulticastDr() uint32 {
	if x != nil {
		return x.MulticastDr
	}
	return 0
}

func (x *Deployment) GetMulticastPingSlotPeriod() uint32 {
	if x != nil {
		return x.MulticastPingSlotPeriod
	}
	return 0
}

func (x *Deployment) GetMulticastFrequency() uint32 {
	if x != nil {
		return x.MulticastFrequency
	}
	return 0
}

func (x *Deployment) GetMulticastGroupId() uint32 {
	if x != nil {
		return x.MulticastGroupId
	}
	return 0
}

func (x *Deployment) GetMulticastTimeout() uint32 {
	if x != nil {
		return x.MulticastTimeout
	}
	return 0
}

func (x *Deployment) GetUnicastTimeout() *duration.Duration {
	if x != nil {
		return x.UnicastTimeout
	}
	return nil
}

func (x *Deployment) GetUnicastAttemptCount() uint32 {
	if x != nil {
		return x.UnicastAttemptCount
	}
	return 0
}

func (x *Deployment) GetFragmentationFragmentSize() uint32 {
	if x != nil {
		return x.FragmentationFragmentSize
	}
	return 0
}

func (x *Deployment) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Deployment) GetFragmentationRedundancy() uint32 {
	if x != nil {
		return x.FragmentationRedundancy
	}
	return 0
}

func (x *Deployment) GetFragmentationSessionIndex() uint32 {
	if x != nil {
		return x.FragmentationSessionIndex
	}
	return 0
}

func (x *Deployment) GetFragmentationMatrix() uint32 {
	if x != nil {
		return x.FragmentationMatrix
	}
	return 0
}

func (x *Deployment) GetFragmentationBlockAckDelay() uint32 {
	if x != nil {
		return x.FragmentationBlockAckDelay
	}
	return 0
}

func (x *Deployment) GetFragmentationDescriptor() []byte {
	if x != nil {
		return x.FragmentationDescriptor
	}
	return nil
}

func (x *Deployment) GetRequestFragmentationSessionStatus() RequestFragmentationSessionStatus {
	if x != nil {
		return x.RequestFragmentationSessionStatus
	}
	return RequestFragmentationSessionStatus_AFTER_FRAGMENT_ENQUEUE
}

type CreateDeploymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deployment.
	Deployment    *Deployment `protobuf:"bytes,1,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeploymentRequest) Reset() {
	*x = CreateDeploymentRequest{}
	mi := &file_fuota_fuota_v3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeploymentRequest) ProtoMessage() {}

func (x *CreateDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fuota_fuota_v3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeploymentRequest.ProtoReflect.Descriptor instead.
func (*CreateDeploymentRequest) Descriptor() ([]byte, []int) {
	return file_fuota_fuota_v3_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDeploymentRequest) GetDeployment() *Deployment {
	if x != nil {
		return x.Deployment
	}
	return nil
}

type CreateDeploymentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the created deployment.
	Id            []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeploymentResponse) Reset() {
	*x = CreateDeploymentResponse{}
	mi := &file_fuota_fuota_v3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeploymentResponse) ProtoMessage() {}

func (x *CreateDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fuota_fuota_v3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeploymentResponse.ProtoReflect.Descriptor instead.
func (*CreateDeploymentResponse) Descriptor() ([]byte, []int) {
	return file_fuota_fuota_v3_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDeploymentResponse) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type GetDeploymentStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deployment ID.
	Id            []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentStatusRequest) Reset() {
	*x = GetDeploymentStatusRequest{}
	mi := &file_fuota_fuota_v3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentStatusRequest) ProtoMessage() {}

func (x *GetDeploymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fuota_fuota_v3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_fuota_fuota_v3_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeploymentStatusRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeploymentDeviceStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DevEUI.
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Created at.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated at.
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Multicast-group setup completed at.
	McGroupSetupCompletedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=mc_group_setup_completed_at,json=mcGroupSetupCompletedAt,proto3" json:"mc_group_setup_completed_at,omitempty"`
	// Multicast-session completed at.
	McSessionCompletedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=mc_session_completed_at,json=mcSessionCompletedAt,proto3" json:"mc_session_completed_at,omitempty"`
	// Fragmentation session setup completed at.
	FragSessionSetupCompletedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=frag_session_setup_completed_at,json=fragSessionSetupCompletedAt,proto3" json:"frag_session_setup_completed_at,omitempty"`
	// Fragmentation status completed at.
	FragStatusCompletedAt *timestamp.Timestamp `protobuf:"bytes,7,opt,name=frag_status_completed_at,json=fragStatusCompletedAt,proto3" json:"frag_status_completed_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeploymentDeviceStatus) Reset() {
	*x = DeploymentDeviceStatus{}
	mi := &file_fuota_fuota_v3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentDeviceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentDeviceStatus) ProtoMessage() {}

func (x *DeploymentDeviceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fuota_fuota_v3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentDeviceStatus.ProtoReflect.Descriptor instead.
func (*DeploymentDeviceStatus) Descriptor() ([]byte, []int) {
	return file_fuota_fuota_v3_proto_rawDescGZIP(), []int{5}
}

func (x *DeploymentDeviceStatus) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *DeploymentDeviceStatus) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeploymentDeviceStatus) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *DeploymentDeviceStatus) GetMcGroupSetupCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.McGroupSetupCompletedAt
	}
	return nil
}

func (x *DeploymentDeviceStatus) GetMcSessionCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.McSessionCompletedAt
	}
	return nil
}

func (x *DeploymentDeviceStatus) GetFragSessionSetupCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.FragSessionSetupCompletedAt
	}
	return nil
}

func (x *DeploymentDeviceStatus) GetFragStatusCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.FragStatusCompletedAt
	}
	return nil
}

type GetDeploymentStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created at.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated at.
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Multicast-group setup completed at.
	McGroupSetupCompletedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=mc_group_setup_completed_at,json=mcGroupSetupCompletedAt,proto3" json:"mc_group_setup_completed_at,omitempty"`
	// Multicast-session completed at.
	McSessionCompletedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=mc_session_completed_at,json=mcSessionCompletedAt,proto3" json:"mc_session_completed_at,omitempty"`
	// Fragmentation session setup completed at.
	FragSessionSetupCompletedAt *timestamp.Timestamp `protobuf:"bytes,5,opt,name=frag_session_setup_completed_at,json=fragSessionSetupCompletedAt,proto3" json:"frag_session_setup_completed_at,omitempty"`
	// Enqueue completed at.
	EnqueueCompletedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=enqueue_completed_at,json=enqueueCompletedAt,proto3" json:"enqueue_completed_at,omitempty"`
	// Fragmentation status completed at.
	FragStatusCompletedAt *timestamp.Timestamp `protobuf:"bytes,7,opt,name=frag_status_completed_at,json=fragStatusCompletedAt,proto3" json:"frag_status_completed_at,omitempty"`
	// Per device status.
	DeviceStatus  []*DeploymentDeviceStatus `protobuf:"bytes,8,rep,name=device_status,json=deviceStatus,proto3" json:"device_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentStatusResponse) Reset() {
	*x = GetDeploymentStatusResponse{}
	mi := &file_fuota_fuota_v3_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentStatusResponse) ProtoMessage() {}

func (x *GetDeploymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fuota_fuota_v3_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_fuota_fuota_v3_proto_rawDescGZIP(), []int{6}
}

func (x *GetDeploymentStatusResponse) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetDeploymentStatusResponse) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetDeploymentStatusResponse) GetMcGroupSetupCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.McGroupSetupCompletedAt
	}
	return nil
}

func (x *GetDeploymentStatusResponse) GetMcSessionCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.McSessionCompletedAt
	}
	return nil
}

func (x *GetDeploymentStatusResponse) GetFragSessionSetupCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.FragSessionSetupCompletedAt
	}
	return nil
}

func (x *GetDeploymentStatusResponse) GetEnqueueCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.EnqueueCompletedAt
	}
	return nil
}

func (x *GetDeploymentStatusResponse) GetFragStatusCompletedAt() *timestamp.Timestamp {
	if x != nil {
		return x.FragStatusCompletedAt
	}
	return nil
}

func (x *GetDeploymentStatusResponse) GetDeviceStatus() []*DeploymentDeviceStatus {
	if x != nil {
		return x.DeviceStatus
	}
	return nil
}

type GetDeploymentDeviceLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deployment ID.
	DeploymentId []byte `protobuf:"bytes,1,opt,name=deployment_id,json=deploymentId,proto3" json:"deployment_id,omitempty"`
	// DevEUI.
	DevEui        []byte `protobuf:"bytes,2,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentDeviceLogsRequest) Reset() {
	*x = GetDeploymentDeviceLogsRequest{}
	mi := &file_fuota_fuota_v3_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentDeviceLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentDeviceLogsRequest) ProtoMessage() {}

func (x *GetDeploymentDeviceLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fuota_fuota_v3_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentDeviceLogsRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentDeviceLogsRequest) Descriptor() ([]byte, []int) {
	return file_fuota_fuota_v3_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeploymentDeviceLogsRequest) GetDeploymentId() []byte {
	if x != nil {
		return x.DeploymentId
	}
	return nil
}

func (x *GetDeploymentDeviceLogsRequest) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

type DeploymentDeviceLog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Created at.
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// FPort.
	FPort uint32 `protobuf:"varint,2,opt,name=f_port,json=fPort,proto3" json:"f_port,omitempty"`
	// Command.
	Command string `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	// Fields.
	Fields        map[string]string `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentDeviceLog) Reset() {
	*x = DeploymentDeviceLog{}
	mi := &file_fuota_fuota_v3_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentDeviceLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentDeviceLog) ProtoMessage() {}

func (x *DeploymentDeviceLog) ProtoReflect() protoreflect.Message {
	mi := &file_fuota_fuota_v3_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentDeviceLog.ProtoReflect.Descriptor instead.
func (*DeploymentDeviceLog) Descriptor() ([]byte, []int) {
	return file_fuota_fuota_v3_proto_rawDescGZIP(), []int{8}
}

func (x *DeploymentDeviceLog) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DeploymentDeviceLog) GetFPort() uint32 {
	if x != nil {
		return x.FPort
	}
	return 0
}

func (x *DeploymentDeviceLog) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *DeploymentDeviceLog) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type GetDeploymentDeviceLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*DeploymentDeviceLog `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentDeviceLogsResponse) Reset() {
	*x = GetDeploymentDeviceLogsResponse{}
	mi := &file_fuota_fuota_v3_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentDeviceLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentDeviceLogsResponse) ProtoMessage() {}

func (x *GetDeploymentDeviceLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fuota_fuota_v3_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentDeviceLogsResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentDeviceLogsResponse) Descriptor() ([]byte, []int) {
	return file_fuota_fuota_v3_proto_rawDescGZIP(), []int{9}
}

func (x *GetDeploymentDeviceLogsResponse) GetLogs() []*DeploymentDeviceLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_fuota_fuota_v3_proto protoreflect.FileDescriptor

const file_fuota_fuota_v3_proto_rawDesc = "" +
	"\n" +
	"\x14fuota/fuota_v3.proto\x12\bfuota_v3\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"K\n" +
	"\x10DeploymentDevice\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEui\x12\x1e\n" +
	"\vmc_root_key\x18\x02 \x01(\fR\tmcRootKey\"\xa1\b\n" +
	"\n" +
	"Deployment\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x03R\rapplicationId\x124\n" +
	"\adevices\x18\x02 \x03(\v2\x1a.fuota_v3.DeploymentDeviceR\adevices\x12N\n" +
	"\x14multicast_group_type\x18\x03 \x01(\x0e2\x1c.fuota_v3.MulticastGroupTypeR\x12multicastGroupType\x12!\n" +
	"\fmulticast_dr\x18\x04 \x01(\rR\vmulticastDr\x12;\n" +
	"\x1amulticast_ping_slot_period\x18\x05 \x01(\rR\x17multicastPingSlotPeriod\x12/\n" +
	"\x13multicast_frequency\x18\x06 \x01(\rR\x12multicastFrequency\x12,\n" +
	"\x12multicast_group_id\x18\a \x01(\rR\x10multicastGroupId\x12+\n" +
	"\x11multicast_timeout\x18\b \x01(\rR\x10multicastTimeout\x12B\n" +
	"\x0funicast_timeout\x18\t \x01(\v2\x19.google.protobuf.DurationR\x0eunicastTimeout\x122\n" +
	"\x15unicast_attempt_count\x18\n" +
	" \x01(\rR\x13unicastAttemptCount\x12>\n" +
	"\x1bfragmentation_fragment_size\x18\v \x01(\rR\x19fragmentationFragmentSize\x12\x18\n" +
	"\apayload\x18\f \x01(\fR\apayload\x129\n" +
	"\x18fragmentation_redundancy\x18\r \x01(\rR\x17fragmentationRedundancy\x12>\n" +
	"\x1bfragmentation_session_index\x18\x0e \x01(\rR\x19fragmentationSessionIndex\x121\n" +
	"\x14fragmentation_matrix\x18\x0f \x01(\rR\x13fragmentationMatrix\x12A\n" +
	"\x1dfragmentation_block_ack_delay\x18\x10 \x01(\rR\x1afragmentationBlockAckDelay\x129\n" +
	"\x18fragmentation_descriptor\x18\x11 \x01(\fR\x17fragmentationDescriptor\x12|\n" +
	"$request_fragmentation_session_status\x18\x12 \x01(\x0e2+.fuota_v3.RequestFragmentationSessionStatusR!requestFragmentationSessionStatus\"O\n" +
	"\x17CreateDeploymentRequest\x124\n" +
	"\n" +
	"deployment\x18\x01 \x01(\v2\x14.fuota_v3.DeploymentR\n" +
	"deployment\"*\n" +
	"\x18CreateDeploymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\",\n" +
	"\x1aGetDeploymentStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\"\x8b\x04\n" +
	"\x16DeploymentDeviceStatus\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEui\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12X\n" +
	"\x1bmc_group_setup_completed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x17mcGroupSetupCompletedAt\x12Q\n" +
	"\x17mc_session_completed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x14mcSessionCompletedAt\x12`\n" +
	"\x1ffrag_session_setup_completed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x1bfragSessionSetupCompletedAt\x12S\n" +
	"\x18frag_status_completed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x15fragStatusCompletedAt\"\x8c\x05\n" +
	"\x1bGetDeploymentStatusResponse\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12X\n" +
	"\x1bmc_group_setup_completed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x17mcGroupSetupCompletedAt\x12Q\n" +
	"\x17mc_session_completed_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x14mcSessionCompletedAt\x12`\n" +
	"\x1ffrag_session_setup_completed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x1bfragSessionSetupCompletedAt\x12L\n" +
	"\x14enqueue_completed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x12enqueueCompletedAt\x12S\n" +
	"\x18frag_status_completed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x15fragStatusCompletedAt\x12E\n" +
	"\rdevice_status\x18\b \x03(\v2 .fuota_v3.DeploymentDeviceStatusR\fdeviceStatus\"^\n" +
	"\x1eGetDeploymentDeviceLogsRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\fR\fdeploymentId\x12\x17\n" +
	"\adev_eui\x18\x02 \x01(\fR\x06devEui\"\xff\x01\n" +
	"\x13DeploymentDeviceLog\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x15\n" +
	"\x06f_port\x18\x02 \x01(\rR\x05fPort\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12A\n" +
	"\x06fields\x18\x04 \x03(\v2).fuota_v3.DeploymentDeviceLog.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"T\n" +
	"\x1fGetDeploymentDeviceLogsResponse\x121\n" +
	"\x04logs\x18\x01 \x03(\v2\x1d.fuota_v3.DeploymentDeviceLogR\x04logs*.\n" +
	"\x12MulticastGroupType\x12\v\n" +
	"\aCLASS_B\x10\x00\x12\v\n" +
	"\aCLASS_C\x10\x01*j\n" +
	"!RequestFragmentationSessionStatus\x12\x1a\n" +
	"\x16AFTER_FRAGMENT_ENQUEUE\x10\x00\x12\x19\n" +
	"\x15AFTER_SESSION_TIMEOUT\x10\x01\x12\x0e\n" +
	"\n" +
	"NO_REQUEST\x10\x022\xc9\x02\n" +
	"\x12FUOTAServerService\x12[\n" +
	"\x10CreateDeployment\x12!.fuota_v3.CreateDeploymentRequest\x1a\".fuota_v3.CreateDeploymentResponse\"\x00\x12d\n" +
	"\x13GetDeploymentStatus\x12$.fuota_v3.GetDeploymentStatusRequest\x1a%.fuota_v3.GetDeploymentStatusResponse\"\x00\x12p\n" +
	"\x17GetDeploymentDeviceLogs\x12(.fuota_v3.GetDeploymentDeviceLogsRequest\x1a).fuota_v3.GetDeploymentDeviceLogsResponse\"\x00BN\n" +
	"\x1aio.chirpstack.api_v3.fuotaZ0github.com/IoTOpen/chirpstack-v3-api/go/v3/fuotab\x06proto3"

var (
	file_fuota_fuota_v3_proto_rawDescOnce sync.Once
	file_fuota_fuota_v3_proto_rawDescData []byte
)

func file_fuota_fuota_v3_proto_rawDescGZIP() []byte {
	file_fuota_fuota_v3_proto_rawDescOnce.Do(func() {
		file_fuota_fuota_v3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fuota_fuota_v3_proto_rawDesc), len(file_fuota_fuota_v3_proto_rawDesc)))
	})
	return file_fuota_fuota_v3_proto_rawDescData
}

var file_fuota_fuota_v3_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_fuota_fuota_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_fuota_fuota_v3_proto_goTypes = []any{
	(MulticastGroupType)(0),                 // 0: fuota_v3.MulticastGroupType
	(RequestFragmentationSessionStatus)(0),  // 1: fuota_v3.RequestFragmentationSessionStatus
	(*DeploymentDevice)(nil),                // 2: fuota_v3.DeploymentDevice
	(*Deployment)(nil),                      // 3: fuota_v3.Deployment
	(*CreateDeploymentRequest)(nil),         // 4: fuota_v3.CreateDeploymentRequest
	(*CreateDeploymentResponse)(nil),        // 5: fuota_v3.CreateDeploymentResponse
	(*GetDeploymentStatusRequest)(nil),      // 6: fuota_v3.GetDeploymentStatusRequest
	(*DeploymentDeviceStatus)(nil),          // 7: fuota_v3.DeploymentDeviceStatus
	(*GetDeploymentStatusResponse)(nil),     // 8: fuota_v3.GetDeploymentStatusResponse
	(*GetDeploymentDeviceLogsRequest)(nil),  // 9: fuota_v3.GetDeploymentDeviceLogsRequest
	(*DeploymentDeviceLog)(nil),             // 10: fuota_v3.DeploymentDeviceLog
	(*GetDeploymentDeviceLogsResponse)(nil), // 11: fuota_v3.GetDeploymentDeviceLogsResponse
	nil,                                     // 12: fuota_v3.DeploymentDeviceLog.FieldsEntry
	(*duration.Duration)(nil),               // 13: google.protobuf.Duration
	(*timestamp.Timestamp)(nil),             // 14: google.protobuf.Timestamp
}
var file_fuota_fuota_v3_proto_depIdxs = []int32{
	2,  // 0: fuota_v3.Deployment.devices:type_name -> fuota_v3.DeploymentDevice
	0,  // 1: fuota_v3.Deployment.multicast_group_type:type_name -> fuota_v3.MulticastGroupType
	13, // 2: fuota_v3.Deployment.unicast_timeout:type_name -> google.protobuf.Duration
	1,  // 3: fuota_v3.Deployment.request_fragmentation_session_status:type_name -> fuota_v3.RequestFragmentationSessionStatus
	3,  // 4: fuota_v3.CreateDeploymentRequest.deployment:type_name -> fuota_v3.Deployment
	14, // 5: fuota_v3.DeploymentDeviceStatus.created_at:type_name -> google.protobuf.Timestamp
	14, // 6: fuota_v3.DeploymentDeviceStatus.updated_at:type_name -> google.protobuf.Timestamp
	14, // 7: fuota_v3.DeploymentDeviceStatus.mc_group_setup_completed_at:type_name -> google.protobuf.Timestamp
	14, // 8: fuota_v3.DeploymentDeviceStatus.mc_session_completed_at:type_name -> google.protobuf.Timestamp
	14, // 9: fuota_v3.DeploymentDeviceStatus.frag_session_setup_completed_at:type_name -> google.protobuf.Timestamp
	14, // 10: fuota_v3.DeploymentDeviceStatus.frag_status_completed_at:type_name -> google.protobuf.Timestamp
	14, // 11: fuota_v3.GetDeploymentStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 12: fuota_v3.GetDeploymentStatusResponse.updated_at:type_name -> google.protobuf.Timestamp
	14, // 13: fuota_v3.GetDeploymentStatusResponse.mc_group_setup_completed_at:type_name -> google.protobuf.Timestamp
	14, // 14: fuota_v3.GetDeploymentStatusResponse.mc_session_completed_at:type_name -> google.protobuf.Timestamp
	14, // 15: fuota_v3.GetDeploymentStatusResponse.frag_session_setup_completed_at:type_name -> google.protobuf.Timestamp
	14, // 16: fuota_v3.GetDeploymentStatusResponse.enqueue_completed_at:type_name -> google.protobuf.Timestamp
	14, // 17: fuota_v3.GetDeploymentStatusResponse.frag_status_completed_at:type_name -> google.protobuf.Timestamp
	7,  // 18: fuota_v3.GetDeploymentStatusResponse.device_status:type_name -> fuota_v3.DeploymentDeviceStatus
	14, // 19: fuota_v3.DeploymentDeviceLog.created_at:type_name -> google.protobuf.Timestamp
	12, // 20: fuota_v3.DeploymentDeviceLog.fields:type_name -> fuota_v3.DeploymentDeviceLog.FieldsEntry
	10, // 21: fuota_v3.GetDeploymentDeviceLogsResponse.logs:type_name -> fuota_v3.DeploymentDeviceLog
	4,  // 22: fuota_v3.FUOTAServerService.CreateDeployment:input_type -> fuota_v3.CreateDeploymentRequest
	6,  // 23: fuota_v3.FUOTAServerService.GetDeploymentStatus:input_type -> fuota_v3.GetDeploymentStatusRequest
	9,  // 24: fuota_v3.FUOTAServerService.GetDeploymentDeviceLogs:input_type -> fuota_v3.GetDeploymentDeviceLogsRequest
	5,  // 25: fuota_v3.FUOTAServerService.CreateDeployment:output_type -> fuota_v3.CreateDeploymentResponse
	8,  // 26: fuota_v3.FUOTAServerService.GetDeploymentStatus:output_type -> fuota_v3.GetDeploymentStatusResponse
	11, // 27: fuota_v3.FUOTAServerService.GetDeploymentDeviceLogs:output_type -> fuota_v3.GetDeploymentDeviceLogsResponse
	25, // [25:28] is the sub-list for method output_type
	22, // [22:25] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_fuota_fuota_v3_proto_init() }
func file_fuota_fuota_v3_proto_init() {
	if File_fuota_fuota_v3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fuota_fuota_v3_proto_rawDesc), len(file_fuota_fuota_v3_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fuota_fuota_v3_proto_goTypes,
		DependencyIndexes: file_fuota_fuota_v3_proto_depIdxs,
		EnumInfos:         file_fuota_fuota_v3_proto_enumTypes,
		MessageInfos:      file_fuota_fuota_v3_proto_msgTypes,
	}.Build()
	File_fuota_fuota_v3_proto = out.File
	file_fuota_fuota_v3_proto_goTypes = nil
	file_fuota_fuota_v3_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FUOTAServerServiceClient is the client API for FUOTAServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FUOTAServerServiceClient interface {
	// CreateDeployment creates the given FUOTA deployment.
	CreateDeployment(ctx context.Context, in *CreateDeploymentRequest, opts ...grpc.CallOption) (*CreateDeploymentResponse, error)
	// GetDeploymentStatus returns the FUOTA deployment status given an ID.
	GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error)
	// GetDeploymentDeviceLogs returns the FUOTA logs given a deployment ID and DevEUI.
	GetDeploymentDeviceLogs(ctx context.Context, in *GetDeploymentDeviceLogsRequest, opts ...grpc.CallOption) (*GetDeploymentDeviceLogsResponse, error)
}

type fUOTAServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFUOTAServerServiceClient(cc grpc.ClientConnInterface) FUOTAServerServiceClient {
	return &fUOTAServerServiceClient{cc}
}

func (c *fUOTAServerServiceClient) CreateDeployment(ctx context.Context, in *CreateDeploymentRequest, opts ...grpc.CallOption) (*CreateDeploymentResponse, error) {
	out := new(CreateDeploymentResponse)
	err := c.cc.Invoke(ctx, "/fuota_v3.FUOTAServerService/CreateDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTAServerServiceClient) GetDeploymentStatus(ctx context.Context, in *GetDeploymentStatusRequest, opts ...grpc.CallOption) (*GetDeploymentStatusResponse, error) {
	out := new(GetDeploymentStatusResponse)
	err := c.cc.Invoke(ctx, "/fuota_v3.FUOTAServerService/GetDeploymentStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fUOTAServerServiceClient) GetDeploymentDeviceLogs(ctx context.Context, in *GetDeploymentDeviceLogsRequest, opts ...grpc.CallOption) (*GetDeploymentDeviceLogsResponse, error) {
	out := new(GetDeploymentDeviceLogsResponse)
	err := c.cc.Invoke(ctx, "/fuota_v3.FUOTAServerService/GetDeploymentDeviceLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FUOTAServerServiceServer is the server API for FUOTAServerService service.
type FUOTAServerServiceServer interface {
	// CreateDeployment creates the given FUOTA deployment.
	CreateDeployment(context.Context, *CreateDeploymentRequest) (*CreateDeploymentResponse, error)
	// GetDeploymentStatus returns the FUOTA deployment status given an ID.
	GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error)
	// GetDeploymentDeviceLogs returns the FUOTA logs given a deployment ID and DevEUI.
	GetDeploymentDeviceLogs(context.Context, *GetDeploymentDeviceLogsRequest) (*GetDeploymentDeviceLogsResponse, error)
}

// UnimplementedFUOTAServerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFUOTAServerServiceServer struct {
}

func (*UnimplementedFUOTAServerServiceServer) CreateDeployment(context.Context, *CreateDeploymentRequest) (*CreateDeploymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDeployment not implemented")
}
func (*UnimplementedFUOTAServerServiceServer) GetDeploymentStatus(context.Context, *GetDeploymentStatusRequest) (*GetDeploymentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentStatus not implemented")
}
func (*UnimplementedFUOTAServerServiceServer) GetDeploymentDeviceLogs(context.Context, *GetDeploymentDeviceLogsRequest) (*GetDeploymentDeviceLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeploymentDeviceLogs not implemented")
}

func RegisterFUOTAServerServiceServer(s *grpc.Server, srv FUOTAServerServiceServer) {
	s.RegisterService(&_FUOTAServerService_serviceDesc, srv)
}

func _FUOTAServerService_CreateDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeploymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTAServerServiceServer).CreateDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuota_v3.FUOTAServerService/CreateDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTAServerServiceServer).CreateDeployment(ctx, req.(*CreateDeploymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTAServerService_GetDeploymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTAServerServiceServer).GetDeploymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuota_v3.FUOTAServerService/GetDeploymentStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTAServerServiceServer).GetDeploymentStatus(ctx, req.(*GetDeploymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FUOTAServerService_GetDeploymentDeviceLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentDeviceLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FUOTAServerServiceServer).GetDeploymentDeviceLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuota_v3.FUOTAServerService/GetDeploymentDeviceLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FUOTAServerServiceServer).GetDeploymentDeviceLogs(ctx, req.(*GetDeploymentDeviceLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FUOTAServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fuota_v3.FUOTAServerService",
	HandlerType: (*FUOTAServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeployment",
			Handler:    _FUOTAServerService_CreateDeployment_Handler,
		},
		{
			MethodName: "GetDeploymentStatus",
			Handler:    _FUOTAServerService_GetDeploymentStatus_Handler,
		},
		{
			MethodName: "GetDeploymentDeviceLogs",
			Handler:    _FUOTAServerService_GetDeploymentDeviceLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fuota/fuota_v3.proto",
}
