// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: gw/gw_v3.proto

package gw

import (
	common "github.com/brocaar/chirpstack-api/go/v3/common"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownlinkTiming int32

const (
	// Send the downlink immediately.
	DownlinkTiming_IMMEDIATELY DownlinkTiming = 0
	// Send downlink at the given delay (based on provided context).
	DownlinkTiming_DELAY DownlinkTiming = 1
	// Send at given GPS epoch value.
	DownlinkTiming_GPS_EPOCH DownlinkTiming = 2
)

// Enum value maps for DownlinkTiming.
var (
	DownlinkTiming_name = map[int32]string{
		0: "IMMEDIATELY",
		1: "DELAY",
		2: "GPS_EPOCH",
	}
	DownlinkTiming_value = map[string]int32{
		"IMMEDIATELY": 0,
		"DELAY":       1,
		"GPS_EPOCH":   2,
	}
)

func (x DownlinkTiming) Enum() *DownlinkTiming {
	p := new(DownlinkTiming)
	*p = x
	return p
}

func (x DownlinkTiming) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DownlinkTiming) Descriptor() protoreflect.EnumDescriptor {
	return file_gw_gw_v3_proto_enumTypes[0].Descriptor()
}

func (DownlinkTiming) Type() protoreflect.EnumType {
	return &file_gw_gw_v3_proto_enumTypes[0]
}

func (x DownlinkTiming) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DownlinkTiming.Descriptor instead.
func (DownlinkTiming) EnumDescriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{0}
}

type FineTimestampType int32

const (
	// No fine-timestamp available.
	FineTimestampType_NONE FineTimestampType = 0
	// Encrypted fine-timestamp.
	FineTimestampType_ENCRYPTED FineTimestampType = 1
	// Plain fine-timestamp.
	FineTimestampType_PLAIN FineTimestampType = 2
)

// Enum value maps for FineTimestampType.
var (
	FineTimestampType_name = map[int32]string{
		0: "NONE",
		1: "ENCRYPTED",
		2: "PLAIN",
	}
	FineTimestampType_value = map[string]int32{
		"NONE":      0,
		"ENCRYPTED": 1,
		"PLAIN":     2,
	}
)

func (x FineTimestampType) Enum() *FineTimestampType {
	p := new(FineTimestampType)
	*p = x
	return p
}

func (x FineTimestampType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FineTimestampType) Descriptor() protoreflect.EnumDescriptor {
	return file_gw_gw_v3_proto_enumTypes[1].Descriptor()
}

func (FineTimestampType) Type() protoreflect.EnumType {
	return &file_gw_gw_v3_proto_enumTypes[1]
}

func (x FineTimestampType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FineTimestampType.Descriptor instead.
func (FineTimestampType) EnumDescriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{1}
}

type CRCStatus int32

const (
	// No CRC.
	CRCStatus_NO_CRC CRCStatus = 0
	// Bad CRC.
	CRCStatus_BAD_CRC CRCStatus = 1
	// CRC OK.
	CRCStatus_CRC_OK CRCStatus = 2
)

// Enum value maps for CRCStatus.
var (
	CRCStatus_name = map[int32]string{
		0: "NO_CRC",
		1: "BAD_CRC",
		2: "CRC_OK",
	}
	CRCStatus_value = map[string]int32{
		"NO_CRC":  0,
		"BAD_CRC": 1,
		"CRC_OK":  2,
	}
)

func (x CRCStatus) Enum() *CRCStatus {
	p := new(CRCStatus)
	*p = x
	return p
}

func (x CRCStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CRCStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gw_gw_v3_proto_enumTypes[2].Descriptor()
}

func (CRCStatus) Type() protoreflect.EnumType {
	return &file_gw_gw_v3_proto_enumTypes[2]
}

func (x CRCStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CRCStatus.Descriptor instead.
func (CRCStatus) EnumDescriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{2}
}

type TxAckStatus int32

const (
	// Ignored (when a previous item was already emitted).
	TxAckStatus_IGNORED TxAckStatus = 0
	// Packet has been programmed for downlink.
	TxAckStatus_OK TxAckStatus = 1
	// Rejected because it was already too late to program this packet for downlink.
	TxAckStatus_TOO_LATE TxAckStatus = 2
	// Rejected because downlink packet timestamp is too much in advance.
	TxAckStatus_TOO_EARLY TxAckStatus = 3
	// Rejected because there was already a packet programmed in requested timeframe.
	TxAckStatus_COLLISION_PACKET TxAckStatus = 4
	// Rejected because there was already a beacon planned in requested timeframe.
	TxAckStatus_COLLISION_BEACON TxAckStatus = 5
	// Rejected because requested frequency is not supported by TX RF chain.
	TxAckStatus_TX_FREQ TxAckStatus = 6
	// Rejected because requested power is not supported by gateway.
	TxAckStatus_TX_POWER TxAckStatus = 7
	// Rejected because GPS is unlocked, so GPS timestamp cannot be used.
	TxAckStatus_GPS_UNLOCKED TxAckStatus = 8
	// Downlink queue is full.
	TxAckStatus_QUEUE_FULL TxAckStatus = 9
	// Internal error.
	TxAckStatus_INTERNAL_ERROR TxAckStatus = 10
)

// Enum value maps for TxAckStatus.
var (
	TxAckStatus_name = map[int32]string{
		0:  "IGNORED",
		1:  "OK",
		2:  "TOO_LATE",
		3:  "TOO_EARLY",
		4:  "COLLISION_PACKET",
		5:  "COLLISION_BEACON",
		6:  "TX_FREQ",
		7:  "TX_POWER",
		8:  "GPS_UNLOCKED",
		9:  "QUEUE_FULL",
		10: "INTERNAL_ERROR",
	}
	TxAckStatus_value = map[string]int32{
		"IGNORED":          0,
		"OK":               1,
		"TOO_LATE":         2,
		"TOO_EARLY":        3,
		"COLLISION_PACKET": 4,
		"COLLISION_BEACON": 5,
		"TX_FREQ":          6,
		"TX_POWER":         7,
		"GPS_UNLOCKED":     8,
		"QUEUE_FULL":       9,
		"INTERNAL_ERROR":   10,
	}
)

func (x TxAckStatus) Enum() *TxAckStatus {
	p := new(TxAckStatus)
	*p = x
	return p
}

func (x TxAckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxAckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gw_gw_v3_proto_enumTypes[3].Descriptor()
}

func (TxAckStatus) Type() protoreflect.EnumType {
	return &file_gw_gw_v3_proto_enumTypes[3]
}

func (x TxAckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxAckStatus.Descriptor instead.
func (TxAckStatus) EnumDescriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{3}
}

type ConnState_State int32

const (
	ConnState_OFFLINE ConnState_State = 0
	ConnState_ONLINE  ConnState_State = 1
)

// Enum value maps for ConnState_State.
var (
	ConnState_State_name = map[int32]string{
		0: "OFFLINE",
		1: "ONLINE",
	}
	ConnState_State_value = map[string]int32{
		"OFFLINE": 0,
		"ONLINE":  1,
	}
)

func (x ConnState_State) Enum() *ConnState_State {
	p := new(ConnState_State)
	*p = x
	return p
}

func (x ConnState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_gw_gw_v3_proto_enumTypes[4].Descriptor()
}

func (ConnState_State) Type() protoreflect.EnumType {
	return &file_gw_gw_v3_proto_enumTypes[4]
}

func (x ConnState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnState_State.Descriptor instead.
func (ConnState_State) EnumDescriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{28, 0}
}

type Modulation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Parameters:
	//
	//	*Modulation_Lora
	//	*Modulation_Fsk
	//	*Modulation_LrFhss
	Parameters    isModulation_Parameters `protobuf_oneof:"parameters"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Modulation) Reset() {
	*x = Modulation{}
	mi := &file_gw_gw_v3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Modulation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Modulation) ProtoMessage() {}

func (x *Modulation) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Modulation.ProtoReflect.Descriptor instead.
func (*Modulation) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{0}
}

func (x *Modulation) GetParameters() isModulation_Parameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Modulation) GetLora() *LoRaModulationInfo {
	if x != nil {
		if x, ok := x.Parameters.(*Modulation_Lora); ok {
			return x.Lora
		}
	}
	return nil
}

func (x *Modulation) GetFsk() *FSKModulationInfo {
	if x != nil {
		if x, ok := x.Parameters.(*Modulation_Fsk); ok {
			return x.Fsk
		}
	}
	return nil
}

func (x *Modulation) GetLrFhss() *LRFHSSModulationInfo {
	if x != nil {
		if x, ok := x.Parameters.(*Modulation_LrFhss); ok {
			return x.LrFhss
		}
	}
	return nil
}

type isModulation_Parameters interface {
	isModulation_Parameters()
}

type Modulation_Lora struct {
	// LoRa modulation information.
	Lora *LoRaModulationInfo `protobuf:"bytes,3,opt,name=lora,json=loRa,proto3,oneof"`
}

type Modulation_Fsk struct {
	// FSK modulation information.
	Fsk *FSKModulationInfo `protobuf:"bytes,4,opt,name=fsk,proto3,oneof"`
}

type Modulation_LrFhss struct {
	// LR-FHSS modulation information.
	LrFhss *LRFHSSModulationInfo `protobuf:"bytes,5,opt,name=lr_fhss,json=lrFHSS,proto3,oneof"`
}

func (*Modulation_Lora) isModulation_Parameters() {}

func (*Modulation_Fsk) isModulation_Parameters() {}

func (*Modulation_LrFhss) isModulation_Parameters() {}

type UplinkTXInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Frequency (Hz).
	Frequency uint32 `protobuf:"varint,1,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// Modulation.
	Modulation common.Modulation `protobuf:"varint,2,opt,name=modulation,proto3,enum=common_v3.Modulation" json:"modulation,omitempty"`
	// Types that are valid to be assigned to ModulationInfo:
	//
	//	*UplinkTXInfo_LoraModulationInfo
	//	*UplinkTXInfo_FskModulationInfo
	//	*UplinkTXInfo_LrFhssModulationInfo
	ModulationInfo isUplinkTXInfo_ModulationInfo `protobuf_oneof:"modulation_info"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UplinkTXInfo) Reset() {
	*x = UplinkTXInfo{}
	mi := &file_gw_gw_v3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UplinkTXInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UplinkTXInfo) ProtoMessage() {}

func (x *UplinkTXInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UplinkTXInfo.ProtoReflect.Descriptor instead.
func (*UplinkTXInfo) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{1}
}

func (x *UplinkTXInfo) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *UplinkTXInfo) GetModulation() common.Modulation {
	if x != nil {
		return x.Modulation
	}
	return common.Modulation(0)
}

func (x *UplinkTXInfo) GetModulationInfo() isUplinkTXInfo_ModulationInfo {
	if x != nil {
		return x.ModulationInfo
	}
	return nil
}

func (x *UplinkTXInfo) GetLoraModulationInfo() *LoRaModulationInfo {
	if x != nil {
		if x, ok := x.ModulationInfo.(*UplinkTXInfo_LoraModulationInfo); ok {
			return x.LoraModulationInfo
		}
	}
	return nil
}

func (x *UplinkTXInfo) GetFskModulationInfo() *FSKModulationInfo {
	if x != nil {
		if x, ok := x.ModulationInfo.(*UplinkTXInfo_FskModulationInfo); ok {
			return x.FskModulationInfo
		}
	}
	return nil
}

func (x *UplinkTXInfo) GetLrFhssModulationInfo() *LRFHSSModulationInfo {
	if x != nil {
		if x, ok := x.ModulationInfo.(*UplinkTXInfo_LrFhssModulationInfo); ok {
			return x.LrFhssModulationInfo
		}
	}
	return nil
}

type isUplinkTXInfo_ModulationInfo interface {
	isUplinkTXInfo_ModulationInfo()
}

type UplinkTXInfo_LoraModulationInfo struct {
	// LoRa modulation information.
	LoraModulationInfo *LoRaModulationInfo `protobuf:"bytes,3,opt,name=lora_modulation_info,json=loRaModulationInfo,proto3,oneof"`
}

type UplinkTXInfo_FskModulationInfo struct {
	// FSK modulation information.
	FskModulationInfo *FSKModulationInfo `protobuf:"bytes,4,opt,name=fsk_modulation_info,json=fskModulationInfo,proto3,oneof"`
}

type UplinkTXInfo_LrFhssModulationInfo struct {
	// LR-FHSS modulation information.
	LrFhssModulationInfo *LRFHSSModulationInfo `protobuf:"bytes,5,opt,name=lr_fhss_modulation_info,json=lrFHSSModulationInfo,proto3,oneof"`
}

func (*UplinkTXInfo_LoraModulationInfo) isUplinkTXInfo_ModulationInfo() {}

func (*UplinkTXInfo_FskModulationInfo) isUplinkTXInfo_ModulationInfo() {}

func (*UplinkTXInfo_LrFhssModulationInfo) isUplinkTXInfo_ModulationInfo() {}

type LoRaModulationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bandwidth.
	Bandwidth uint32 `protobuf:"varint,1,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	// Speading-factor.
	SpreadingFactor uint32 `protobuf:"varint,2,opt,name=spreading_factor,json=spreadingFactor,proto3" json:"spreading_factor,omitempty"`
	// Code-rate.
	CodeRate string `protobuf:"bytes,3,opt,name=code_rate,json=codeRate,proto3" json:"code_rate,omitempty"`
	// Polarization inversion.
	PolarizationInversion bool `protobuf:"varint,4,opt,name=polarization_inversion,json=polarizationInversion,proto3" json:"polarization_inversion,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LoRaModulationInfo) Reset() {
	*x = LoRaModulationInfo{}
	mi := &file_gw_gw_v3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoRaModulationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoRaModulationInfo) ProtoMessage() {}

func (x *LoRaModulationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoRaModulationInfo.ProtoReflect.Descriptor instead.
func (*LoRaModulationInfo) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{2}
}

func (x *LoRaModulationInfo) GetBandwidth() uint32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *LoRaModulationInfo) GetSpreadingFactor() uint32 {
	if x != nil {
		return x.SpreadingFactor
	}
	return 0
}

func (x *LoRaModulationInfo) GetCodeRate() string {
	if x != nil {
		return x.CodeRate
	}
	return ""
}

func (x *LoRaModulationInfo) GetPolarizationInversion() bool {
	if x != nil {
		return x.PolarizationInversion
	}
	return false
}

type FSKModulationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Frequency deviation.
	FrequencyDeviation uint32 `protobuf:"varint,1,opt,name=frequency_deviation,json=frequencyDeviation,proto3" json:"frequency_deviation,omitempty"`
	// FSK datarate (bits / sec).
	Datarate      uint32 `protobuf:"varint,2,opt,name=datarate,proto3" json:"datarate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSKModulationInfo) Reset() {
	*x = FSKModulationInfo{}
	mi := &file_gw_gw_v3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSKModulationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSKModulationInfo) ProtoMessage() {}

func (x *FSKModulationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSKModulationInfo.ProtoReflect.Descriptor instead.
func (*FSKModulationInfo) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{3}
}

func (x *FSKModulationInfo) GetFrequencyDeviation() uint32 {
	if x != nil {
		return x.FrequencyDeviation
	}
	return 0
}

func (x *FSKModulationInfo) GetDatarate() uint32 {
	if x != nil {
		return x.Datarate
	}
	return 0
}

type LRFHSSModulationInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operating channel width (OCW) in Hz.
	OperatingChannelWidth uint32 `protobuf:"varint,1,opt,name=operating_channel_width,json=operatingChannelWidth,proto3" json:"operating_channel_width,omitempty"`
	// Code-rate.
	CodeRate string `protobuf:"bytes,2,opt,name=code_rate,json=codeRate,proto3" json:"code_rate,omitempty"`
	// Hopping grid number of steps.
	GridSteps     uint32 `protobuf:"varint,3,opt,name=grid_steps,json=gridSteps,proto3" json:"grid_steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LRFHSSModulationInfo) Reset() {
	*x = LRFHSSModulationInfo{}
	mi := &file_gw_gw_v3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LRFHSSModulationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRFHSSModulationInfo) ProtoMessage() {}

func (x *LRFHSSModulationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRFHSSModulationInfo.ProtoReflect.Descriptor instead.
func (*LRFHSSModulationInfo) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{4}
}

func (x *LRFHSSModulationInfo) GetOperatingChannelWidth() uint32 {
	if x != nil {
		return x.OperatingChannelWidth
	}
	return 0
}

func (x *LRFHSSModulationInfo) GetCodeRate() string {
	if x != nil {
		return x.CodeRate
	}
	return ""
}

func (x *LRFHSSModulationInfo) GetGridSteps() uint32 {
	if x != nil {
		return x.GridSteps
	}
	return 0
}

type EncryptedFineTimestamp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AES key index used for encrypting the fine timestamp.
	AesKeyIndex uint32 `protobuf:"varint,1,opt,name=aes_key_index,json=aesKeyIndex,proto3" json:"aes_key_index,omitempty"`
	// Encrypted 'main' fine-timestamp (ns precision part of the timestamp).
	EncryptedNs []byte `protobuf:"bytes,2,opt,name=encrypted_ns,json=encryptedNS,proto3" json:"encrypted_ns,omitempty"`
	// FPGA ID.
	FpgaId        []byte `protobuf:"bytes,3,opt,name=fpga_id,json=fpgaID,proto3" json:"fpga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedFineTimestamp) Reset() {
	*x = EncryptedFineTimestamp{}
	mi := &file_gw_gw_v3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedFineTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedFineTimestamp) ProtoMessage() {}

func (x *EncryptedFineTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedFineTimestamp.ProtoReflect.Descriptor instead.
func (*EncryptedFineTimestamp) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{5}
}

func (x *EncryptedFineTimestamp) GetAesKeyIndex() uint32 {
	if x != nil {
		return x.AesKeyIndex
	}
	return 0
}

func (x *EncryptedFineTimestamp) GetEncryptedNs() []byte {
	if x != nil {
		return x.EncryptedNs
	}
	return nil
}

func (x *EncryptedFineTimestamp) GetFpgaId() []byte {
	if x != nil {
		return x.FpgaId
	}
	return nil
}

type PlainFineTimestamp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full timestamp.
	Time          *timestamp.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlainFineTimestamp) Reset() {
	*x = PlainFineTimestamp{}
	mi := &file_gw_gw_v3_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlainFineTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlainFineTimestamp) ProtoMessage() {}

func (x *PlainFineTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlainFineTimestamp.ProtoReflect.Descriptor instead.
func (*PlainFineTimestamp) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{6}
}

func (x *PlainFineTimestamp) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type GatewayStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// Gateway IP.
	Ip string `protobuf:"bytes,9,opt,name=ip,proto3" json:"ip,omitempty"`
	// Gateway time.
	Time *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	// Gateway location.
	Location *common.Location `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// Gateway configuration version (this maps to the config_version sent
	// by LoRa Server to the gateway).
	ConfigVersion string `protobuf:"bytes,4,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// Number of radio packets received.
	RxPacketsReceived uint32 `protobuf:"varint,5,opt,name=rx_packets_received,json=rxPacketsReceived,proto3" json:"rx_packets_received,omitempty"`
	// Number of radio packets received with valid PHY CRC.
	RxPacketsReceivedOk uint32 `protobuf:"varint,6,opt,name=rx_packets_received_ok,json=rxPacketsReceivedOK,proto3" json:"rx_packets_received_ok,omitempty"`
	// Number of downlink packets received for transmission.
	TxPacketsReceived uint32 `protobuf:"varint,7,opt,name=tx_packets_received,json=txPacketsReceived,proto3" json:"tx_packets_received,omitempty"`
	// Number of downlink packets emitted.
	TxPacketsEmitted uint32 `protobuf:"varint,8,opt,name=tx_packets_emitted,json=txPacketsEmitted,proto3" json:"tx_packets_emitted,omitempty"`
	// Additional gateway meta-data.
	MetaData map[string]string `protobuf:"bytes,10,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Stats ID (UUID).
	// Unique identifier for the gateway stats.
	StatsId []byte `protobuf:"bytes,11,opt,name=stats_id,json=statsID,proto3" json:"stats_id,omitempty"`
	// Tx packets per frequency.
	TxPacketsPerFrequency map[uint32]uint32 `protobuf:"bytes,12,rep,name=tx_packets_per_frequency,json=txPacketsPerFrequency,proto3" json:"tx_packets_per_frequency,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Rx packets per frequency.
	RxPacketsPerFrequency map[uint32]uint32 `protobuf:"bytes,13,rep,name=rx_packets_per_frequency,json=rxPacketsPerFrequency,proto3" json:"rx_packets_per_frequency,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Tx packets per modulation parameters.
	TxPacketsPerModulation []*PerModulationCount `protobuf:"bytes,14,rep,name=tx_packets_per_modulation,json=txPacketsPerModulation,proto3" json:"tx_packets_per_modulation,omitempty"`
	// Rx packets per modulation parameters.
	RxPacketsPerModulation []*PerModulationCount `protobuf:"bytes,15,rep,name=rx_packets_per_modulation,json=rxPacketsPerModulation,proto3" json:"rx_packets_per_modulation,omitempty"`
	// Tx packets per status.
	TxPacketsPerStatus map[string]uint32 `protobuf:"bytes,16,rep,name=tx_packets_per_status,json=txPacketsPerStatus,proto3" json:"tx_packets_per_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GatewayStats) Reset() {
	*x = GatewayStats{}
	mi := &file_gw_gw_v3_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayStats) ProtoMessage() {}

func (x *GatewayStats) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayStats.ProtoReflect.Descriptor instead.
func (*GatewayStats) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{7}
}

func (x *GatewayStats) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *GatewayStats) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GatewayStats) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *GatewayStats) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *GatewayStats) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *GatewayStats) GetRxPacketsReceived() uint32 {
	if x != nil {
		return x.RxPacketsReceived
	}
	return 0
}

func (x *GatewayStats) GetRxPacketsReceivedOk() uint32 {
	if x != nil {
		return x.RxPacketsReceivedOk
	}
	return 0
}

func (x *GatewayStats) GetTxPacketsReceived() uint32 {
	if x != nil {
		return x.TxPacketsReceived
	}
	return 0
}

func (x *GatewayStats) GetTxPacketsEmitted() uint32 {
	if x != nil {
		return x.TxPacketsEmitted
	}
	return 0
}

func (x *GatewayStats) GetMetaData() map[string]string {
	if x != nil {
		return x.MetaData
	}
	return nil
}

func (x *GatewayStats) GetStatsId() []byte {
	if x != nil {
		return x.StatsId
	}
	return nil
}

func (x *GatewayStats) GetTxPacketsPerFrequency() map[uint32]uint32 {
	if x != nil {
		return x.TxPacketsPerFrequency
	}
	return nil
}

func (x *GatewayStats) GetRxPacketsPerFrequency() map[uint32]uint32 {
	if x != nil {
		return x.RxPacketsPerFrequency
	}
	return nil
}

func (x *GatewayStats) GetTxPacketsPerModulation() []*PerModulationCount {
	if x != nil {
		return x.TxPacketsPerModulation
	}
	return nil
}

func (x *GatewayStats) GetRxPacketsPerModulation() []*PerModulationCount {
	if x != nil {
		return x.RxPacketsPerModulation
	}
	return nil
}

func (x *GatewayStats) GetTxPacketsPerStatus() map[string]uint32 {
	if x != nil {
		return x.TxPacketsPerStatus
	}
	return nil
}

type PerModulationCount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Modulation.
	Modulation *Modulation `protobuf:"bytes,1,opt,name=modulation,proto3" json:"modulation,omitempty"`
	// Count.
	Count         uint32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerModulationCount) Reset() {
	*x = PerModulationCount{}
	mi := &file_gw_gw_v3_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerModulationCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerModulationCount) ProtoMessage() {}

func (x *PerModulationCount) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerModulationCount.ProtoReflect.Descriptor instead.
func (*PerModulationCount) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{8}
}

func (x *PerModulationCount) GetModulation() *Modulation {
	if x != nil {
		return x.Modulation
	}
	return nil
}

func (x *PerModulationCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UplinkRXInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// RX time (only set when the gateway has a GPS module).
	Time *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	// RX time since GPS epoch (only set when the gateway has a GPS module).
	TimeSinceGpsEpoch *duration.Duration `protobuf:"bytes,3,opt,name=time_since_gps_epoch,json=timeSinceGPSEpoch,proto3" json:"time_since_gps_epoch,omitempty"`
	// RSSI.
	Rssi int32 `protobuf:"varint,5,opt,name=rssi,proto3" json:"rssi,omitempty"`
	// LoRa SNR.
	LoraSnr float64 `protobuf:"fixed64,6,opt,name=lora_snr,json=loRaSNR,proto3" json:"lora_snr,omitempty"`
	// Channel.
	Channel uint32 `protobuf:"varint,7,opt,name=channel,proto3" json:"channel,omitempty"`
	// RF Chain.
	RfChain uint32 `protobuf:"varint,8,opt,name=rf_chain,json=rfChain,proto3" json:"rf_chain,omitempty"`
	// Board.
	Board uint32 `protobuf:"varint,9,opt,name=board,proto3" json:"board,omitempty"`
	// Antenna.
	Antenna uint32 `protobuf:"varint,10,opt,name=antenna,proto3" json:"antenna,omitempty"`
	// Location.
	Location *common.Location `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`
	// Fine-timestamp type.
	FineTimestampType FineTimestampType `protobuf:"varint,12,opt,name=fine_timestamp_type,json=fineTimestampType,proto3,enum=gw_v3.FineTimestampType" json:"fine_timestamp_type,omitempty"`
	// Fine-timestamp data.
	//
	// Types that are valid to be assigned to FineTimestamp:
	//
	//	*UplinkRXInfo_EncryptedFineTimestamp
	//	*UplinkRXInfo_PlainFineTimestamp
	FineTimestamp isUplinkRXInfo_FineTimestamp `protobuf_oneof:"fine_timestamp"`
	// Gateway specific context.
	Context []byte `protobuf:"bytes,15,opt,name=context,proto3" json:"context,omitempty"`
	// Uplink ID (UUID bytes).
	// Unique and random ID which can be used to correlate the uplink across multiple logs.
	UplinkId []byte `protobuf:"bytes,16,opt,name=uplink_id,json=uplinkID,proto3" json:"uplink_id,omitempty"`
	// CRC status.
	CrcStatus     CRCStatus `protobuf:"varint,17,opt,name=crc_status,json=crcStatus,proto3,enum=gw_v3.CRCStatus" json:"crc_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UplinkRXInfo) Reset() {
	*x = UplinkRXInfo{}
	mi := &file_gw_gw_v3_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UplinkRXInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UplinkRXInfo) ProtoMessage() {}

func (x *UplinkRXInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UplinkRXInfo.ProtoReflect.Descriptor instead.
func (*UplinkRXInfo) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{9}
}

func (x *UplinkRXInfo) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *UplinkRXInfo) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *UplinkRXInfo) GetTimeSinceGpsEpoch() *duration.Duration {
	if x != nil {
		return x.TimeSinceGpsEpoch
	}
	return nil
}

func (x *UplinkRXInfo) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *UplinkRXInfo) GetLoraSnr() float64 {
	if x != nil {
		return x.LoraSnr
	}
	return 0
}

func (x *UplinkRXInfo) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *UplinkRXInfo) GetRfChain() uint32 {
	if x != nil {
		return x.RfChain
	}
	return 0
}

func (x *UplinkRXInfo) GetBoard() uint32 {
	if x != nil {
		return x.Board
	}
	return 0
}

func (x *UplinkRXInfo) GetAntenna() uint32 {
	if x != nil {
		return x.Antenna
	}
	return 0
}

func (x *UplinkRXInfo) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *UplinkRXInfo) GetFineTimestampType() FineTimestampType {
	if x != nil {
		return x.FineTimestampType
	}
	return FineTimestampType_NONE
}

func (x *UplinkRXInfo) GetFineTimestamp() isUplinkRXInfo_FineTimestamp {
	if x != nil {
		return x.FineTimestamp
	}
	return nil
}

func (x *UplinkRXInfo) GetEncryptedFineTimestamp() *EncryptedFineTimestamp {
	if x != nil {
		if x, ok := x.FineTimestamp.(*UplinkRXInfo_EncryptedFineTimestamp); ok {
			return x.EncryptedFineTimestamp
		}
	}
	return nil
}

func (x *UplinkRXInfo) GetPlainFineTimestamp() *PlainFineTimestamp {
	if x != nil {
		if x, ok := x.FineTimestamp.(*UplinkRXInfo_PlainFineTimestamp); ok {
			return x.PlainFineTimestamp
		}
	}
	return nil
}

func (x *UplinkRXInfo) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UplinkRXInfo) GetUplinkId() []byte {
	if x != nil {
		return x.UplinkId
	}
	return nil
}

func (x *UplinkRXInfo) GetCrcStatus() CRCStatus {
	if x != nil {
		return x.CrcStatus
	}
	return CRCStatus_NO_CRC
}

type isUplinkRXInfo_FineTimestamp interface {
	isUplinkRXInfo_FineTimestamp()
}

type UplinkRXInfo_EncryptedFineTimestamp struct {
	// Encrypted fine-timestamp data.
	EncryptedFineTimestamp *EncryptedFineTimestamp `protobuf:"bytes,13,opt,name=encrypted_fine_timestamp,json=encryptedFineTimestamp,proto3,oneof"`
}

type UplinkRXInfo_PlainFineTimestamp struct {
	// Plain fine-timestamp data.
	PlainFineTimestamp *PlainFineTimestamp `protobuf:"bytes,14,opt,name=plain_fine_timestamp,json=plainFineTimestamp,proto3,oneof"`
}

func (*UplinkRXInfo_EncryptedFineTimestamp) isUplinkRXInfo_FineTimestamp() {}

func (*UplinkRXInfo_PlainFineTimestamp) isUplinkRXInfo_FineTimestamp() {}

type DownlinkTXInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID.
	// Deprecated: replaced by gateway_id in DownlinkFrame.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// TX frequency (in Hz).
	Frequency uint32 `protobuf:"varint,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// TX power (in dBm).
	Power int32 `protobuf:"varint,6,opt,name=power,proto3" json:"power,omitempty"`
	// Modulation.
	Modulation common.Modulation `protobuf:"varint,7,opt,name=modulation,proto3,enum=common_v3.Modulation" json:"modulation,omitempty"`
	// Types that are valid to be assigned to ModulationInfo:
	//
	//	*DownlinkTXInfo_LoraModulationInfo
	//	*DownlinkTXInfo_FskModulationInfo
	ModulationInfo isDownlinkTXInfo_ModulationInfo `protobuf_oneof:"modulation_info"`
	// The board identifier for emitting the frame.
	Board uint32 `protobuf:"varint,10,opt,name=board,proto3" json:"board,omitempty"`
	// The antenna identifier for emitting the frame.
	Antenna uint32 `protobuf:"varint,11,opt,name=antenna,proto3" json:"antenna,omitempty"`
	// Timing defines the downlink timing to use.
	Timing DownlinkTiming `protobuf:"varint,12,opt,name=timing,proto3,enum=gw_v3.DownlinkTiming" json:"timing,omitempty"`
	// Types that are valid to be assigned to TimingInfo:
	//
	//	*DownlinkTXInfo_ImmediatelyTimingInfo
	//	*DownlinkTXInfo_DelayTimingInfo
	//	*DownlinkTXInfo_GpsEpochTimingInfo
	TimingInfo isDownlinkTXInfo_TimingInfo `protobuf_oneof:"timing_info"`
	// Gateway specific context.
	// In case of a Class-A downlink, this contains a copy of the uplink context.
	Context       []byte `protobuf:"bytes,16,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkTXInfo) Reset() {
	*x = DownlinkTXInfo{}
	mi := &file_gw_gw_v3_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkTXInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkTXInfo) ProtoMessage() {}

func (x *DownlinkTXInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkTXInfo.ProtoReflect.Descriptor instead.
func (*DownlinkTXInfo) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{10}
}

func (x *DownlinkTXInfo) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *DownlinkTXInfo) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *DownlinkTXInfo) GetPower() int32 {
	if x != nil {
		return x.Power
	}
	return 0
}

func (x *DownlinkTXInfo) GetModulation() common.Modulation {
	if x != nil {
		return x.Modulation
	}
	return common.Modulation(0)
}

func (x *DownlinkTXInfo) GetModulationInfo() isDownlinkTXInfo_ModulationInfo {
	if x != nil {
		return x.ModulationInfo
	}
	return nil
}

func (x *DownlinkTXInfo) GetLoraModulationInfo() *LoRaModulationInfo {
	if x != nil {
		if x, ok := x.ModulationInfo.(*DownlinkTXInfo_LoraModulationInfo); ok {
			return x.LoraModulationInfo
		}
	}
	return nil
}

func (x *DownlinkTXInfo) GetFskModulationInfo() *FSKModulationInfo {
	if x != nil {
		if x, ok := x.ModulationInfo.(*DownlinkTXInfo_FskModulationInfo); ok {
			return x.FskModulationInfo
		}
	}
	return nil
}

func (x *DownlinkTXInfo) GetBoard() uint32 {
	if x != nil {
		return x.Board
	}
	return 0
}

func (x *DownlinkTXInfo) GetAntenna() uint32 {
	if x != nil {
		return x.Antenna
	}
	return 0
}

func (x *DownlinkTXInfo) GetTiming() DownlinkTiming {
	if x != nil {
		return x.Timing
	}
	return DownlinkTiming_IMMEDIATELY
}

func (x *DownlinkTXInfo) GetTimingInfo() isDownlinkTXInfo_TimingInfo {
	if x != nil {
		return x.TimingInfo
	}
	return nil
}

func (x *DownlinkTXInfo) GetImmediatelyTimingInfo() *ImmediatelyTimingInfo {
	if x != nil {
		if x, ok := x.TimingInfo.(*DownlinkTXInfo_ImmediatelyTimingInfo); ok {
			return x.ImmediatelyTimingInfo
		}
	}
	return nil
}

func (x *DownlinkTXInfo) GetDelayTimingInfo() *DelayTimingInfo {
	if x != nil {
		if x, ok := x.TimingInfo.(*DownlinkTXInfo_DelayTimingInfo); ok {
			return x.DelayTimingInfo
		}
	}
	return nil
}

func (x *DownlinkTXInfo) GetGpsEpochTimingInfo() *GPSEpochTimingInfo {
	if x != nil {
		if x, ok := x.TimingInfo.(*DownlinkTXInfo_GpsEpochTimingInfo); ok {
			return x.GpsEpochTimingInfo
		}
	}
	return nil
}

func (x *DownlinkTXInfo) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

type isDownlinkTXInfo_ModulationInfo interface {
	isDownlinkTXInfo_ModulationInfo()
}

type DownlinkTXInfo_LoraModulationInfo struct {
	// LoRa modulation information.
	LoraModulationInfo *LoRaModulationInfo `protobuf:"bytes,8,opt,name=lora_modulation_info,json=loRaModulationInfo,proto3,oneof"`
}

type DownlinkTXInfo_FskModulationInfo struct {
	// FSK modulation information.
	FskModulationInfo *FSKModulationInfo `protobuf:"bytes,9,opt,name=fsk_modulation_info,json=fskModulationInfo,proto3,oneof"`
}

func (*DownlinkTXInfo_LoraModulationInfo) isDownlinkTXInfo_ModulationInfo() {}

func (*DownlinkTXInfo_FskModulationInfo) isDownlinkTXInfo_ModulationInfo() {}

type isDownlinkTXInfo_TimingInfo interface {
	isDownlinkTXInfo_TimingInfo()
}

type DownlinkTXInfo_ImmediatelyTimingInfo struct {
	// Immediately timing information.
	ImmediatelyTimingInfo *ImmediatelyTimingInfo `protobuf:"bytes,13,opt,name=immediately_timing_info,json=immediatelyTimingInfo,proto3,oneof"`
}

type DownlinkTXInfo_DelayTimingInfo struct {
	// Context based delay timing information.
	DelayTimingInfo *DelayTimingInfo `protobuf:"bytes,14,opt,name=delay_timing_info,json=delayTimingInfo,proto3,oneof"`
}

type DownlinkTXInfo_GpsEpochTimingInfo struct {
	// GPS Epoch timing information.
	GpsEpochTimingInfo *GPSEpochTimingInfo `protobuf:"bytes,15,opt,name=gps_epoch_timing_info,json=gpsEpochTimingInfo,proto3,oneof"`
}

func (*DownlinkTXInfo_ImmediatelyTimingInfo) isDownlinkTXInfo_TimingInfo() {}

func (*DownlinkTXInfo_DelayTimingInfo) isDownlinkTXInfo_TimingInfo() {}

func (*DownlinkTXInfo_GpsEpochTimingInfo) isDownlinkTXInfo_TimingInfo() {}

type ImmediatelyTimingInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImmediatelyTimingInfo) Reset() {
	*x = ImmediatelyTimingInfo{}
	mi := &file_gw_gw_v3_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImmediatelyTimingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImmediatelyTimingInfo) ProtoMessage() {}

func (x *ImmediatelyTimingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImmediatelyTimingInfo.ProtoReflect.Descriptor instead.
func (*ImmediatelyTimingInfo) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{11}
}

type DelayTimingInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Delay (duration).
	// The delay will be added to the gateway internal timing, provided by the context object.
	Delay         *duration.Duration `protobuf:"bytes,1,opt,name=delay,proto3" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelayTimingInfo) Reset() {
	*x = DelayTimingInfo{}
	mi := &file_gw_gw_v3_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayTimingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayTimingInfo) ProtoMessage() {}

func (x *DelayTimingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayTimingInfo.ProtoReflect.Descriptor instead.
func (*DelayTimingInfo) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{12}
}

func (x *DelayTimingInfo) GetDelay() *duration.Duration {
	if x != nil {
		return x.Delay
	}
	return nil
}

type GPSEpochTimingInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Duration since GPS Epoch.
	TimeSinceGpsEpoch *duration.Duration `protobuf:"bytes,1,opt,name=time_since_gps_epoch,json=timeSinceGPSEpoch,proto3" json:"time_since_gps_epoch,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GPSEpochTimingInfo) Reset() {
	*x = GPSEpochTimingInfo{}
	mi := &file_gw_gw_v3_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPSEpochTimingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPSEpochTimingInfo) ProtoMessage() {}

func (x *GPSEpochTimingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPSEpochTimingInfo.ProtoReflect.Descriptor instead.
func (*GPSEpochTimingInfo) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{13}
}

func (x *GPSEpochTimingInfo) GetTimeSinceGpsEpoch() *duration.Duration {
	if x != nil {
		return x.TimeSinceGpsEpoch
	}
	return nil
}

type UplinkFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PHYPayload.
	PhyPayload []byte `protobuf:"bytes,1,opt,name=phy_payload,json=phyPayload,proto3" json:"phy_payload,omitempty"`
	// TX meta-data.
	TxInfo *UplinkTXInfo `protobuf:"bytes,2,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// RX meta-data.
	RxInfo        *UplinkRXInfo `protobuf:"bytes,3,opt,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UplinkFrame) Reset() {
	*x = UplinkFrame{}
	mi := &file_gw_gw_v3_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UplinkFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UplinkFrame) ProtoMessage() {}

func (x *UplinkFrame) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UplinkFrame.ProtoReflect.Descriptor instead.
func (*UplinkFrame) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{14}
}

func (x *UplinkFrame) GetPhyPayload() []byte {
	if x != nil {
		return x.PhyPayload
	}
	return nil
}

func (x *UplinkFrame) GetTxInfo() *UplinkTXInfo {
	if x != nil {
		return x.TxInfo
	}
	return nil
}

func (x *UplinkFrame) GetRxInfo() *UplinkRXInfo {
	if x != nil {
		return x.RxInfo
	}
	return nil
}

type UplinkFrameSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PHYPayload.
	PhyPayload []byte `protobuf:"bytes,1,opt,name=phy_payload,json=phyPayload,proto3" json:"phy_payload,omitempty"`
	// TX meta-data.
	TxInfo *UplinkTXInfo `protobuf:"bytes,2,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// RX meta-data set.
	RxInfo        []*UplinkRXInfo `protobuf:"bytes,3,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UplinkFrameSet) Reset() {
	*x = UplinkFrameSet{}
	mi := &file_gw_gw_v3_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UplinkFrameSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UplinkFrameSet) ProtoMessage() {}

func (x *UplinkFrameSet) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UplinkFrameSet.ProtoReflect.Descriptor instead.
func (*UplinkFrameSet) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{15}
}

func (x *UplinkFrameSet) GetPhyPayload() []byte {
	if x != nil {
		return x.PhyPayload
	}
	return nil
}

func (x *UplinkFrameSet) GetTxInfo() *UplinkTXInfo {
	if x != nil {
		return x.TxInfo
	}
	return nil
}

func (x *UplinkFrameSet) GetRxInfo() []*UplinkRXInfo {
	if x != nil {
		return x.RxInfo
	}
	return nil
}

type DownlinkFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PHYPayload.
	// Deprecated: replaced by items.
	PhyPayload []byte `protobuf:"bytes,1,opt,name=phy_payload,json=phyPayload,proto3" json:"phy_payload,omitempty"`
	// TX meta-data.
	// Deprecated: replaced by items.
	TxInfo *DownlinkTXInfo `protobuf:"bytes,2,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// Token (uint16 value).
	// Deprecated: replaced by downlink_id.
	Token uint32 `protobuf:"varint,3,opt,name=token,proto3" json:"token,omitempty"`
	// Downlink ID (UUID).
	DownlinkId []byte `protobuf:"bytes,4,opt,name=downlink_id,json=downlinkID,proto3" json:"downlink_id,omitempty"`
	// Downlink frame items.
	// This makes it possible to send multiple downlink opportunities to the
	// gateway at once (e.g. RX1 and RX2 in LoRaWAN). The first item has the
	// highest priority, the last the lowest. The gateway will emit at most
	// one item.
	Items []*DownlinkFrameItem `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	// Gateway ID.
	GatewayId     []byte `protobuf:"bytes,6,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkFrame) Reset() {
	*x = DownlinkFrame{}
	mi := &file_gw_gw_v3_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkFrame) ProtoMessage() {}

func (x *DownlinkFrame) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkFrame.ProtoReflect.Descriptor instead.
func (*DownlinkFrame) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{16}
}

func (x *DownlinkFrame) GetPhyPayload() []byte {
	if x != nil {
		return x.PhyPayload
	}
	return nil
}

func (x *DownlinkFrame) GetTxInfo() *DownlinkTXInfo {
	if x != nil {
		return x.TxInfo
	}
	return nil
}

func (x *DownlinkFrame) GetToken() uint32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *DownlinkFrame) GetDownlinkId() []byte {
	if x != nil {
		return x.DownlinkId
	}
	return nil
}

func (x *DownlinkFrame) GetItems() []*DownlinkFrameItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *DownlinkFrame) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

type DownlinkFrameItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PHYPayload.
	PhyPayload []byte `protobuf:"bytes,1,opt,name=phy_payload,json=phyPayload,proto3" json:"phy_payload,omitempty"`
	// TX meta-data.
	TxInfo        *DownlinkTXInfo `protobuf:"bytes,2,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkFrameItem) Reset() {
	*x = DownlinkFrameItem{}
	mi := &file_gw_gw_v3_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkFrameItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkFrameItem) ProtoMessage() {}

func (x *DownlinkFrameItem) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkFrameItem.ProtoReflect.Descriptor instead.
func (*DownlinkFrameItem) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{17}
}

func (x *DownlinkFrameItem) GetPhyPayload() []byte {
	if x != nil {
		return x.PhyPayload
	}
	return nil
}

func (x *DownlinkFrameItem) GetTxInfo() *DownlinkTXInfo {
	if x != nil {
		return x.TxInfo
	}
	return nil
}

type DownlinkTXAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// Token (uint16 value).
	// Deprecated: replaced by downlink_id.
	Token uint32 `protobuf:"varint,2,opt,name=token,proto3" json:"token,omitempty"`
	// Error.
	// Deprecated: replaced by items.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Downlink ID (UUID).
	DownlinkId []byte `protobuf:"bytes,4,opt,name=downlink_id,json=downlinkID,proto3" json:"downlink_id,omitempty"`
	// Downlink frame items.
	// This list has the same length as the request and indicates which
	// downlink frame has been emitted of the requested list (or why it failed).
	// Note that at most one item has a positive acknowledgement.
	Items         []*DownlinkTXAckItem `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkTXAck) Reset() {
	*x = DownlinkTXAck{}
	mi := &file_gw_gw_v3_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkTXAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkTXAck) ProtoMessage() {}

func (x *DownlinkTXAck) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkTXAck.ProtoReflect.Descriptor instead.
func (*DownlinkTXAck) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{18}
}

func (x *DownlinkTXAck) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *DownlinkTXAck) GetToken() uint32 {
	if x != nil {
		return x.Token
	}
	return 0
}

func (x *DownlinkTXAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DownlinkTXAck) GetDownlinkId() []byte {
	if x != nil {
		return x.DownlinkId
	}
	return nil
}

func (x *DownlinkTXAck) GetItems() []*DownlinkTXAckItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DownlinkTXAckItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Ack status of this item.
	Status        TxAckStatus `protobuf:"varint,1,opt,name=status,proto3,enum=gw_v3.TxAckStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownlinkTXAckItem) Reset() {
	*x = DownlinkTXAckItem{}
	mi := &file_gw_gw_v3_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownlinkTXAckItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownlinkTXAckItem) ProtoMessage() {}

func (x *DownlinkTXAckItem) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownlinkTXAckItem.ProtoReflect.Descriptor instead.
func (*DownlinkTXAckItem) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{19}
}

func (x *DownlinkTXAckItem) GetStatus() TxAckStatus {
	if x != nil {
		return x.Status
	}
	return TxAckStatus_IGNORED
}

type GatewayConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// Configuration version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Channels.
	Channels []*ChannelConfiguration `protobuf:"bytes,3,rep,name=channels,proto3" json:"channels,omitempty"`
	// Stats interval.
	StatsInterval *duration.Duration `protobuf:"bytes,4,opt,name=stats_interval,json=statsInterval,proto3" json:"stats_interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayConfiguration) Reset() {
	*x = GatewayConfiguration{}
	mi := &file_gw_gw_v3_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayConfiguration) ProtoMessage() {}

func (x *GatewayConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayConfiguration.ProtoReflect.Descriptor instead.
func (*GatewayConfiguration) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{20}
}

func (x *GatewayConfiguration) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *GatewayConfiguration) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GatewayConfiguration) GetChannels() []*ChannelConfiguration {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *GatewayConfiguration) GetStatsInterval() *duration.Duration {
	if x != nil {
		return x.StatsInterval
	}
	return nil
}

type ChannelConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Frequency (Hz).
	Frequency uint32 `protobuf:"varint,1,opt,name=frequency,proto3" json:"frequency,omitempty"`
	// Channel modulation.
	Modulation common.Modulation `protobuf:"varint,2,opt,name=modulation,proto3,enum=common_v3.Modulation" json:"modulation,omitempty"`
	// Types that are valid to be assigned to ModulationConfig:
	//
	//	*ChannelConfiguration_LoraModulationConfig
	//	*ChannelConfiguration_FskModulationConfig
	ModulationConfig isChannelConfiguration_ModulationConfig `protobuf_oneof:"modulation_config"`
	// Board index.
	Board uint32 `protobuf:"varint,5,opt,name=board,proto3" json:"board,omitempty"`
	// Demodulator index (of the given board).
	Demodulator   uint32 `protobuf:"varint,6,opt,name=demodulator,proto3" json:"demodulator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelConfiguration) Reset() {
	*x = ChannelConfiguration{}
	mi := &file_gw_gw_v3_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelConfiguration) ProtoMessage() {}

func (x *ChannelConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelConfiguration.ProtoReflect.Descriptor instead.
func (*ChannelConfiguration) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{21}
}

func (x *ChannelConfiguration) GetFrequency() uint32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *ChannelConfiguration) GetModulation() common.Modulation {
	if x != nil {
		return x.Modulation
	}
	return common.Modulation(0)
}

func (x *ChannelConfiguration) GetModulationConfig() isChannelConfiguration_ModulationConfig {
	if x != nil {
		return x.ModulationConfig
	}
	return nil
}

func (x *ChannelConfiguration) GetLoraModulationConfig() *LoRaModulationConfig {
	if x != nil {
		if x, ok := x.ModulationConfig.(*ChannelConfiguration_LoraModulationConfig); ok {
			return x.LoraModulationConfig
		}
	}
	return nil
}

func (x *ChannelConfiguration) GetFskModulationConfig() *FSKModulationConfig {
	if x != nil {
		if x, ok := x.ModulationConfig.(*ChannelConfiguration_FskModulationConfig); ok {
			return x.FskModulationConfig
		}
	}
	return nil
}

func (x *ChannelConfiguration) GetBoard() uint32 {
	if x != nil {
		return x.Board
	}
	return 0
}

func (x *ChannelConfiguration) GetDemodulator() uint32 {
	if x != nil {
		return x.Demodulator
	}
	return 0
}

type isChannelConfiguration_ModulationConfig interface {
	isChannelConfiguration_ModulationConfig()
}

type ChannelConfiguration_LoraModulationConfig struct {
	// LoRa modulation config.
	LoraModulationConfig *LoRaModulationConfig `protobuf:"bytes,3,opt,name=lora_modulation_config,json=loRaModulationConfig,proto3,oneof"`
}

type ChannelConfiguration_FskModulationConfig struct {
	// FSK modulation config.
	FskModulationConfig *FSKModulationConfig `protobuf:"bytes,4,opt,name=fsk_modulation_config,json=fskModulationConfig,proto3,oneof"`
}

func (*ChannelConfiguration_LoraModulationConfig) isChannelConfiguration_ModulationConfig() {}

func (*ChannelConfiguration_FskModulationConfig) isChannelConfiguration_ModulationConfig() {}

type LoRaModulationConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bandwidth.
	Bandwidth uint32 `protobuf:"varint,1,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	// Spreading-factors.
	SpreadingFactors []uint32 `protobuf:"varint,2,rep,packed,name=spreading_factors,json=spreadingFactors,proto3" json:"spreading_factors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoRaModulationConfig) Reset() {
	*x = LoRaModulationConfig{}
	mi := &file_gw_gw_v3_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoRaModulationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoRaModulationConfig) ProtoMessage() {}

func (x *LoRaModulationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoRaModulationConfig.ProtoReflect.Descriptor instead.
func (*LoRaModulationConfig) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{22}
}

func (x *LoRaModulationConfig) GetBandwidth() uint32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *LoRaModulationConfig) GetSpreadingFactors() []uint32 {
	if x != nil {
		return x.SpreadingFactors
	}
	return nil
}

type FSKModulationConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bandwidth.
	Bandwidth uint32 `protobuf:"varint,1,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	// Bitrate.
	Bitrate       uint32 `protobuf:"varint,2,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSKModulationConfig) Reset() {
	*x = FSKModulationConfig{}
	mi := &file_gw_gw_v3_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSKModulationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSKModulationConfig) ProtoMessage() {}

func (x *FSKModulationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSKModulationConfig.ProtoReflect.Descriptor instead.
func (*FSKModulationConfig) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{23}
}

func (x *FSKModulationConfig) GetBandwidth() uint32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *FSKModulationConfig) GetBitrate() uint32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

type GatewayCommandExecRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// Command to execute.
	// This command must be pre-configured in the LoRa Gateway Bridge configuration.
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// Execution request ID (UUID).
	// The same token will be returned when the execution of the command has
	// completed.
	ExecId []byte `protobuf:"bytes,3,opt,name=ExecId,json=execID,proto3" json:"ExecId,omitempty"`
	// Standard input.
	Stdin []byte `protobuf:"bytes,4,opt,name=stdin,proto3" json:"stdin,omitempty"`
	// Environment variables.
	Environment   map[string]string `protobuf:"bytes,5,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayCommandExecRequest) Reset() {
	*x = GatewayCommandExecRequest{}
	mi := &file_gw_gw_v3_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayCommandExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCommandExecRequest) ProtoMessage() {}

func (x *GatewayCommandExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCommandExecRequest.ProtoReflect.Descriptor instead.
func (*GatewayCommandExecRequest) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{24}
}

func (x *GatewayCommandExecRequest) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *GatewayCommandExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GatewayCommandExecRequest) GetExecId() []byte {
	if x != nil {
		return x.ExecId
	}
	return nil
}

func (x *GatewayCommandExecRequest) GetStdin() []byte {
	if x != nil {
		return x.Stdin
	}
	return nil
}

func (x *GatewayCommandExecRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

type GatewayCommandExecResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// Execution request ID (UUID).
	ExecId []byte `protobuf:"bytes,2,opt,name=exec_id,json=execID,proto3" json:"exec_id,omitempty"`
	// Standard output.
	Stdout []byte `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Standard error.
	Stderr []byte `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// Error message.
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayCommandExecResponse) Reset() {
	*x = GatewayCommandExecResponse{}
	mi := &file_gw_gw_v3_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayCommandExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCommandExecResponse) ProtoMessage() {}

func (x *GatewayCommandExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCommandExecResponse.ProtoReflect.Descriptor instead.
func (*GatewayCommandExecResponse) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{25}
}

func (x *GatewayCommandExecResponse) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *GatewayCommandExecResponse) GetExecId() []byte {
	if x != nil {
		return x.ExecId
	}
	return nil
}

func (x *GatewayCommandExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *GatewayCommandExecResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *GatewayCommandExecResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// RawPacketForwarderEvent contains a raw packet-forwarder event.
// It can be used to access packet-forwarder features that are not (fully)
// integrated with the ChirpStack Gateway Bridge.
type RawPacketForwarderEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// Raw ID (UUID).
	RawId []byte `protobuf:"bytes,2,opt,name=raw_id,json=rawID,proto3" json:"raw_id,omitempty"`
	// Payload contains the raw payload.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPacketForwarderEvent) Reset() {
	*x = RawPacketForwarderEvent{}
	mi := &file_gw_gw_v3_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPacketForwarderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPacketForwarderEvent) ProtoMessage() {}

func (x *RawPacketForwarderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPacketForwarderEvent.ProtoReflect.Descriptor instead.
func (*RawPacketForwarderEvent) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{26}
}

func (x *RawPacketForwarderEvent) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *RawPacketForwarderEvent) GetRawId() []byte {
	if x != nil {
		return x.RawId
	}
	return nil
}

func (x *RawPacketForwarderEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// RawPacketForwarderEvent contains a raw packet-forwarder command.
// It can be used to access packet-forwarder features that are not (fully)
// integrated with the ChirpStack Gateway Bridge.
type RawPacketForwarderCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	// Raw ID (UUID).
	RawId []byte `protobuf:"bytes,2,opt,name=raw_id,json=rawID,proto3" json:"raw_id,omitempty"`
	// Payload contains the raw payload.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPacketForwarderCommand) Reset() {
	*x = RawPacketForwarderCommand{}
	mi := &file_gw_gw_v3_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPacketForwarderCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPacketForwarderCommand) ProtoMessage() {}

func (x *RawPacketForwarderCommand) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPacketForwarderCommand.ProtoReflect.Descriptor instead.
func (*RawPacketForwarderCommand) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{27}
}

func (x *RawPacketForwarderCommand) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *RawPacketForwarderCommand) GetRawId() []byte {
	if x != nil {
		return x.RawId
	}
	return nil
}

func (x *RawPacketForwarderCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ConnState contains the connection state of a gateway.
type ConnState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID.
	GatewayId     []byte          `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayID,proto3" json:"gateway_id,omitempty"`
	State         ConnState_State `protobuf:"varint,2,opt,name=state,proto3,enum=gw_v3.ConnState_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnState) Reset() {
	*x = ConnState{}
	mi := &file_gw_gw_v3_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnState) ProtoMessage() {}

func (x *ConnState) ProtoReflect() protoreflect.Message {
	mi := &file_gw_gw_v3_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnState.ProtoReflect.Descriptor instead.
func (*ConnState) Descriptor() ([]byte, []int) {
	return file_gw_gw_v3_proto_rawDescGZIP(), []int{28}
}

func (x *ConnState) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *ConnState) GetState() ConnState_State {
	if x != nil {
		return x.State
	}
	return ConnState_OFFLINE
}

var File_gw_gw_v3_proto protoreflect.FileDescriptor

const file_gw_gw_v3_proto_rawDesc = "" +
	"\n" +
	"\x0egw/gw_v3.proto\x12\x05gw_v3\x1a\x16common/common_v3.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xb1\x01\n" +
	"\n" +
	"Modulation\x12/\n" +
	"\x04lora\x18\x03 \x01(\v2\x19.gw_v3.LoRaModulationInfoH\x00R\x04loRa\x12,\n" +
	"\x03fsk\x18\x04 \x01(\v2\x18.gw_v3.FSKModulationInfoH\x00R\x03fsk\x126\n" +
	"\alr_fhss\x18\x05 \x01(\v2\x1b.gw_v3.LRFHSSModulationInfoH\x00R\x06lrFHSSB\f\n" +
	"\n" +
	"parameters\"\xe7\x02\n" +
	"\fUplinkTXInfo\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\rR\tfrequency\x125\n" +
	"\n" +
	"modulation\x18\x02 \x01(\x0e2\x15.common_v3.ModulationR\n" +
	"modulation\x12M\n" +
	"\x14lora_modulation_info\x18\x03 \x01(\v2\x19.gw_v3.LoRaModulationInfoH\x00R\x12loRaModulationInfo\x12J\n" +
	"\x13fsk_modulation_info\x18\x04 \x01(\v2\x18.gw_v3.FSKModulationInfoH\x00R\x11fskModulationInfo\x12T\n" +
	"\x17lr_fhss_modulation_info\x18\x05 \x01(\v2\x1b.gw_v3.LRFHSSModulationInfoH\x00R\x14lrFHSSModulationInfoB\x11\n" +
	"\x0fmodulation_info\"\xb1\x01\n" +
	"\x12LoRaModulationInfo\x12\x1c\n" +
	"\tbandwidth\x18\x01 \x01(\rR\tbandwidth\x12)\n" +
	"\x10spreading_factor\x18\x02 \x01(\rR\x0fspreadingFactor\x12\x1b\n" +
	"\tcode_rate\x18\x03 \x01(\tR\bcodeRate\x125\n" +
	"\x16polarization_inversion\x18\x04 \x01(\bR\x15polarizationInversion\"`\n" +
	"\x11FSKModulationInfo\x12/\n" +
	"\x13frequency_deviation\x18\x01 \x01(\rR\x12frequencyDeviation\x12\x1a\n" +
	"\bdatarate\x18\x02 \x01(\rR\bdatarate\"\x8a\x01\n" +
	"\x14LRFHSSModulationInfo\x126\n" +
	"\x17operating_channel_width\x18\x01 \x01(\rR\x15operatingChannelWidth\x12\x1b\n" +
	"\tcode_rate\x18\x02 \x01(\tR\bcodeRate\x12\x1d\n" +
	"\n" +
	"grid_steps\x18\x03 \x01(\rR\tgridSteps\"x\n" +
	"\x16EncryptedFineTimestamp\x12\"\n" +
	"\raes_key_index\x18\x01 \x01(\rR\vaesKeyIndex\x12!\n" +
	"\fencrypted_ns\x18\x02 \x01(\fR\vencryptedNS\x12\x17\n" +
	"\afpga_id\x18\x03 \x01(\fR\x06fpgaID\"D\n" +
	"\x12PlainFineTimestamp\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\xd9\t\n" +
	"\fGatewayStats\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\fR\tgatewayID\x12\x0e\n" +
	"\x02ip\x18\t \x01(\tR\x02ip\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12/\n" +
	"\blocation\x18\x03 \x01(\v2\x13.common_v3.LocationR\blocation\x12%\n" +
	"\x0econfig_version\x18\x04 \x01(\tR\rconfigVersion\x12.\n" +
	"\x13rx_packets_received\x18\x05 \x01(\rR\x11rxPacketsReceived\x123\n" +
	"\x16rx_packets_received_ok\x18\x06 \x01(\rR\x13rxPacketsReceivedOK\x12.\n" +
	"\x13tx_packets_received\x18\a \x01(\rR\x11txPacketsReceived\x12,\n" +
	"\x12tx_packets_emitted\x18\b \x01(\rR\x10txPacketsEmitted\x12>\n" +
	"\tmeta_data\x18\n" +
	" \x03(\v2!.gw_v3.GatewayStats.MetaDataEntryR\bmetaData\x12\x19\n" +
	"\bstats_id\x18\v \x01(\fR\astatsID\x12g\n" +
	"\x18tx_packets_per_frequency\x18\f \x03(\v2..gw_v3.GatewayStats.TxPacketsPerFrequencyEntryR\x15txPacketsPerFrequency\x12g\n" +
	"\x18rx_packets_per_frequency\x18\r \x03(\v2..gw_v3.GatewayStats.RxPacketsPerFrequencyEntryR\x15rxPacketsPerFrequency\x12T\n" +
	"\x19tx_packets_per_modulation\x18\x0e \x03(\v2\x19.gw_v3.PerModulationCountR\x16txPacketsPerModulation\x12T\n" +
	"\x19rx_packets_per_modulation\x18\x0f \x03(\v2\x19.gw_v3.PerModulationCountR\x16rxPacketsPerModulation\x12^\n" +
	"\x15tx_packets_per_status\x18\x10 \x03(\v2+.gw_v3.GatewayStats.TxPacketsPerStatusEntryR\x12txPacketsPerStatus\x1a;\n" +
	"\rMetaDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aH\n" +
	"\x1aTxPacketsPerFrequencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aH\n" +
	"\x1aRxPacketsPerFrequencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aE\n" +
	"\x17TxPacketsPerStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"]\n" +
	"\x12PerModulationCount\x121\n" +
	"\n" +
	"modulation\x18\x01 \x01(\v2\x11.gw_v3.ModulationR\n" +
	"modulation\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\xdc\x05\n" +
	"\fUplinkRXInfo\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\fR\tgatewayID\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12J\n" +
	"\x14time_since_gps_epoch\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x11timeSinceGPSEpoch\x12\x12\n" +
	"\x04rssi\x18\x05 \x01(\x05R\x04rssi\x12\x19\n" +
	"\blora_snr\x18\x06 \x01(\x01R\aloRaSNR\x12\x18\n" +
	"\achannel\x18\a \x01(\rR\achannel\x12\x19\n" +
	"\brf_chain\x18\b \x01(\rR\arfChain\x12\x14\n" +
	"\x05board\x18\t \x01(\rR\x05board\x12\x18\n" +
	"\aantenna\x18\n" +
	" \x01(\rR\aantenna\x12/\n" +
	"\blocation\x18\v \x01(\v2\x13.common_v3.LocationR\blocation\x12H\n" +
	"\x13fine_timestamp_type\x18\f \x01(\x0e2\x18.gw_v3.FineTimestampTypeR\x11fineTimestampType\x12Y\n" +
	"\x18encrypted_fine_timestamp\x18\r \x01(\v2\x1d.gw_v3.EncryptedFineTimestampH\x00R\x16encryptedFineTimestamp\x12M\n" +
	"\x14plain_fine_timestamp\x18\x0e \x01(\v2\x19.gw_v3.PlainFineTimestampH\x00R\x12plainFineTimestamp\x12\x18\n" +
	"\acontext\x18\x0f \x01(\fR\acontext\x12\x1b\n" +
	"\tuplink_id\x18\x10 \x01(\fR\buplinkID\x12/\n" +
	"\n" +
	"crc_status\x18\x11 \x01(\x0e2\x10.gw_v3.CRCStatusR\tcrcStatusB\x10\n" +
	"\x0efine_timestamp\"\xbe\x05\n" +
	"\x0eDownlinkTXInfo\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\fR\tgatewayID\x12\x1c\n" +
	"\tfrequency\x18\x05 \x01(\rR\tfrequency\x12\x14\n" +
	"\x05power\x18\x06 \x01(\x05R\x05power\x125\n" +
	"\n" +
	"modulation\x18\a \x01(\x0e2\x15.common_v3.ModulationR\n" +
	"modulation\x12M\n" +
	"\x14lora_modulation_info\x18\b \x01(\v2\x19.gw_v3.LoRaModulationInfoH\x00R\x12loRaModulationInfo\x12J\n" +
	"\x13fsk_modulation_info\x18\t \x01(\v2\x18.gw_v3.FSKModulationInfoH\x00R\x11fskModulationInfo\x12\x14\n" +
	"\x05board\x18\n" +
	" \x01(\rR\x05board\x12\x18\n" +
	"\aantenna\x18\v \x01(\rR\aantenna\x12-\n" +
	"\x06timing\x18\f \x01(\x0e2\x15.gw_v3.DownlinkTimingR\x06timing\x12V\n" +
	"\x17immediately_timing_info\x18\r \x01(\v2\x1c.gw_v3.ImmediatelyTimingInfoH\x01R\x15immediatelyTimingInfo\x12D\n" +
	"\x11delay_timing_info\x18\x0e \x01(\v2\x16.gw_v3.DelayTimingInfoH\x01R\x0fdelayTimingInfo\x12N\n" +
	"\x15gps_epoch_timing_info\x18\x0f \x01(\v2\x19.gw_v3.GPSEpochTimingInfoH\x01R\x12gpsEpochTimingInfo\x12\x18\n" +
	"\acontext\x18\x10 \x01(\fR\acontextB\x11\n" +
	"\x0fmodulation_infoB\r\n" +
	"\vtiming_info\"\x17\n" +
	"\x15ImmediatelyTimingInfo\"B\n" +
	"\x0fDelayTimingInfo\x12/\n" +
	"\x05delay\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x05delay\"`\n" +
	"\x12GPSEpochTimingInfo\x12J\n" +
	"\x14time_since_gps_epoch\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x11timeSinceGPSEpoch\"\x8a\x01\n" +
	"\vUplinkFrame\x12\x1f\n" +
	"\vphy_payload\x18\x01 \x01(\fR\n" +
	"phyPayload\x12,\n" +
	"\atx_info\x18\x02 \x01(\v2\x13.gw_v3.UplinkTXInfoR\x06txInfo\x12,\n" +
	"\arx_info\x18\x03 \x01(\v2\x13.gw_v3.UplinkRXInfoR\x06rxInfo\"\x8d\x01\n" +
	"\x0eUplinkFrameSet\x12\x1f\n" +
	"\vphy_payload\x18\x01 \x01(\fR\n" +
	"phyPayload\x12,\n" +
	"\atx_info\x18\x02 \x01(\v2\x13.gw_v3.UplinkTXInfoR\x06txInfo\x12,\n" +
	"\arx_info\x18\x03 \x03(\v2\x13.gw_v3.UplinkRXInfoR\x06rxInfo\"\xe6\x01\n" +
	"\rDownlinkFrame\x12\x1f\n" +
	"\vphy_payload\x18\x01 \x01(\fR\n" +
	"phyPayload\x12.\n" +
	"\atx_info\x18\x02 \x01(\v2\x15.gw_v3.DownlinkTXInfoR\x06txInfo\x12\x14\n" +
	"\x05token\x18\x03 \x01(\rR\x05token\x12\x1f\n" +
	"\vdownlink_id\x18\x04 \x01(\fR\n" +
	"downlinkID\x12.\n" +
	"\x05items\x18\x05 \x03(\v2\x18.gw_v3.DownlinkFrameItemR\x05items\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x06 \x01(\fR\tgatewayID\"d\n" +
	"\x11DownlinkFrameItem\x12\x1f\n" +
	"\vphy_payload\x18\x01 \x01(\fR\n" +
	"phyPayload\x12.\n" +
	"\atx_info\x18\x02 \x01(\v2\x15.gw_v3.DownlinkTXInfoR\x06txInfo\"\xab\x01\n" +
	"\rDownlinkTXAck\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\fR\tgatewayID\x12\x14\n" +
	"\x05token\x18\x02 \x01(\rR\x05token\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vdownlink_id\x18\x04 \x01(\fR\n" +
	"downlinkID\x12.\n" +
	"\x05items\x18\x05 \x03(\v2\x18.gw_v3.DownlinkTXAckItemR\x05items\"?\n" +
	"\x11DownlinkTXAckItem\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.gw_v3.TxAckStatusR\x06status\"\xca\x01\n" +
	"\x14GatewayConfiguration\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\fR\tgatewayID\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x127\n" +
	"\bchannels\x18\x03 \x03(\v2\x1b.gw_v3.ChannelConfigurationR\bchannels\x12@\n" +
	"\x0estats_interval\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\rstatsInterval\"\xdf\x02\n" +
	"\x14ChannelConfiguration\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\rR\tfrequency\x125\n" +
	"\n" +
	"modulation\x18\x02 \x01(\x0e2\x15.common_v3.ModulationR\n" +
	"modulation\x12S\n" +
	"\x16lora_modulation_config\x18\x03 \x01(\v2\x1b.gw_v3.LoRaModulationConfigH\x00R\x14loRaModulationConfig\x12P\n" +
	"\x15fsk_modulation_config\x18\x04 \x01(\v2\x1a.gw_v3.FSKModulationConfigH\x00R\x13fskModulationConfig\x12\x14\n" +
	"\x05board\x18\x05 \x01(\rR\x05board\x12 \n" +
	"\vdemodulator\x18\x06 \x01(\rR\vdemodulatorB\x13\n" +
	"\x11modulation_config\"a\n" +
	"\x14LoRaModulationConfig\x12\x1c\n" +
	"\tbandwidth\x18\x01 \x01(\rR\tbandwidth\x12+\n" +
	"\x11spreading_factors\x18\x02 \x03(\rR\x10spreadingFactors\"M\n" +
	"\x13FSKModulationConfig\x12\x1c\n" +
	"\tbandwidth\x18\x01 \x01(\rR\tbandwidth\x12\x18\n" +
	"\abitrate\x18\x02 \x01(\rR\abitrate\"\x97\x02\n" +
	"\x19GatewayCommandExecRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\fR\tgatewayID\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x16\n" +
	"\x06ExecId\x18\x03 \x01(\fR\x06execID\x12\x14\n" +
	"\x05stdin\x18\x04 \x01(\fR\x05stdin\x12S\n" +
	"\venvironment\x18\x05 \x03(\v21.gw_v3.GatewayCommandExecRequest.EnvironmentEntryR\venvironment\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\x1aGatewayCommandExecResponse\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\fR\tgatewayID\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\fR\x06execID\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\fR\x06stderr\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"i\n" +
	"\x17RawPacketForwarderEvent\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\fR\tgatewayID\x12\x15\n" +
	"\x06raw_id\x18\x02 \x01(\fR\x05rawID\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"k\n" +
	"\x19RawPacketForwarderCommand\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\fR\tgatewayID\x12\x15\n" +
	"\x06raw_id\x18\x02 \x01(\fR\x05rawID\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"z\n" +
	"\tConnState\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\fR\tgatewayID\x12,\n" +
	"\x05state\x18\x02 \x01(\x0e2\x16.gw_v3.ConnState.StateR\x05state\" \n" +
	"\x05State\x12\v\n" +
	"\aOFFLINE\x10\x00\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x01*;\n" +
	"\x0eDownlinkTiming\x12\x0f\n" +
	"\vIMMEDIATELY\x10\x00\x12\t\n" +
	"\x05DELAY\x10\x01\x12\r\n" +
	"\tGPS_EPOCH\x10\x02*7\n" +
	"\x11FineTimestampType\x12\b\n" +
	"\x04NONE\x10\x00\x12\r\n" +
	"\tENCRYPTED\x10\x01\x12\t\n" +
	"\x05PLAIN\x10\x02*0\n" +
	"\tCRCStatus\x12\n" +
	"\n" +
	"\x06NO_CRC\x10\x00\x12\v\n" +
	"\aBAD_CRC\x10\x01\x12\n" +
	"\n" +
	"\x06CRC_OK\x10\x02*\xbc\x01\n" +
	"\vTxAckStatus\x12\v\n" +
	"\aIGNORED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\f\n" +
	"\bTOO_LATE\x10\x02\x12\r\n" +
	"\tTOO_EARLY\x10\x03\x12\x14\n" +
	"\x10COLLISION_PACKET\x10\x04\x12\x14\n" +
	"\x10COLLISION_BEACON\x10\x05\x12\v\n" +
	"\aTX_FREQ\x10\x06\x12\f\n" +
	"\bTX_POWER\x10\a\x12\x10\n" +
	"\fGPS_UNLOCKED\x10\b\x12\x0e\n" +
	"\n" +
	"QUEUE_FULL\x10\t\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\n" +
	"BU\n" +
	"\x17io.chirpstack.api_v3.gwB\fGatewayProtoP\x01Z*github.com/brocaar/chirpstack-api/go/v3/gwb\x06proto3"

var (
	file_gw_gw_v3_proto_rawDescOnce sync.Once
	file_gw_gw_v3_proto_rawDescData []byte
)

func file_gw_gw_v3_proto_rawDescGZIP() []byte {
	file_gw_gw_v3_proto_rawDescOnce.Do(func() {
		file_gw_gw_v3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gw_gw_v3_proto_rawDesc), len(file_gw_gw_v3_proto_rawDesc)))
	})
	return file_gw_gw_v3_proto_rawDescData
}

var file_gw_gw_v3_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_gw_gw_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_gw_gw_v3_proto_goTypes = []any{
	(DownlinkTiming)(0),                // 0: gw_v3.DownlinkTiming
	(FineTimestampType)(0),             // 1: gw_v3.FineTimestampType
	(CRCStatus)(0),                     // 2: gw_v3.CRCStatus
	(TxAckStatus)(0),                   // 3: gw_v3.TxAckStatus
	(ConnState_State)(0),               // 4: gw_v3.ConnState.State
	(*Modulation)(nil),                 // 5: gw_v3.Modulation
	(*UplinkTXInfo)(nil),               // 6: gw_v3.UplinkTXInfo
	(*LoRaModulationInfo)(nil),         // 7: gw_v3.LoRaModulationInfo
	(*FSKModulationInfo)(nil),          // 8: gw_v3.FSKModulationInfo
	(*LRFHSSModulationInfo)(nil),       // 9: gw_v3.LRFHSSModulationInfo
	(*EncryptedFineTimestamp)(nil),     // 10: gw_v3.EncryptedFineTimestamp
	(*PlainFineTimestamp)(nil),         // 11: gw_v3.PlainFineTimestamp
	(*GatewayStats)(nil),               // 12: gw_v3.GatewayStats
	(*PerModulationCount)(nil),         // 13: gw_v3.PerModulationCount
	(*UplinkRXInfo)(nil),               // 14: gw_v3.UplinkRXInfo
	(*DownlinkTXInfo)(nil),             // 15: gw_v3.DownlinkTXInfo
	(*ImmediatelyTimingInfo)(nil),      // 16: gw_v3.ImmediatelyTimingInfo
	(*DelayTimingInfo)(nil),            // 17: gw_v3.DelayTimingInfo
	(*GPSEpochTimingInfo)(nil),         // 18: gw_v3.GPSEpochTimingInfo
	(*UplinkFrame)(nil),                // 19: gw_v3.UplinkFrame
	(*UplinkFrameSet)(nil),             // 20: gw_v3.UplinkFrameSet
	(*DownlinkFrame)(nil),              // 21: gw_v3.DownlinkFrame
	(*DownlinkFrameItem)(nil),          // 22: gw_v3.DownlinkFrameItem
	(*DownlinkTXAck)(nil),              // 23: gw_v3.DownlinkTXAck
	(*DownlinkTXAckItem)(nil),          // 24: gw_v3.DownlinkTXAckItem
	(*GatewayConfiguration)(nil),       // 25: gw_v3.GatewayConfiguration
	(*ChannelConfiguration)(nil),       // 26: gw_v3.ChannelConfiguration
	(*LoRaModulationConfig)(nil),       // 27: gw_v3.LoRaModulationConfig
	(*FSKModulationConfig)(nil),        // 28: gw_v3.FSKModulationConfig
	(*GatewayCommandExecRequest)(nil),  // 29: gw_v3.GatewayCommandExecRequest
	(*GatewayCommandExecResponse)(nil), // 30: gw_v3.GatewayCommandExecResponse
	(*RawPacketForwarderEvent)(nil),    // 31: gw_v3.RawPacketForwarderEvent
	(*RawPacketForwarderCommand)(nil),  // 32: gw_v3.RawPacketForwarderCommand
	(*ConnState)(nil),                  // 33: gw_v3.ConnState
	nil,                                // 34: gw_v3.GatewayStats.MetaDataEntry
	nil,                                // 35: gw_v3.GatewayStats.TxPacketsPerFrequencyEntry
	nil,                                // 36: gw_v3.GatewayStats.RxPacketsPerFrequencyEntry
	nil,                                // 37: gw_v3.GatewayStats.TxPacketsPerStatusEntry
	nil,                                // 38: gw_v3.GatewayCommandExecRequest.EnvironmentEntry
	(common.Modulation)(0),             // 39: common_v3.Modulation
	(*timestamp.Timestamp)(nil),        // 40: google.protobuf.Timestamp
	(*common.Location)(nil),            // 41: common_v3.Location
	(*duration.Duration)(nil),          // 42: google.protobuf.Duration
}
var file_gw_gw_v3_proto_depIdxs = []int32{
	7,  // 0: gw_v3.Modulation.lora:type_name -> gw_v3.LoRaModulationInfo
	8,  // 1: gw_v3.Modulation.fsk:type_name -> gw_v3.FSKModulationInfo
	9,  // 2: gw_v3.Modulation.lr_fhss:type_name -> gw_v3.LRFHSSModulationInfo
	39, // 3: gw_v3.UplinkTXInfo.modulation:type_name -> common_v3.Modulation
	7,  // 4: gw_v3.UplinkTXInfo.lora_modulation_info:type_name -> gw_v3.LoRaModulationInfo
	8,  // 5: gw_v3.UplinkTXInfo.fsk_modulation_info:type_name -> gw_v3.FSKModulationInfo
	9,  // 6: gw_v3.UplinkTXInfo.lr_fhss_modulation_info:type_name -> gw_v3.LRFHSSModulationInfo
	40, // 7: gw_v3.PlainFineTimestamp.time:type_name -> google.protobuf.Timestamp
	40, // 8: gw_v3.GatewayStats.time:type_name -> google.protobuf.Timestamp
	41, // 9: gw_v3.GatewayStats.location:type_name -> common_v3.Location
	34, // 10: gw_v3.GatewayStats.meta_data:type_name -> gw_v3.GatewayStats.MetaDataEntry
	35, // 11: gw_v3.GatewayStats.tx_packets_per_frequency:type_name -> gw_v3.GatewayStats.TxPacketsPerFrequencyEntry
	36, // 12: gw_v3.GatewayStats.rx_packets_per_frequency:type_name -> gw_v3.GatewayStats.RxPacketsPerFrequencyEntry
	13, // 13: gw_v3.GatewayStats.tx_packets_per_modulation:type_name -> gw_v3.PerModulationCount
	13, // 14: gw_v3.GatewayStats.rx_packets_per_modulation:type_name -> gw_v3.PerModulationCount
	37, // 15: gw_v3.GatewayStats.tx_packets_per_status:type_name -> gw_v3.GatewayStats.TxPacketsPerStatusEntry
	5,  // 16: gw_v3.PerModulationCount.modulation:type_name -> gw_v3.Modulation
	40, // 17: gw_v3.UplinkRXInfo.time:type_name -> google.protobuf.Timestamp
	42, // 18: gw_v3.UplinkRXInfo.time_since_gps_epoch:type_name -> google.protobuf.Duration
	41, // 19: gw_v3.UplinkRXInfo.location:type_name -> common_v3.Location
	1,  // 20: gw_v3.UplinkRXInfo.fine_timestamp_type:type_name -> gw_v3.FineTimestampType
	10, // 21: gw_v3.UplinkRXInfo.encrypted_fine_timestamp:type_name -> gw_v3.EncryptedFineTimestamp
	11, // 22: gw_v3.UplinkRXInfo.plain_fine_timestamp:type_name -> gw_v3.PlainFineTimestamp
	2,  // 23: gw_v3.UplinkRXInfo.crc_status:type_name -> gw_v3.CRCStatus
	39, // 24: gw_v3.DownlinkTXInfo.modulation:type_name -> common_v3.Modulation
	7,  // 25: gw_v3.DownlinkTXInfo.lora_modulation_info:type_name -> gw_v3.LoRaModulationInfo
	8,  // 26: gw_v3.DownlinkTXInfo.fsk_modulation_info:type_name -> gw_v3.FSKModulationInfo
	0,  // 27: gw_v3.DownlinkTXInfo.timing:type_name -> gw_v3.DownlinkTiming
	16, // 28: gw_v3.DownlinkTXInfo.immediately_timing_info:type_name -> gw_v3.ImmediatelyTimingInfo
	17, // 29: gw_v3.DownlinkTXInfo.delay_timing_info:type_name -> gw_v3.DelayTimingInfo
	18, // 30: gw_v3.DownlinkTXInfo.gps_epoch_timing_info:type_name -> gw_v3.GPSEpochTimingInfo
	42, // 31: gw_v3.DelayTimingInfo.delay:type_name -> google.protobuf.Duration
	42, // 32: gw_v3.GPSEpochTimingInfo.time_since_gps_epoch:type_name -> google.protobuf.Duration
	6,  // 33: gw_v3.UplinkFrame.tx_info:type_name -> gw_v3.UplinkTXInfo
	14, // 34: gw_v3.UplinkFrame.rx_info:type_name -> gw_v3.UplinkRXInfo
	6,  // 35: gw_v3.UplinkFrameSet.tx_info:type_name -> gw_v3.UplinkTXInfo
	14, // 36: gw_v3.UplinkFrameSet.rx_info:type_name -> gw_v3.UplinkRXInfo
	15, // 37: gw_v3.DownlinkFrame.tx_info:type_name -> gw_v3.DownlinkTXInfo
	22, // 38: gw_v3.DownlinkFrame.items:type_name -> gw_v3.DownlinkFrameItem
	15, // 39: gw_v3.DownlinkFrameItem.tx_info:type_name -> gw_v3.DownlinkTXInfo
	24, // 40: gw_v3.DownlinkTXAck.items:type_name -> gw_v3.DownlinkTXAckItem
	3,  // 41: gw_v3.DownlinkTXAckItem.status:type_name -> gw_v3.TxAckStatus
	26, // 42: gw_v3.GatewayConfiguration.channels:type_name -> gw_v3.ChannelConfiguration
	42, // 43: gw_v3.GatewayConfiguration.stats_interval:type_name -> google.protobuf.Duration
	39, // 44: gw_v3.ChannelConfiguration.modulation:type_name -> common_v3.Modulation
	27, // 45: gw_v3.ChannelConfiguration.lora_modulation_config:type_name -> gw_v3.LoRaModulationConfig
	28, // 46: gw_v3.ChannelConfiguration.fsk_modulation_config:type_name -> gw_v3.FSKModulationConfig
	38, // 47: gw_v3.GatewayCommandExecRequest.environment:type_name -> gw_v3.GatewayCommandExecRequest.EnvironmentEntry
	4,  // 48: gw_v3.ConnState.state:type_name -> gw_v3.ConnState.State
	49, // [49:49] is the sub-list for method output_type
	49, // [49:49] is the sub-list for method input_type
	49, // [49:49] is the sub-list for extension type_name
	49, // [49:49] is the sub-list for extension extendee
	0,  // [0:49] is the sub-list for field type_name
}

func init() { file_gw_gw_v3_proto_init() }
func file_gw_gw_v3_proto_init() {
	if File_gw_gw_v3_proto != nil {
		return
	}
	file_gw_gw_v3_proto_msgTypes[0].OneofWrappers = []any{
		(*Modulation_Lora)(nil),
		(*Modulation_Fsk)(nil),
		(*Modulation_LrFhss)(nil),
	}
	file_gw_gw_v3_proto_msgTypes[1].OneofWrappers = []any{
		(*UplinkTXInfo_LoraModulationInfo)(nil),
		(*UplinkTXInfo_FskModulationInfo)(nil),
		(*UplinkTXInfo_LrFhssModulationInfo)(nil),
	}
	file_gw_gw_v3_proto_msgTypes[9].OneofWrappers = []any{
		(*UplinkRXInfo_EncryptedFineTimestamp)(nil),
		(*UplinkRXInfo_PlainFineTimestamp)(nil),
	}
	file_gw_gw_v3_proto_msgTypes[10].OneofWrappers = []any{
		(*DownlinkTXInfo_LoraModulationInfo)(nil),
		(*DownlinkTXInfo_FskModulationInfo)(nil),
		(*DownlinkTXInfo_ImmediatelyTimingInfo)(nil),
		(*DownlinkTXInfo_DelayTimingInfo)(nil),
		(*DownlinkTXInfo_GpsEpochTimingInfo)(nil),
	}
	file_gw_gw_v3_proto_msgTypes[21].OneofWrappers = []any{
		(*ChannelConfiguration_LoraModulationConfig)(nil),
		(*ChannelConfiguration_FskModulationConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gw_gw_v3_proto_rawDesc), len(file_gw_gw_v3_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gw_gw_v3_proto_goTypes,
		DependencyIndexes: file_gw_gw_v3_proto_depIdxs,
		EnumInfos:         file_gw_gw_v3_proto_enumTypes,
		MessageInfos:      file_gw_gw_v3_proto_msgTypes,
	}.Build()
	File_gw_gw_v3_proto = out.File
	file_gw_gw_v3_proto_goTypes = nil
	file_gw_gw_v3_proto_depIdxs = nil
}
