// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: as/as_v3.proto

package as

import (
	context "context"
	common "github.com/IoTOpen/chirpstack-v3-api/go/v3/common"
	gw "github.com/IoTOpen/chirpstack-v3-api/go/v3/gw"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RXWindow int32

const (
	RXWindow_RX1 RXWindow = 0
	RXWindow_RX2 RXWindow = 1
)

// Enum value maps for RXWindow.
var (
	RXWindow_name = map[int32]string{
		0: "RX1",
		1: "RX2",
	}
	RXWindow_value = map[string]int32{
		"RX1": 0,
		"RX2": 1,
	}
)

func (x RXWindow) Enum() *RXWindow {
	p := new(RXWindow)
	*p = x
	return p
}

func (x RXWindow) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RXWindow) Descriptor() protoreflect.EnumDescriptor {
	return file_as_as_v3_proto_enumTypes[0].Descriptor()
}

func (RXWindow) Type() protoreflect.EnumType {
	return &file_as_as_v3_proto_enumTypes[0]
}

func (x RXWindow) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RXWindow.Descriptor instead.
func (RXWindow) EnumDescriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{0}
}

type ErrorType int32

const (
	// Generic error type.
	ErrorType_GENERIC ErrorType = 0
	// OTAA error.
	ErrorType_OTAA ErrorType = 1
	// Uplink frame-counter was reset.
	ErrorType_DATA_UP_FCNT_RESET ErrorType = 2
	// Uplink MIC error.
	ErrorType_DATA_UP_MIC ErrorType = 3
	// Downlink payload size error.
	ErrorType_DEVICE_QUEUE_ITEM_SIZE ErrorType = 4
	// Downlink frame-counter error.
	ErrorType_DEVICE_QUEUE_ITEM_FCNT ErrorType = 5
	// Uplink frame-counter retransmission.
	ErrorType_DATA_UP_FCNT_RETRANSMISSION ErrorType = 6
	// Downlink gateway error.
	ErrorType_DATA_DOWN_GATEWAY ErrorType = 7
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "GENERIC",
		1: "OTAA",
		2: "DATA_UP_FCNT_RESET",
		3: "DATA_UP_MIC",
		4: "DEVICE_QUEUE_ITEM_SIZE",
		5: "DEVICE_QUEUE_ITEM_FCNT",
		6: "DATA_UP_FCNT_RETRANSMISSION",
		7: "DATA_DOWN_GATEWAY",
	}
	ErrorType_value = map[string]int32{
		"GENERIC":                     0,
		"OTAA":                        1,
		"DATA_UP_FCNT_RESET":          2,
		"DATA_UP_MIC":                 3,
		"DEVICE_QUEUE_ITEM_SIZE":      4,
		"DEVICE_QUEUE_ITEM_FCNT":      5,
		"DATA_UP_FCNT_RETRANSMISSION": 6,
		"DATA_DOWN_GATEWAY":           7,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_as_as_v3_proto_enumTypes[1].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_as_as_v3_proto_enumTypes[1]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{1}
}

type DeviceActivationContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Assigned Device Address.
	DevAddr []byte `protobuf:"bytes,1,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	// Application session key (envelope).
	AppSKey       *common.KeyEnvelope `protobuf:"bytes,2,opt,name=app_s_key,json=appSKey,proto3" json:"app_s_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceActivationContext) Reset() {
	*x = DeviceActivationContext{}
	mi := &file_as_as_v3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceActivationContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceActivationContext) ProtoMessage() {}

func (x *DeviceActivationContext) ProtoReflect() protoreflect.Message {
	mi := &file_as_as_v3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceActivationContext.ProtoReflect.Descriptor instead.
func (*DeviceActivationContext) Descriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceActivationContext) GetDevAddr() []byte {
	if x != nil {
		return x.DevAddr
	}
	return nil
}

func (x *DeviceActivationContext) GetAppSKey() *common.KeyEnvelope {
	if x != nil {
		return x.AppSKey
	}
	return nil
}

type HandleUplinkDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DevEUI EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Join EUI used for OTAA activation (8 bytes).
	JoinEui []byte `protobuf:"bytes,2,opt,name=join_eui,json=joinEui,proto3" json:"join_eui,omitempty"`
	// Frame-counter.
	FCnt uint32 `protobuf:"varint,3,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// Frame port.
	FPort uint32 `protobuf:"varint,4,opt,name=f_port,json=fPort,proto3" json:"f_port,omitempty"`
	// ADR enabled.
	Adr bool `protobuf:"varint,5,opt,name=adr,proto3" json:"adr,omitempty"`
	// Data-rate.
	Dr uint32 `protobuf:"varint,6,opt,name=dr,proto3" json:"dr,omitempty"`
	// TX meta-data.
	TxInfo *gw.UplinkTXInfo `protobuf:"bytes,7,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// RX meta-data.
	RxInfo []*gw.UplinkRXInfo `protobuf:"bytes,8,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	// Received data (encrypted).
	Data []byte `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	// Device activation context.
	//
	// This field is only set on the first uplink frame when the security
	// context has changed (e.g. a new OTAA (re)activation).
	DeviceActivationContext *DeviceActivationContext `protobuf:"bytes,10,opt,name=device_activation_context,json=deviceActivationContext,proto3" json:"device_activation_context,omitempty"`
	// Uplink was of type confirmed.
	ConfirmedUplink bool `protobuf:"varint,11,opt,name=confirmed_uplink,json=confirmedUplink,proto3" json:"confirmed_uplink,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandleUplinkDataRequest) Reset() {
	*x = HandleUplinkDataRequest{}
	mi := &file_as_as_v3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleUplinkDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleUplinkDataRequest) ProtoMessage() {}

func (x *HandleUplinkDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_as_as_v3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleUplinkDataRequest.ProtoReflect.Descriptor instead.
func (*HandleUplinkDataRequest) Descriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{1}
}

func (x *HandleUplinkDataRequest) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *HandleUplinkDataRequest) GetJoinEui() []byte {
	if x != nil {
		return x.JoinEui
	}
	return nil
}

func (x *HandleUplinkDataRequest) GetFCnt() uint32 {
	if x != nil {
		return x.FCnt
	}
	return 0
}

func (x *HandleUplinkDataRequest) GetFPort() uint32 {
	if x != nil {
		return x.FPort
	}
	return 0
}

func (x *HandleUplinkDataRequest) GetAdr() bool {
	if x != nil {
		return x.Adr
	}
	return false
}

func (x *HandleUplinkDataRequest) GetDr() uint32 {
	if x != nil {
		return x.Dr
	}
	return 0
}

func (x *HandleUplinkDataRequest) GetTxInfo() *gw.UplinkTXInfo {
	if x != nil {
		return x.TxInfo
	}
	return nil
}

func (x *HandleUplinkDataRequest) GetRxInfo() []*gw.UplinkRXInfo {
	if x != nil {
		return x.RxInfo
	}
	return nil
}

func (x *HandleUplinkDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HandleUplinkDataRequest) GetDeviceActivationContext() *DeviceActivationContext {
	if x != nil {
		return x.DeviceActivationContext
	}
	return nil
}

func (x *HandleUplinkDataRequest) GetConfirmedUplink() bool {
	if x != nil {
		return x.ConfirmedUplink
	}
	return false
}

type HandleProprietaryUplinkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MACPayload of the proprietary LoRaWAN frame.
	MacPayload []byte `protobuf:"bytes,1,opt,name=mac_payload,json=macPayload,proto3" json:"mac_payload,omitempty"`
	// MIC of the proprietary LoRaWAN frame.
	Mic []byte `protobuf:"bytes,2,opt,name=mic,proto3" json:"mic,omitempty"`
	// TXInfo contains the TX related meta-data.
	TxInfo *gw.UplinkTXInfo `protobuf:"bytes,3,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// RXInfo contains the RX related meta-data.
	RxInfo        []*gw.UplinkRXInfo `protobuf:"bytes,4,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleProprietaryUplinkRequest) Reset() {
	*x = HandleProprietaryUplinkRequest{}
	mi := &file_as_as_v3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleProprietaryUplinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleProprietaryUplinkRequest) ProtoMessage() {}

func (x *HandleProprietaryUplinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_as_as_v3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleProprietaryUplinkRequest.ProtoReflect.Descriptor instead.
func (*HandleProprietaryUplinkRequest) Descriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{2}
}

func (x *HandleProprietaryUplinkRequest) GetMacPayload() []byte {
	if x != nil {
		return x.MacPayload
	}
	return nil
}

func (x *HandleProprietaryUplinkRequest) GetMic() []byte {
	if x != nil {
		return x.Mic
	}
	return nil
}

func (x *HandleProprietaryUplinkRequest) GetTxInfo() *gw.UplinkTXInfo {
	if x != nil {
		return x.TxInfo
	}
	return nil
}

func (x *HandleProprietaryUplinkRequest) GetRxInfo() []*gw.UplinkRXInfo {
	if x != nil {
		return x.RxInfo
	}
	return nil
}

type HandleErrorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Type of the error.
	Type ErrorType `protobuf:"varint,3,opt,name=type,proto3,enum=as_v3.ErrorType" json:"type,omitempty"`
	// Error string describing the error.
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// Frame-counter (if applicable) related to the error.
	FCnt          uint32 `protobuf:"varint,5,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleErrorRequest) Reset() {
	*x = HandleErrorRequest{}
	mi := &file_as_as_v3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleErrorRequest) ProtoMessage() {}

func (x *HandleErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_as_as_v3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleErrorRequest.ProtoReflect.Descriptor instead.
func (*HandleErrorRequest) Descriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{3}
}

func (x *HandleErrorRequest) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *HandleErrorRequest) GetType() ErrorType {
	if x != nil {
		return x.Type
	}
	return ErrorType_GENERIC
}

func (x *HandleErrorRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HandleErrorRequest) GetFCnt() uint32 {
	if x != nil {
		return x.FCnt
	}
	return 0
}

type HandleDownlinkACKRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Downlink frame-counter.
	FCnt uint32 `protobuf:"varint,2,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// Frame was acknowledged?
	Acknowledged  bool `protobuf:"varint,3,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleDownlinkACKRequest) Reset() {
	*x = HandleDownlinkACKRequest{}
	mi := &file_as_as_v3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleDownlinkACKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleDownlinkACKRequest) ProtoMessage() {}

func (x *HandleDownlinkACKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_as_as_v3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleDownlinkACKRequest.ProtoReflect.Descriptor instead.
func (*HandleDownlinkACKRequest) Descriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{4}
}

func (x *HandleDownlinkACKRequest) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *HandleDownlinkACKRequest) GetFCnt() uint32 {
	if x != nil {
		return x.FCnt
	}
	return 0
}

func (x *HandleDownlinkACKRequest) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type SetDeviceStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Battery level (deprecated, use battery_level).
	// 0:      The end-device is connected to an external power source
	// 1..254: The battery level, 1 being at minimum and 254 being at maximum
	// 255:    The end-device was not able to measure the battery level
	Battery uint32 `protobuf:"varint,2,opt,name=battery,proto3" json:"battery,omitempty"`
	// The device margin status
	// -32..32: The demodulation SNR ration in dB
	Margin int32 `protobuf:"varint,3,opt,name=margin,proto3" json:"margin,omitempty"`
	// Device is connected to an external power source.
	ExternalPowerSource bool `protobuf:"varint,4,opt,name=external_power_source,json=externalPowerSource,proto3" json:"external_power_source,omitempty"`
	// Device battery status is not available.
	BatteryLevelUnavailable bool `protobuf:"varint,5,opt,name=battery_level_unavailable,json=batteryLevelUnavailable,proto3" json:"battery_level_unavailable,omitempty"`
	// Battery level as a percentage.
	BatteryLevel  float32 `protobuf:"fixed32,6,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceStatusRequest) Reset() {
	*x = SetDeviceStatusRequest{}
	mi := &file_as_as_v3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceStatusRequest) ProtoMessage() {}

func (x *SetDeviceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_as_as_v3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceStatusRequest.ProtoReflect.Descriptor instead.
func (*SetDeviceStatusRequest) Descriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{5}
}

func (x *SetDeviceStatusRequest) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *SetDeviceStatusRequest) GetBattery() uint32 {
	if x != nil {
		return x.Battery
	}
	return 0
}

func (x *SetDeviceStatusRequest) GetMargin() int32 {
	if x != nil {
		return x.Margin
	}
	return 0
}

func (x *SetDeviceStatusRequest) GetExternalPowerSource() bool {
	if x != nil {
		return x.ExternalPowerSource
	}
	return false
}

func (x *SetDeviceStatusRequest) GetBatteryLevelUnavailable() bool {
	if x != nil {
		return x.BatteryLevelUnavailable
	}
	return false
}

func (x *SetDeviceStatusRequest) GetBatteryLevel() float32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

type SetDeviceLocationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// The location of the device.
	Location *common.Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	// Uplink IDs used for geolocation.
	UplinkIds     [][]byte `protobuf:"bytes,3,rep,name=uplink_ids,json=uplinkIds,proto3" json:"uplink_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceLocationRequest) Reset() {
	*x = SetDeviceLocationRequest{}
	mi := &file_as_as_v3_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceLocationRequest) ProtoMessage() {}

func (x *SetDeviceLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_as_as_v3_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceLocationRequest.ProtoReflect.Descriptor instead.
func (*SetDeviceLocationRequest) Descriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{6}
}

func (x *SetDeviceLocationRequest) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *SetDeviceLocationRequest) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *SetDeviceLocationRequest) GetUplinkIds() [][]byte {
	if x != nil {
		return x.UplinkIds
	}
	return nil
}

type HandleGatewayStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway ID (8 bytes).
	GatewayId []byte `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// Stats ID (UUID).
	StatsId []byte `protobuf:"bytes,2,opt,name=stats_id,json=statsId,proto3" json:"stats_id,omitempty"`
	// Timestamp.
	Time *timestamp.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	// Gateway location.
	Location *common.Location `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	// Uplink frames received.
	RxPacketsReceived uint32 `protobuf:"varint,5,opt,name=rx_packets_received,json=rxPacketsReceived,proto3" json:"rx_packets_received,omitempty"`
	// Uplink frames received OK.
	RxPacketsReceivedOk uint32 `protobuf:"varint,6,opt,name=rx_packets_received_ok,json=rxPacketsReceivedOk,proto3" json:"rx_packets_received_ok,omitempty"`
	// Downlink transmissions requested.
	TxPacketsReceived uint32 `protobuf:"varint,7,opt,name=tx_packets_received,json=txPacketsReceived,proto3" json:"tx_packets_received,omitempty"`
	// Downlink emitted.
	TxPacketsEmitted uint32 `protobuf:"varint,8,opt,name=tx_packets_emitted,json=txPacketsEmitted,proto3" json:"tx_packets_emitted,omitempty"`
	// Gateway metadata.
	Metadata map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Tx packets per frequency.
	TxPacketsPerFrequency map[uint32]uint32 `protobuf:"bytes,10,rep,name=tx_packets_per_frequency,json=txPacketsPerFrequency,proto3" json:"tx_packets_per_frequency,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Rx packets per frequency.
	RxPacketsPerFrequency map[uint32]uint32 `protobuf:"bytes,11,rep,name=rx_packets_per_frequency,json=rxPacketsPerFrequency,proto3" json:"rx_packets_per_frequency,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Tx packets per DR.
	TxPacketsPerDr map[uint32]uint32 `protobuf:"bytes,12,rep,name=tx_packets_per_dr,json=txPacketsPerDr,proto3" json:"tx_packets_per_dr,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Rx packets per DR.
	RxPacketsPerDr map[uint32]uint32 `protobuf:"bytes,13,rep,name=rx_packets_per_dr,json=rxPacketsPerDr,proto3" json:"rx_packets_per_dr,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Tx packets per status.
	TxPacketsPerStatus map[string]uint32 `protobuf:"bytes,14,rep,name=tx_packets_per_status,json=txPacketsPerStatus,proto3" json:"tx_packets_per_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HandleGatewayStatsRequest) Reset() {
	*x = HandleGatewayStatsRequest{}
	mi := &file_as_as_v3_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleGatewayStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGatewayStatsRequest) ProtoMessage() {}

func (x *HandleGatewayStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_as_as_v3_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGatewayStatsRequest.ProtoReflect.Descriptor instead.
func (*HandleGatewayStatsRequest) Descriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{7}
}

func (x *HandleGatewayStatsRequest) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *HandleGatewayStatsRequest) GetStatsId() []byte {
	if x != nil {
		return x.StatsId
	}
	return nil
}

func (x *HandleGatewayStatsRequest) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *HandleGatewayStatsRequest) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *HandleGatewayStatsRequest) GetRxPacketsReceived() uint32 {
	if x != nil {
		return x.RxPacketsReceived
	}
	return 0
}

func (x *HandleGatewayStatsRequest) GetRxPacketsReceivedOk() uint32 {
	if x != nil {
		return x.RxPacketsReceivedOk
	}
	return 0
}

func (x *HandleGatewayStatsRequest) GetTxPacketsReceived() uint32 {
	if x != nil {
		return x.TxPacketsReceived
	}
	return 0
}

func (x *HandleGatewayStatsRequest) GetTxPacketsEmitted() uint32 {
	if x != nil {
		return x.TxPacketsEmitted
	}
	return 0
}

func (x *HandleGatewayStatsRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HandleGatewayStatsRequest) GetTxPacketsPerFrequency() map[uint32]uint32 {
	if x != nil {
		return x.TxPacketsPerFrequency
	}
	return nil
}

func (x *HandleGatewayStatsRequest) GetRxPacketsPerFrequency() map[uint32]uint32 {
	if x != nil {
		return x.RxPacketsPerFrequency
	}
	return nil
}

func (x *HandleGatewayStatsRequest) GetTxPacketsPerDr() map[uint32]uint32 {
	if x != nil {
		return x.TxPacketsPerDr
	}
	return nil
}

func (x *HandleGatewayStatsRequest) GetRxPacketsPerDr() map[uint32]uint32 {
	if x != nil {
		return x.RxPacketsPerDr
	}
	return nil
}

func (x *HandleGatewayStatsRequest) GetTxPacketsPerStatus() map[string]uint32 {
	if x != nil {
		return x.TxPacketsPerStatus
	}
	return nil
}

type HandleTxAckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Downlink frame-counter.
	FCnt uint32 `protobuf:"varint,2,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// Gateway ID.
	GatewayId []byte `protobuf:"bytes,3,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	// TXInfo contains the TX related meta-data.
	TxInfo        *gw.DownlinkTXInfo `protobuf:"bytes,4,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleTxAckRequest) Reset() {
	*x = HandleTxAckRequest{}
	mi := &file_as_as_v3_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleTxAckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleTxAckRequest) ProtoMessage() {}

func (x *HandleTxAckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_as_as_v3_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleTxAckRequest.ProtoReflect.Descriptor instead.
func (*HandleTxAckRequest) Descriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{8}
}

func (x *HandleTxAckRequest) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *HandleTxAckRequest) GetFCnt() uint32 {
	if x != nil {
		return x.FCnt
	}
	return 0
}

func (x *HandleTxAckRequest) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

func (x *HandleTxAckRequest) GetTxInfo() *gw.DownlinkTXInfo {
	if x != nil {
		return x.TxInfo
	}
	return nil
}

type ReEncryptDeviceQueueItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DevEUI of the device.
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Device addres.
	// This is the device address which was used to encrypt the given
	// payloads.
	DevAddr []byte `protobuf:"bytes,2,opt,name=dev_addr,json=devAddr,proto3" json:"dev_addr,omitempty"`
	// Downlink frame-counter to start with.
	// The application-server must use this value when encrypting the first
	// item, and increment it for each successive item.
	FCntStart uint32 `protobuf:"varint,3,opt,name=f_cnt_start,json=fCntStart,proto3" json:"f_cnt_start,omitempty"`
	// Items to re-encrypt.
	Items         []*ReEncryptDeviceQueueItem `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEncryptDeviceQueueItemsRequest) Reset() {
	*x = ReEncryptDeviceQueueItemsRequest{}
	mi := &file_as_as_v3_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEncryptDeviceQueueItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEncryptDeviceQueueItemsRequest) ProtoMessage() {}

func (x *ReEncryptDeviceQueueItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_as_as_v3_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEncryptDeviceQueueItemsRequest.ProtoReflect.Descriptor instead.
func (*ReEncryptDeviceQueueItemsRequest) Descriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{9}
}

func (x *ReEncryptDeviceQueueItemsRequest) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *ReEncryptDeviceQueueItemsRequest) GetDevAddr() []byte {
	if x != nil {
		return x.DevAddr
	}
	return nil
}

func (x *ReEncryptDeviceQueueItemsRequest) GetFCntStart() uint32 {
	if x != nil {
		return x.FCntStart
	}
	return 0
}

func (x *ReEncryptDeviceQueueItemsRequest) GetItems() []*ReEncryptDeviceQueueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReEncryptDeviceQueueItemsResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Items         []*ReEncryptedDeviceQueueItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEncryptDeviceQueueItemsResponse) Reset() {
	*x = ReEncryptDeviceQueueItemsResponse{}
	mi := &file_as_as_v3_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEncryptDeviceQueueItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEncryptDeviceQueueItemsResponse) ProtoMessage() {}

func (x *ReEncryptDeviceQueueItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_as_as_v3_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEncryptDeviceQueueItemsResponse.ProtoReflect.Descriptor instead.
func (*ReEncryptDeviceQueueItemsResponse) Descriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{10}
}

func (x *ReEncryptDeviceQueueItemsResponse) GetItems() []*ReEncryptedDeviceQueueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReEncryptDeviceQueueItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The encrypted FRMPayload bytes.
	FrmPayload []byte `protobuf:"bytes,1,opt,name=frm_payload,json=frmPayload,proto3" json:"frm_payload,omitempty"`
	// The original FCnt of the payload.
	FCnt uint32 `protobuf:"varint,2,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// The FPort of the payload.
	FPort uint32 `protobuf:"varint,3,opt,name=f_port,json=fPort,proto3" json:"f_port,omitempty"`
	// Payload is of type confirmed.
	Confirmed     bool `protobuf:"varint,4,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEncryptDeviceQueueItem) Reset() {
	*x = ReEncryptDeviceQueueItem{}
	mi := &file_as_as_v3_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEncryptDeviceQueueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEncryptDeviceQueueItem) ProtoMessage() {}

func (x *ReEncryptDeviceQueueItem) ProtoReflect() protoreflect.Message {
	mi := &file_as_as_v3_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEncryptDeviceQueueItem.ProtoReflect.Descriptor instead.
func (*ReEncryptDeviceQueueItem) Descriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{11}
}

func (x *ReEncryptDeviceQueueItem) GetFrmPayload() []byte {
	if x != nil {
		return x.FrmPayload
	}
	return nil
}

func (x *ReEncryptDeviceQueueItem) GetFCnt() uint32 {
	if x != nil {
		return x.FCnt
	}
	return 0
}

func (x *ReEncryptDeviceQueueItem) GetFPort() uint32 {
	if x != nil {
		return x.FPort
	}
	return 0
}

func (x *ReEncryptDeviceQueueItem) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

type ReEncryptedDeviceQueueItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The re-encrypted FRMPayload bytes.
	FrmPayload []byte `protobuf:"bytes,1,opt,name=frm_payload,json=frmPayload,proto3" json:"frm_payload,omitempty"`
	// The new FCnt of the payload.
	FCnt uint32 `protobuf:"varint,2,opt,name=f_cnt,json=fCnt,proto3" json:"f_cnt,omitempty"`
	// The FPort of the payload.
	FPort uint32 `protobuf:"varint,3,opt,name=f_port,json=fPort,proto3" json:"f_port,omitempty"`
	// Payload is of type confirmed.
	Confirmed     bool `protobuf:"varint,4,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEncryptedDeviceQueueItem) Reset() {
	*x = ReEncryptedDeviceQueueItem{}
	mi := &file_as_as_v3_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEncryptedDeviceQueueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEncryptedDeviceQueueItem) ProtoMessage() {}

func (x *ReEncryptedDeviceQueueItem) ProtoReflect() protoreflect.Message {
	mi := &file_as_as_v3_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEncryptedDeviceQueueItem.ProtoReflect.Descriptor instead.
func (*ReEncryptedDeviceQueueItem) Descriptor() ([]byte, []int) {
	return file_as_as_v3_proto_rawDescGZIP(), []int{12}
}

func (x *ReEncryptedDeviceQueueItem) GetFrmPayload() []byte {
	if x != nil {
		return x.FrmPayload
	}
	return nil
}

func (x *ReEncryptedDeviceQueueItem) GetFCnt() uint32 {
	if x != nil {
		return x.FCnt
	}
	return 0
}

func (x *ReEncryptedDeviceQueueItem) GetFPort() uint32 {
	if x != nil {
		return x.FPort
	}
	return 0
}

func (x *ReEncryptedDeviceQueueItem) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

var File_as_as_v3_proto protoreflect.FileDescriptor

const file_as_as_v3_proto_rawDesc = "" +
	"\n" +
	"\x0eas/as_v3.proto\x12\x05as_v3\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16common/common_v3.proto\x1a\x0egw/gw_v3.proto\"h\n" +
	"\x17DeviceActivationContext\x12\x19\n" +
	"\bdev_addr\x18\x01 \x01(\fR\adevAddr\x122\n" +
	"\tapp_s_key\x18\x02 \x01(\v2\x16.common_v3.KeyEnvelopeR\aappSKey\"\x92\x03\n" +
	"\x17HandleUplinkDataRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEui\x12\x19\n" +
	"\bjoin_eui\x18\x02 \x01(\fR\ajoinEui\x12\x13\n" +
	"\x05f_cnt\x18\x03 \x01(\rR\x04fCnt\x12\x15\n" +
	"\x06f_port\x18\x04 \x01(\rR\x05fPort\x12\x10\n" +
	"\x03adr\x18\x05 \x01(\bR\x03adr\x12\x0e\n" +
	"\x02dr\x18\x06 \x01(\rR\x02dr\x12,\n" +
	"\atx_info\x18\a \x01(\v2\x13.gw_v3.UplinkTXInfoR\x06txInfo\x12,\n" +
	"\arx_info\x18\b \x03(\v2\x13.gw_v3.UplinkRXInfoR\x06rxInfo\x12\x12\n" +
	"\x04data\x18\t \x01(\fR\x04data\x12Z\n" +
	"\x19device_activation_context\x18\n" +
	" \x01(\v2\x1e.as_v3.DeviceActivationContextR\x17deviceActivationContext\x12)\n" +
	"\x10confirmed_uplink\x18\v \x01(\bR\x0fconfirmedUplink\"\xaf\x01\n" +
	"\x1eHandleProprietaryUplinkRequest\x12\x1f\n" +
	"\vmac_payload\x18\x01 \x01(\fR\n" +
	"macPayload\x12\x10\n" +
	"\x03mic\x18\x02 \x01(\fR\x03mic\x12,\n" +
	"\atx_info\x18\x03 \x01(\v2\x13.gw_v3.UplinkTXInfoR\x06txInfo\x12,\n" +
	"\arx_info\x18\x04 \x03(\v2\x13.gw_v3.UplinkRXInfoR\x06rxInfo\"~\n" +
	"\x12HandleErrorRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEui\x12$\n" +
	"\x04type\x18\x03 \x01(\x0e2\x10.as_v3.ErrorTypeR\x04type\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x13\n" +
	"\x05f_cnt\x18\x05 \x01(\rR\x04fCnt\"l\n" +
	"\x18HandleDownlinkACKRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEui\x12\x13\n" +
	"\x05f_cnt\x18\x02 \x01(\rR\x04fCnt\x12\"\n" +
	"\facknowledged\x18\x03 \x01(\bR\facknowledged\"\xf8\x01\n" +
	"\x16SetDeviceStatusRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEui\x12\x18\n" +
	"\abattery\x18\x02 \x01(\rR\abattery\x12\x16\n" +
	"\x06margin\x18\x03 \x01(\x05R\x06margin\x122\n" +
	"\x15external_power_source\x18\x04 \x01(\bR\x13externalPowerSource\x12:\n" +
	"\x19battery_level_unavailable\x18\x05 \x01(\bR\x17batteryLevelUnavailable\x12#\n" +
	"\rbattery_level\x18\x06 \x01(\x02R\fbatteryLevel\"\x83\x01\n" +
	"\x18SetDeviceLocationRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEui\x12/\n" +
	"\blocation\x18\x02 \x01(\v2\x13.common_v3.LocationR\blocation\x12\x1d\n" +
	"\n" +
	"uplink_ids\x18\x03 \x03(\fR\tuplinkIds\"\xfe\n" +
	"\n" +
	"\x19HandleGatewayStatsRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\fR\tgatewayId\x12\x19\n" +
	"\bstats_id\x18\x02 \x01(\fR\astatsId\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12/\n" +
	"\blocation\x18\x04 \x01(\v2\x13.common_v3.LocationR\blocation\x12.\n" +
	"\x13rx_packets_received\x18\x05 \x01(\rR\x11rxPacketsReceived\x123\n" +
	"\x16rx_packets_received_ok\x18\x06 \x01(\rR\x13rxPacketsReceivedOk\x12.\n" +
	"\x13tx_packets_received\x18\a \x01(\rR\x11txPacketsReceived\x12,\n" +
	"\x12tx_packets_emitted\x18\b \x01(\rR\x10txPacketsEmitted\x12J\n" +
	"\bmetadata\x18\t \x03(\v2..as_v3.HandleGatewayStatsRequest.MetadataEntryR\bmetadata\x12t\n" +
	"\x18tx_packets_per_frequency\x18\n" +
	" \x03(\v2;.as_v3.HandleGatewayStatsRequest.TxPacketsPerFrequencyEntryR\x15txPacketsPerFrequency\x12t\n" +
	"\x18rx_packets_per_frequency\x18\v \x03(\v2;.as_v3.HandleGatewayStatsRequest.RxPacketsPerFrequencyEntryR\x15rxPacketsPerFrequency\x12_\n" +
	"\x11tx_packets_per_dr\x18\f \x03(\v24.as_v3.HandleGatewayStatsRequest.TxPacketsPerDrEntryR\x0etxPacketsPerDr\x12_\n" +
	"\x11rx_packets_per_dr\x18\r \x03(\v24.as_v3.HandleGatewayStatsRequest.RxPacketsPerDrEntryR\x0erxPacketsPerDr\x12k\n" +
	"\x15tx_packets_per_status\x18\x0e \x03(\v28.as_v3.HandleGatewayStatsRequest.TxPacketsPerStatusEntryR\x12txPacketsPerStatus\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aH\n" +
	"\x1aTxPacketsPerFrequencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aH\n" +
	"\x1aRxPacketsPerFrequencyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aA\n" +
	"\x13TxPacketsPerDrEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aA\n" +
	"\x13RxPacketsPerDrEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\x1aE\n" +
	"\x17TxPacketsPerStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\x91\x01\n" +
	"\x12HandleTxAckRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEui\x12\x13\n" +
	"\x05f_cnt\x18\x02 \x01(\rR\x04fCnt\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x03 \x01(\fR\tgatewayId\x12.\n" +
	"\atx_info\x18\x04 \x01(\v2\x15.gw_v3.DownlinkTXInfoR\x06txInfo\"\xad\x01\n" +
	" ReEncryptDeviceQueueItemsRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEui\x12\x19\n" +
	"\bdev_addr\x18\x02 \x01(\fR\adevAddr\x12\x1e\n" +
	"\vf_cnt_start\x18\x03 \x01(\rR\tfCntStart\x125\n" +
	"\x05items\x18\x04 \x03(\v2\x1f.as_v3.ReEncryptDeviceQueueItemR\x05items\"\\\n" +
	"!ReEncryptDeviceQueueItemsResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.as_v3.ReEncryptedDeviceQueueItemR\x05items\"\x85\x01\n" +
	"\x18ReEncryptDeviceQueueItem\x12\x1f\n" +
	"\vfrm_payload\x18\x01 \x01(\fR\n" +
	"frmPayload\x12\x13\n" +
	"\x05f_cnt\x18\x02 \x01(\rR\x04fCnt\x12\x15\n" +
	"\x06f_port\x18\x03 \x01(\rR\x05fPort\x12\x1c\n" +
	"\tconfirmed\x18\x04 \x01(\bR\tconfirmed\"\x87\x01\n" +
	"\x1aReEncryptedDeviceQueueItem\x12\x1f\n" +
	"\vfrm_payload\x18\x01 \x01(\fR\n" +
	"frmPayload\x12\x13\n" +
	"\x05f_cnt\x18\x02 \x01(\rR\x04fCnt\x12\x15\n" +
	"\x06f_port\x18\x03 \x01(\rR\x05fPort\x12\x1c\n" +
	"\tconfirmed\x18\x04 \x01(\bR\tconfirmed*\x1c\n" +
	"\bRXWindow\x12\a\n" +
	"\x03RX1\x10\x00\x12\a\n" +
	"\x03RX2\x10\x01*\xbb\x01\n" +
	"\tErrorType\x12\v\n" +
	"\aGENERIC\x10\x00\x12\b\n" +
	"\x04OTAA\x10\x01\x12\x16\n" +
	"\x12DATA_UP_FCNT_RESET\x10\x02\x12\x0f\n" +
	"\vDATA_UP_MIC\x10\x03\x12\x1a\n" +
	"\x16DEVICE_QUEUE_ITEM_SIZE\x10\x04\x12\x1a\n" +
	"\x16DEVICE_QUEUE_ITEM_FCNT\x10\x05\x12\x1f\n" +
	"\x1bDATA_UP_FCNT_RETRANSMISSION\x10\x06\x12\x15\n" +
	"\x11DATA_DOWN_GATEWAY\x10\a2\xfc\x05\n" +
	"\x18ApplicationServerService\x12L\n" +
	"\x10HandleUplinkData\x12\x1e.as_v3.HandleUplinkDataRequest\x1a\x16.google.protobuf.Empty\"\x00\x12Z\n" +
	"\x17HandleProprietaryUplink\x12%.as_v3.HandleProprietaryUplinkRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\vHandleError\x12\x19.as_v3.HandleErrorRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\x11HandleDownlinkACK\x12\x1f.as_v3.HandleDownlinkACKRequest\x1a\x16.google.protobuf.Empty\"\x00\x12P\n" +
	"\x12HandleGatewayStats\x12 .as_v3.HandleGatewayStatsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\vHandleTxAck\x12\x19.as_v3.HandleTxAckRequest\x1a\x16.google.protobuf.Empty\"\x00\x12J\n" +
	"\x0fSetDeviceStatus\x12\x1d.as_v3.SetDeviceStatusRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\x11SetDeviceLocation\x12\x1f.as_v3.SetDeviceLocationRequest\x1a\x16.google.protobuf.Empty\"\x00\x12p\n" +
	"\x19ReEncryptDeviceQueueItems\x12'.as_v3.ReEncryptDeviceQueueItemsRequest\x1a(.as_v3.ReEncryptDeviceQueueItemsResponse\"\x00Bb\n" +
	"\x17io.chirpstack.api_v3.asB\x16ApplicationServerProtoP\x01Z-github.com/IoTOpen/chirpstack-v3-api/go/v3/asb\x06proto3"

var (
	file_as_as_v3_proto_rawDescOnce sync.Once
	file_as_as_v3_proto_rawDescData []byte
)

func file_as_as_v3_proto_rawDescGZIP() []byte {
	file_as_as_v3_proto_rawDescOnce.Do(func() {
		file_as_as_v3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_as_as_v3_proto_rawDesc), len(file_as_as_v3_proto_rawDesc)))
	})
	return file_as_as_v3_proto_rawDescData
}

var file_as_as_v3_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_as_as_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_as_as_v3_proto_goTypes = []any{
	(RXWindow)(0),                             // 0: as_v3.RXWindow
	(ErrorType)(0),                            // 1: as_v3.ErrorType
	(*DeviceActivationContext)(nil),           // 2: as_v3.DeviceActivationContext
	(*HandleUplinkDataRequest)(nil),           // 3: as_v3.HandleUplinkDataRequest
	(*HandleProprietaryUplinkRequest)(nil),    // 4: as_v3.HandleProprietaryUplinkRequest
	(*HandleErrorRequest)(nil),                // 5: as_v3.HandleErrorRequest
	(*HandleDownlinkACKRequest)(nil),          // 6: as_v3.HandleDownlinkACKRequest
	(*SetDeviceStatusRequest)(nil),            // 7: as_v3.SetDeviceStatusRequest
	(*SetDeviceLocationRequest)(nil),          // 8: as_v3.SetDeviceLocationRequest
	(*HandleGatewayStatsRequest)(nil),         // 9: as_v3.HandleGatewayStatsRequest
	(*HandleTxAckRequest)(nil),                // 10: as_v3.HandleTxAckRequest
	(*ReEncryptDeviceQueueItemsRequest)(nil),  // 11: as_v3.ReEncryptDeviceQueueItemsRequest
	(*ReEncryptDeviceQueueItemsResponse)(nil), // 12: as_v3.ReEncryptDeviceQueueItemsResponse
	(*ReEncryptDeviceQueueItem)(nil),          // 13: as_v3.ReEncryptDeviceQueueItem
	(*ReEncryptedDeviceQueueItem)(nil),        // 14: as_v3.ReEncryptedDeviceQueueItem
	nil,                                       // 15: as_v3.HandleGatewayStatsRequest.MetadataEntry
	nil,                                       // 16: as_v3.HandleGatewayStatsRequest.TxPacketsPerFrequencyEntry
	nil,                                       // 17: as_v3.HandleGatewayStatsRequest.RxPacketsPerFrequencyEntry
	nil,                                       // 18: as_v3.HandleGatewayStatsRequest.TxPacketsPerDrEntry
	nil,                                       // 19: as_v3.HandleGatewayStatsRequest.RxPacketsPerDrEntry
	nil,                                       // 20: as_v3.HandleGatewayStatsRequest.TxPacketsPerStatusEntry
	(*common.KeyEnvelope)(nil),                // 21: common_v3.KeyEnvelope
	(*gw.UplinkTXInfo)(nil),                   // 22: gw_v3.UplinkTXInfo
	(*gw.UplinkRXInfo)(nil),                   // 23: gw_v3.UplinkRXInfo
	(*common.Location)(nil),                   // 24: common_v3.Location
	(*timestamp.Timestamp)(nil),               // 25: google.protobuf.Timestamp
	(*gw.DownlinkTXInfo)(nil),                 // 26: gw_v3.DownlinkTXInfo
	(*empty.Empty)(nil),                       // 27: google.protobuf.Empty
}
var file_as_as_v3_proto_depIdxs = []int32{
	21, // 0: as_v3.DeviceActivationContext.app_s_key:type_name -> common_v3.KeyEnvelope
	22, // 1: as_v3.HandleUplinkDataRequest.tx_info:type_name -> gw_v3.UplinkTXInfo
	23, // 2: as_v3.HandleUplinkDataRequest.rx_info:type_name -> gw_v3.UplinkRXInfo
	2,  // 3: as_v3.HandleUplinkDataRequest.device_activation_context:type_name -> as_v3.DeviceActivationContext
	22, // 4: as_v3.HandleProprietaryUplinkRequest.tx_info:type_name -> gw_v3.UplinkTXInfo
	23, // 5: as_v3.HandleProprietaryUplinkRequest.rx_info:type_name -> gw_v3.UplinkRXInfo
	1,  // 6: as_v3.HandleErrorRequest.type:type_name -> as_v3.ErrorType
	24, // 7: as_v3.SetDeviceLocationRequest.location:type_name -> common_v3.Location
	25, // 8: as_v3.HandleGatewayStatsRequest.time:type_name -> google.protobuf.Timestamp
	24, // 9: as_v3.HandleGatewayStatsRequest.location:type_name -> common_v3.Location
	15, // 10: as_v3.HandleGatewayStatsRequest.metadata:type_name -> as_v3.HandleGatewayStatsRequest.MetadataEntry
	16, // 11: as_v3.HandleGatewayStatsRequest.tx_packets_per_frequency:type_name -> as_v3.HandleGatewayStatsRequest.TxPacketsPerFrequencyEntry
	17, // 12: as_v3.HandleGatewayStatsRequest.rx_packets_per_frequency:type_name -> as_v3.HandleGatewayStatsRequest.RxPacketsPerFrequencyEntry
	18, // 13: as_v3.HandleGatewayStatsRequest.tx_packets_per_dr:type_name -> as_v3.HandleGatewayStatsRequest.TxPacketsPerDrEntry
	19, // 14: as_v3.HandleGatewayStatsRequest.rx_packets_per_dr:type_name -> as_v3.HandleGatewayStatsRequest.RxPacketsPerDrEntry
	20, // 15: as_v3.HandleGatewayStatsRequest.tx_packets_per_status:type_name -> as_v3.HandleGatewayStatsRequest.TxPacketsPerStatusEntry
	26, // 16: as_v3.HandleTxAckRequest.tx_info:type_name -> gw_v3.DownlinkTXInfo
	13, // 17: as_v3.ReEncryptDeviceQueueItemsRequest.items:type_name -> as_v3.ReEncryptDeviceQueueItem
	14, // 18: as_v3.ReEncryptDeviceQueueItemsResponse.items:type_name -> as_v3.ReEncryptedDeviceQueueItem
	3,  // 19: as_v3.ApplicationServerService.HandleUplinkData:input_type -> as_v3.HandleUplinkDataRequest
	4,  // 20: as_v3.ApplicationServerService.HandleProprietaryUplink:input_type -> as_v3.HandleProprietaryUplinkRequest
	5,  // 21: as_v3.ApplicationServerService.HandleError:input_type -> as_v3.HandleErrorRequest
	6,  // 22: as_v3.ApplicationServerService.HandleDownlinkACK:input_type -> as_v3.HandleDownlinkACKRequest
	9,  // 23: as_v3.ApplicationServerService.HandleGatewayStats:input_type -> as_v3.HandleGatewayStatsRequest
	10, // 24: as_v3.ApplicationServerService.HandleTxAck:input_type -> as_v3.HandleTxAckRequest
	7,  // 25: as_v3.ApplicationServerService.SetDeviceStatus:input_type -> as_v3.SetDeviceStatusRequest
	8,  // 26: as_v3.ApplicationServerService.SetDeviceLocation:input_type -> as_v3.SetDeviceLocationRequest
	11, // 27: as_v3.ApplicationServerService.ReEncryptDeviceQueueItems:input_type -> as_v3.ReEncryptDeviceQueueItemsRequest
	27, // 28: as_v3.ApplicationServerService.HandleUplinkData:output_type -> google.protobuf.Empty
	27, // 29: as_v3.ApplicationServerService.HandleProprietaryUplink:output_type -> google.protobuf.Empty
	27, // 30: as_v3.ApplicationServerService.HandleError:output_type -> google.protobuf.Empty
	27, // 31: as_v3.ApplicationServerService.HandleDownlinkACK:output_type -> google.protobuf.Empty
	27, // 32: as_v3.ApplicationServerService.HandleGatewayStats:output_type -> google.protobuf.Empty
	27, // 33: as_v3.ApplicationServerService.HandleTxAck:output_type -> google.protobuf.Empty
	27, // 34: as_v3.ApplicationServerService.SetDeviceStatus:output_type -> google.protobuf.Empty
	27, // 35: as_v3.ApplicationServerService.SetDeviceLocation:output_type -> google.protobuf.Empty
	12, // 36: as_v3.ApplicationServerService.ReEncryptDeviceQueueItems:output_type -> as_v3.ReEncryptDeviceQueueItemsResponse
	28, // [28:37] is the sub-list for method output_type
	19, // [19:28] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_as_as_v3_proto_init() }
func file_as_as_v3_proto_init() {
	if File_as_as_v3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_as_as_v3_proto_rawDesc), len(file_as_as_v3_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_as_as_v3_proto_goTypes,
		DependencyIndexes: file_as_as_v3_proto_depIdxs,
		EnumInfos:         file_as_as_v3_proto_enumTypes,
		MessageInfos:      file_as_as_v3_proto_msgTypes,
	}.Build()
	File_as_as_v3_proto = out.File
	file_as_as_v3_proto_goTypes = nil
	file_as_as_v3_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ApplicationServerServiceClient is the client API for ApplicationServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ApplicationServerServiceClient interface {
	// HandleUplinkData handles uplink data received from an end-device.
	HandleUplinkData(ctx context.Context, in *HandleUplinkDataRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// HandleProprietaryUplink handles proprietary uplink payloads.
	HandleProprietaryUplink(ctx context.Context, in *HandleProprietaryUplinkRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// HandleError handles an error message.
	HandleError(ctx context.Context, in *HandleErrorRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// HandleDownlinkACK handles a downlink ACK or nACK response.
	HandleDownlinkACK(ctx context.Context, in *HandleDownlinkACKRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// HandleGatewayStats handles the given gateway stats.
	HandleGatewayStats(ctx context.Context, in *HandleGatewayStatsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// HandleTXACK handles the TX acknowledgement.
	HandleTxAck(ctx context.Context, in *HandleTxAckRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// SetDeviceStatus updates the device-status for a device.
	SetDeviceStatus(ctx context.Context, in *SetDeviceStatusRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// SetDeviceLocation updates the device-location for a device.
	SetDeviceLocation(ctx context.Context, in *SetDeviceLocationRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// ReEncryptDeviceQueueItems requests the application-server to re-encrypt
	// the given payload items using the new parameters. This request is
	// for example triggered when the associated frame-counter of a downlink
	// payload will be used by a mac-layer only payload, e.g. when the NS has
	// mac-commands (or ACKs) to send to the device and combining this with
	// an application-layer payload would exceed the max. payload size.
	// Note there is no requirement that the number of returned items must be
	// equal to the number of requested items.
	ReEncryptDeviceQueueItems(ctx context.Context, in *ReEncryptDeviceQueueItemsRequest, opts ...grpc.CallOption) (*ReEncryptDeviceQueueItemsResponse, error)
}

type applicationServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicationServerServiceClient(cc grpc.ClientConnInterface) ApplicationServerServiceClient {
	return &applicationServerServiceClient{cc}
}

func (c *applicationServerServiceClient) HandleUplinkData(ctx context.Context, in *HandleUplinkDataRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/as_v3.ApplicationServerService/HandleUplinkData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerServiceClient) HandleProprietaryUplink(ctx context.Context, in *HandleProprietaryUplinkRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/as_v3.ApplicationServerService/HandleProprietaryUplink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerServiceClient) HandleError(ctx context.Context, in *HandleErrorRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/as_v3.ApplicationServerService/HandleError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerServiceClient) HandleDownlinkACK(ctx context.Context, in *HandleDownlinkACKRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/as_v3.ApplicationServerService/HandleDownlinkACK", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerServiceClient) HandleGatewayStats(ctx context.Context, in *HandleGatewayStatsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/as_v3.ApplicationServerService/HandleGatewayStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerServiceClient) HandleTxAck(ctx context.Context, in *HandleTxAckRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/as_v3.ApplicationServerService/HandleTxAck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerServiceClient) SetDeviceStatus(ctx context.Context, in *SetDeviceStatusRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/as_v3.ApplicationServerService/SetDeviceStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerServiceClient) SetDeviceLocation(ctx context.Context, in *SetDeviceLocationRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/as_v3.ApplicationServerService/SetDeviceLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applicationServerServiceClient) ReEncryptDeviceQueueItems(ctx context.Context, in *ReEncryptDeviceQueueItemsRequest, opts ...grpc.CallOption) (*ReEncryptDeviceQueueItemsResponse, error) {
	out := new(ReEncryptDeviceQueueItemsResponse)
	err := c.cc.Invoke(ctx, "/as_v3.ApplicationServerService/ReEncryptDeviceQueueItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationServerServiceServer is the server API for ApplicationServerService service.
type ApplicationServerServiceServer interface {
	// HandleUplinkData handles uplink data received from an end-device.
	HandleUplinkData(context.Context, *HandleUplinkDataRequest) (*empty.Empty, error)
	// HandleProprietaryUplink handles proprietary uplink payloads.
	HandleProprietaryUplink(context.Context, *HandleProprietaryUplinkRequest) (*empty.Empty, error)
	// HandleError handles an error message.
	HandleError(context.Context, *HandleErrorRequest) (*empty.Empty, error)
	// HandleDownlinkACK handles a downlink ACK or nACK response.
	HandleDownlinkACK(context.Context, *HandleDownlinkACKRequest) (*empty.Empty, error)
	// HandleGatewayStats handles the given gateway stats.
	HandleGatewayStats(context.Context, *HandleGatewayStatsRequest) (*empty.Empty, error)
	// HandleTXACK handles the TX acknowledgement.
	HandleTxAck(context.Context, *HandleTxAckRequest) (*empty.Empty, error)
	// SetDeviceStatus updates the device-status for a device.
	SetDeviceStatus(context.Context, *SetDeviceStatusRequest) (*empty.Empty, error)
	// SetDeviceLocation updates the device-location for a device.
	SetDeviceLocation(context.Context, *SetDeviceLocationRequest) (*empty.Empty, error)
	// ReEncryptDeviceQueueItems requests the application-server to re-encrypt
	// the given payload items using the new parameters. This request is
	// for example triggered when the associated frame-counter of a downlink
	// payload will be used by a mac-layer only payload, e.g. when the NS has
	// mac-commands (or ACKs) to send to the device and combining this with
	// an application-layer payload would exceed the max. payload size.
	// Note there is no requirement that the number of returned items must be
	// equal to the number of requested items.
	ReEncryptDeviceQueueItems(context.Context, *ReEncryptDeviceQueueItemsRequest) (*ReEncryptDeviceQueueItemsResponse, error)
}

// UnimplementedApplicationServerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedApplicationServerServiceServer struct {
}

func (*UnimplementedApplicationServerServiceServer) HandleUplinkData(context.Context, *HandleUplinkDataRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleUplinkData not implemented")
}
func (*UnimplementedApplicationServerServiceServer) HandleProprietaryUplink(context.Context, *HandleProprietaryUplinkRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleProprietaryUplink not implemented")
}
func (*UnimplementedApplicationServerServiceServer) HandleError(context.Context, *HandleErrorRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleError not implemented")
}
func (*UnimplementedApplicationServerServiceServer) HandleDownlinkACK(context.Context, *HandleDownlinkACKRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleDownlinkACK not implemented")
}
func (*UnimplementedApplicationServerServiceServer) HandleGatewayStats(context.Context, *HandleGatewayStatsRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleGatewayStats not implemented")
}
func (*UnimplementedApplicationServerServiceServer) HandleTxAck(context.Context, *HandleTxAckRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleTxAck not implemented")
}
func (*UnimplementedApplicationServerServiceServer) SetDeviceStatus(context.Context, *SetDeviceStatusRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDeviceStatus not implemented")
}
func (*UnimplementedApplicationServerServiceServer) SetDeviceLocation(context.Context, *SetDeviceLocationRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDeviceLocation not implemented")
}
func (*UnimplementedApplicationServerServiceServer) ReEncryptDeviceQueueItems(context.Context, *ReEncryptDeviceQueueItemsRequest) (*ReEncryptDeviceQueueItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReEncryptDeviceQueueItems not implemented")
}

func RegisterApplicationServerServiceServer(s *grpc.Server, srv ApplicationServerServiceServer) {
	s.RegisterService(&_ApplicationServerService_serviceDesc, srv)
}

func _ApplicationServerService_HandleUplinkData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleUplinkDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).HandleUplinkData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as_v3.ApplicationServerService/HandleUplinkData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).HandleUplinkData(ctx, req.(*HandleUplinkDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServerService_HandleProprietaryUplink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleProprietaryUplinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).HandleProprietaryUplink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as_v3.ApplicationServerService/HandleProprietaryUplink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).HandleProprietaryUplink(ctx, req.(*HandleProprietaryUplinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServerService_HandleError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).HandleError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as_v3.ApplicationServerService/HandleError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).HandleError(ctx, req.(*HandleErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServerService_HandleDownlinkACK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleDownlinkACKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).HandleDownlinkACK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as_v3.ApplicationServerService/HandleDownlinkACK",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).HandleDownlinkACK(ctx, req.(*HandleDownlinkACKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServerService_HandleGatewayStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleGatewayStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).HandleGatewayStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as_v3.ApplicationServerService/HandleGatewayStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).HandleGatewayStats(ctx, req.(*HandleGatewayStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServerService_HandleTxAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleTxAckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).HandleTxAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as_v3.ApplicationServerService/HandleTxAck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).HandleTxAck(ctx, req.(*HandleTxAckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServerService_SetDeviceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).SetDeviceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as_v3.ApplicationServerService/SetDeviceStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).SetDeviceStatus(ctx, req.(*SetDeviceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServerService_SetDeviceLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).SetDeviceLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as_v3.ApplicationServerService/SetDeviceLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).SetDeviceLocation(ctx, req.(*SetDeviceLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApplicationServerService_ReEncryptDeviceQueueItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReEncryptDeviceQueueItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationServerServiceServer).ReEncryptDeviceQueueItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/as_v3.ApplicationServerService/ReEncryptDeviceQueueItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationServerServiceServer).ReEncryptDeviceQueueItems(ctx, req.(*ReEncryptDeviceQueueItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApplicationServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "as_v3.ApplicationServerService",
	HandlerType: (*ApplicationServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleUplinkData",
			Handler:    _ApplicationServerService_HandleUplinkData_Handler,
		},
		{
			MethodName: "HandleProprietaryUplink",
			Handler:    _ApplicationServerService_HandleProprietaryUplink_Handler,
		},
		{
			MethodName: "HandleError",
			Handler:    _ApplicationServerService_HandleError_Handler,
		},
		{
			MethodName: "HandleDownlinkACK",
			Handler:    _ApplicationServerService_HandleDownlinkACK_Handler,
		},
		{
			MethodName: "HandleGatewayStats",
			Handler:    _ApplicationServerService_HandleGatewayStats_Handler,
		},
		{
			MethodName: "HandleTxAck",
			Handler:    _ApplicationServerService_HandleTxAck_Handler,
		},
		{
			MethodName: "SetDeviceStatus",
			Handler:    _ApplicationServerService_SetDeviceStatus_Handler,
		},
		{
			MethodName: "SetDeviceLocation",
			Handler:    _ApplicationServerService_SetDeviceLocation_Handler,
		},
		{
			MethodName: "ReEncryptDeviceQueueItems",
			Handler:    _ApplicationServerService_ReEncryptDeviceQueueItems_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "as/as_v3.proto",
}
