// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: ns/profiles_v3.proto

package ns

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RatePolicy int32

const (
	// Drop
	RatePolicy_DROP RatePolicy = 0
	// Mark
	RatePolicy_MARK RatePolicy = 1
)

// Enum value maps for RatePolicy.
var (
	RatePolicy_name = map[int32]string{
		0: "DROP",
		1: "MARK",
	}
	RatePolicy_value = map[string]int32{
		"DROP": 0,
		"MARK": 1,
	}
)

func (x RatePolicy) Enum() *RatePolicy {
	p := new(RatePolicy)
	*p = x
	return p
}

func (x RatePolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RatePolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_ns_profiles_v3_proto_enumTypes[0].Descriptor()
}

func (RatePolicy) Type() protoreflect.EnumType {
	return &file_ns_profiles_v3_proto_enumTypes[0]
}

func (x RatePolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RatePolicy.Descriptor instead.
func (RatePolicy) EnumDescriptor() ([]byte, []int) {
	return file_ns_profiles_v3_proto_rawDescGZIP(), []int{0}
}

type ServiceProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service-profile ID.
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Token bucket filling rate, including ACKs (packet/h).
	UlRate uint32 `protobuf:"varint,2,opt,name=ul_rate,json=ulRate,proto3" json:"ul_rate,omitempty"`
	// Token bucket burst size.
	UlBucketSize uint32 `protobuf:"varint,3,opt,name=ul_bucket_size,json=ulBucketSize,proto3" json:"ul_bucket_size,omitempty"`
	// Drop or mark when exceeding ULRate.
	UlRatePolicy RatePolicy `protobuf:"varint,4,opt,name=ul_rate_policy,json=ulRatePolicy,proto3,enum=ns_v3.RatePolicy" json:"ul_rate_policy,omitempty"`
	// Token bucket filling rate, including ACKs (packet/h).
	DlRate uint32 `protobuf:"varint,5,opt,name=dl_rate,json=dlRate,proto3" json:"dl_rate,omitempty"`
	// Token bucket burst size.
	DlBucketSize uint32 `protobuf:"varint,6,opt,name=dl_bucket_size,json=dlBucketSize,proto3" json:"dl_bucket_size,omitempty"`
	// Drop or mark when exceeding DLRate.
	DlRatePolicy RatePolicy `protobuf:"varint,7,opt,name=dl_rate_policy,json=dlRatePolicy,proto3,enum=ns_v3.RatePolicy" json:"dl_rate_policy,omitempty"`
	// GW metadata (RSSI, SNR, GW geoloc., etc.) are added to the packet sent to AS.
	AddGwMetadata bool `protobuf:"varint,8,opt,name=add_gw_metadata,json=addGwMetadata,proto3" json:"add_gw_metadata,omitempty"`
	// Frequency to initiate an End-Device status request (request/day).
	DevStatusReqFreq uint32 `protobuf:"varint,9,opt,name=dev_status_req_freq,json=devStatusReqFreq,proto3" json:"dev_status_req_freq,omitempty"`
	// Report End-Device battery level to AS.
	ReportDevStatusBattery bool `protobuf:"varint,10,opt,name=report_dev_status_battery,json=reportDevStatusBattery,proto3" json:"report_dev_status_battery,omitempty"`
	// Report End-Device margin to AS.
	ReportDevStatusMargin bool `protobuf:"varint,11,opt,name=report_dev_status_margin,json=reportDevStatusMargin,proto3" json:"report_dev_status_margin,omitempty"`
	// Minimum allowed data rate. Used for ADR.
	DrMin uint32 `protobuf:"varint,12,opt,name=dr_min,json=drMin,proto3" json:"dr_min,omitempty"`
	// Maximum allowed data rate. Used for ADR.
	DrMax uint32 `protobuf:"varint,13,opt,name=dr_max,json=drMax,proto3" json:"dr_max,omitempty"`
	// Channel mask. sNS does not have to obey (i.e., informative).
	ChannelMask []byte `protobuf:"bytes,14,opt,name=channel_mask,json=channelMask,proto3" json:"channel_mask,omitempty"`
	// Passive Roaming allowed.
	PrAllowed bool `protobuf:"varint,15,opt,name=pr_allowed,json=prAllowed,proto3" json:"pr_allowed,omitempty"`
	// Handover Roaming allowed.
	HrAllowed bool `protobuf:"varint,16,opt,name=hr_allowed,json=hrAllowed,proto3" json:"hr_allowed,omitempty"`
	// Roaming Activation allowed.
	RaAllowed bool `protobuf:"varint,17,opt,name=ra_allowed,json=raAllowed,proto3" json:"ra_allowed,omitempty"`
	// Enable network geolocation service.
	NwkGeoLoc bool `protobuf:"varint,18,opt,name=nwk_geo_loc,json=nwkGeoLoc,proto3" json:"nwk_geo_loc,omitempty"`
	// Target Packet Error Rate.
	TargetPer uint32 `protobuf:"varint,19,opt,name=target_per,json=targetPer,proto3" json:"target_per,omitempty"`
	// Minimum number of receiving GWs (informative).
	MinGwDiversity uint32 `protobuf:"varint,20,opt,name=min_gw_diversity,json=minGwDiversity,proto3" json:"min_gw_diversity,omitempty"`
	// Gateways under this service-profile are private.
	// This means that these gateways can only be used by devices under the
	// same service-profile.
	GwsPrivate    bool `protobuf:"varint,21,opt,name=gws_private,json=gwsPrivate,proto3" json:"gws_private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceProfile) Reset() {
	*x = ServiceProfile{}
	mi := &file_ns_profiles_v3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceProfile) ProtoMessage() {}

func (x *ServiceProfile) ProtoReflect() protoreflect.Message {
	mi := &file_ns_profiles_v3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceProfile.ProtoReflect.Descriptor instead.
func (*ServiceProfile) Descriptor() ([]byte, []int) {
	return file_ns_profiles_v3_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceProfile) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ServiceProfile) GetUlRate() uint32 {
	if x != nil {
		return x.UlRate
	}
	return 0
}

func (x *ServiceProfile) GetUlBucketSize() uint32 {
	if x != nil {
		return x.UlBucketSize
	}
	return 0
}

func (x *ServiceProfile) GetUlRatePolicy() RatePolicy {
	if x != nil {
		return x.UlRatePolicy
	}
	return RatePolicy_DROP
}

func (x *ServiceProfile) GetDlRate() uint32 {
	if x != nil {
		return x.DlRate
	}
	return 0
}

func (x *ServiceProfile) GetDlBucketSize() uint32 {
	if x != nil {
		return x.DlBucketSize
	}
	return 0
}

func (x *ServiceProfile) GetDlRatePolicy() RatePolicy {
	if x != nil {
		return x.DlRatePolicy
	}
	return RatePolicy_DROP
}

func (x *ServiceProfile) GetAddGwMetadata() bool {
	if x != nil {
		return x.AddGwMetadata
	}
	return false
}

func (x *ServiceProfile) GetDevStatusReqFreq() uint32 {
	if x != nil {
		return x.DevStatusReqFreq
	}
	return 0
}

func (x *ServiceProfile) GetReportDevStatusBattery() bool {
	if x != nil {
		return x.ReportDevStatusBattery
	}
	return false
}

func (x *ServiceProfile) GetReportDevStatusMargin() bool {
	if x != nil {
		return x.ReportDevStatusMargin
	}
	return false
}

func (x *ServiceProfile) GetDrMin() uint32 {
	if x != nil {
		return x.DrMin
	}
	return 0
}

func (x *ServiceProfile) GetDrMax() uint32 {
	if x != nil {
		return x.DrMax
	}
	return 0
}

func (x *ServiceProfile) GetChannelMask() []byte {
	if x != nil {
		return x.ChannelMask
	}
	return nil
}

func (x *ServiceProfile) GetPrAllowed() bool {
	if x != nil {
		return x.PrAllowed
	}
	return false
}

func (x *ServiceProfile) GetHrAllowed() bool {
	if x != nil {
		return x.HrAllowed
	}
	return false
}

func (x *ServiceProfile) GetRaAllowed() bool {
	if x != nil {
		return x.RaAllowed
	}
	return false
}

func (x *ServiceProfile) GetNwkGeoLoc() bool {
	if x != nil {
		return x.NwkGeoLoc
	}
	return false
}

func (x *ServiceProfile) GetTargetPer() uint32 {
	if x != nil {
		return x.TargetPer
	}
	return 0
}

func (x *ServiceProfile) GetMinGwDiversity() uint32 {
	if x != nil {
		return x.MinGwDiversity
	}
	return 0
}

func (x *ServiceProfile) GetGwsPrivate() bool {
	if x != nil {
		return x.GwsPrivate
	}
	return false
}

type DeviceProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device-profile ID.
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// End-Device supports Class B.
	SupportsClassB bool `protobuf:"varint,2,opt,name=supports_class_b,json=supportsClassB,proto3" json:"supports_class_b,omitempty"`
	// Maximum delay for the End-Device to answer a MAC request or a confirmed DL frame (mandatory if class B mode supported).
	ClassBTimeout uint32 `protobuf:"varint,3,opt,name=class_b_timeout,json=classBTimeout,proto3" json:"class_b_timeout,omitempty"`
	// Mandatory if class B mode supported.
	PingSlotPeriod uint32 `protobuf:"varint,4,opt,name=ping_slot_period,json=pingSlotPeriod,proto3" json:"ping_slot_period,omitempty"`
	// Mandatory if class B mode supported.
	PingSlotDr uint32 `protobuf:"varint,5,opt,name=ping_slot_dr,json=pingSlotDr,proto3" json:"ping_slot_dr,omitempty"`
	// Mandatory if class B mode supported.
	PingSlotFreq uint32 `protobuf:"varint,6,opt,name=ping_slot_freq,json=pingSlotFreq,proto3" json:"ping_slot_freq,omitempty"`
	// End-Device supports Class C.
	SupportsClassC bool `protobuf:"varint,7,opt,name=supports_class_c,json=supportsClassC,proto3" json:"supports_class_c,omitempty"`
	// Maximum delay for the End-Device to answer a MAC request or a confirmed DL frame (mandatory if class C mode supported).
	ClassCTimeout uint32 `protobuf:"varint,8,opt,name=class_c_timeout,json=classCTimeout,proto3" json:"class_c_timeout,omitempty"`
	// Version of the LoRaWAN supported by the End-Device.
	MacVersion string `protobuf:"bytes,9,opt,name=mac_version,json=macVersion,proto3" json:"mac_version,omitempty"`
	// Revision of the Regional Parameters document supported by the End-Device.
	RegParamsRevision string `protobuf:"bytes,10,opt,name=reg_params_revision,json=regParamsRevision,proto3" json:"reg_params_revision,omitempty"`
	// Class A RX1 delay (mandatory for ABP).
	RxDelay_1 uint32 `protobuf:"varint,11,opt,name=rx_delay_1,json=rxDelay1,proto3" json:"rx_delay_1,omitempty"`
	// RX1 data rate offset (mandatory for ABP).
	RxDrOffset_1 uint32 `protobuf:"varint,12,opt,name=rx_dr_offset_1,json=rxDrOffset1,proto3" json:"rx_dr_offset_1,omitempty"`
	// RX2 data rate (mandatory for ABP).
	RxDatarate_2 uint32 `protobuf:"varint,13,opt,name=rx_datarate_2,json=rxDatarate2,proto3" json:"rx_datarate_2,omitempty"`
	// RX2 channel frequency (mandatory for ABP).
	RxFreq_2 uint32 `protobuf:"varint,14,opt,name=rx_freq_2,json=rxFreq2,proto3" json:"rx_freq_2,omitempty"`
	// List of factory-preset frequencies (mandatory for ABP).
	FactoryPresetFreqs []uint32 `protobuf:"varint,15,rep,packed,name=factory_preset_freqs,json=factoryPresetFreqs,proto3" json:"factory_preset_freqs,omitempty"`
	// Maximum EIRP supported by the End-Device.
	MaxEirp uint32 `protobuf:"varint,16,opt,name=max_eirp,json=maxEirp,proto3" json:"max_eirp,omitempty"`
	// Maximum duty cycle supported by the End-Device.
	MaxDutyCycle uint32 `protobuf:"varint,17,opt,name=max_duty_cycle,json=maxDutyCycle,proto3" json:"max_duty_cycle,omitempty"`
	// End-Device supports Join (OTAA) or not (ABP).
	SupportsJoin bool `protobuf:"varint,18,opt,name=supports_join,json=supportsJoin,proto3" json:"supports_join,omitempty"`
	// RF region name.
	RfRegion string `protobuf:"bytes,19,opt,name=rf_region,json=rfRegion,proto3" json:"rf_region,omitempty"`
	// End-Device uses 32bit FCnt (mandatory for LoRaWAN 1.0 End-Device).
	Supports_32BitFCnt bool `protobuf:"varint,20,opt,name=supports_32bit_f_cnt,json=supports32bitFCnt,proto3" json:"supports_32bit_f_cnt,omitempty"`
	// ADR algorithm ID.
	// In case this is left blank, or is configured to a non-existing ADR
	// algorithm (plugin), then it falls back to 'default'.
	AdrAlgorithmId string `protobuf:"bytes,21,opt,name=adr_algorithm_id,json=adrAlgorithmId,proto3" json:"adr_algorithm_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceProfile) Reset() {
	*x = DeviceProfile{}
	mi := &file_ns_profiles_v3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceProfile) ProtoMessage() {}

func (x *DeviceProfile) ProtoReflect() protoreflect.Message {
	mi := &file_ns_profiles_v3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceProfile.ProtoReflect.Descriptor instead.
func (*DeviceProfile) Descriptor() ([]byte, []int) {
	return file_ns_profiles_v3_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceProfile) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *DeviceProfile) GetSupportsClassB() bool {
	if x != nil {
		return x.SupportsClassB
	}
	return false
}

func (x *DeviceProfile) GetClassBTimeout() uint32 {
	if x != nil {
		return x.ClassBTimeout
	}
	return 0
}

func (x *DeviceProfile) GetPingSlotPeriod() uint32 {
	if x != nil {
		return x.PingSlotPeriod
	}
	return 0
}

func (x *DeviceProfile) GetPingSlotDr() uint32 {
	if x != nil {
		return x.PingSlotDr
	}
	return 0
}

func (x *DeviceProfile) GetPingSlotFreq() uint32 {
	if x != nil {
		return x.PingSlotFreq
	}
	return 0
}

func (x *DeviceProfile) GetSupportsClassC() bool {
	if x != nil {
		return x.SupportsClassC
	}
	return false
}

func (x *DeviceProfile) GetClassCTimeout() uint32 {
	if x != nil {
		return x.ClassCTimeout
	}
	return 0
}

func (x *DeviceProfile) GetMacVersion() string {
	if x != nil {
		return x.MacVersion
	}
	return ""
}

func (x *DeviceProfile) GetRegParamsRevision() string {
	if x != nil {
		return x.RegParamsRevision
	}
	return ""
}

func (x *DeviceProfile) GetRxDelay_1() uint32 {
	if x != nil {
		return x.RxDelay_1
	}
	return 0
}

func (x *DeviceProfile) GetRxDrOffset_1() uint32 {
	if x != nil {
		return x.RxDrOffset_1
	}
	return 0
}

func (x *DeviceProfile) GetRxDatarate_2() uint32 {
	if x != nil {
		return x.RxDatarate_2
	}
	return 0
}

func (x *DeviceProfile) GetRxFreq_2() uint32 {
	if x != nil {
		return x.RxFreq_2
	}
	return 0
}

func (x *DeviceProfile) GetFactoryPresetFreqs() []uint32 {
	if x != nil {
		return x.FactoryPresetFreqs
	}
	return nil
}

func (x *DeviceProfile) GetMaxEirp() uint32 {
	if x != nil {
		return x.MaxEirp
	}
	return 0
}

func (x *DeviceProfile) GetMaxDutyCycle() uint32 {
	if x != nil {
		return x.MaxDutyCycle
	}
	return 0
}

func (x *DeviceProfile) GetSupportsJoin() bool {
	if x != nil {
		return x.SupportsJoin
	}
	return false
}

func (x *DeviceProfile) GetRfRegion() string {
	if x != nil {
		return x.RfRegion
	}
	return ""
}

func (x *DeviceProfile) GetSupports_32BitFCnt() bool {
	if x != nil {
		return x.Supports_32BitFCnt
	}
	return false
}

func (x *DeviceProfile) GetAdrAlgorithmId() string {
	if x != nil {
		return x.AdrAlgorithmId
	}
	return ""
}

type RoutingProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the routing profile.
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Application-server ID.
	AsId string `protobuf:"bytes,2,opt,name=as_id,json=asId,proto3" json:"as_id,omitempty"`
	// CA certificate for connecting to the AS.
	CaCert string `protobuf:"bytes,3,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	// TLS certificate for connecting to the AS.
	TlsCert string `protobuf:"bytes,4,opt,name=tls_cert,json=tlsCert,proto3" json:"tls_cert,omitempty"`
	// TLS key for connecting to the AS.
	// Note: when retrieving the routing-profile, the tls_key is not returned
	// for security reasons. When updating the routing-profile, an empty tls_key
	// does not clear the certificate, unless the tls_cert is also left blank.
	TlsKey        string `protobuf:"bytes,5,opt,name=tls_key,json=tlsKey,proto3" json:"tls_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingProfile) Reset() {
	*x = RoutingProfile{}
	mi := &file_ns_profiles_v3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingProfile) ProtoMessage() {}

func (x *RoutingProfile) ProtoReflect() protoreflect.Message {
	mi := &file_ns_profiles_v3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingProfile.ProtoReflect.Descriptor instead.
func (*RoutingProfile) Descriptor() ([]byte, []int) {
	return file_ns_profiles_v3_proto_rawDescGZIP(), []int{2}
}

func (x *RoutingProfile) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RoutingProfile) GetAsId() string {
	if x != nil {
		return x.AsId
	}
	return ""
}

func (x *RoutingProfile) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

func (x *RoutingProfile) GetTlsCert() string {
	if x != nil {
		return x.TlsCert
	}
	return ""
}

func (x *RoutingProfile) GetTlsKey() string {
	if x != nil {
		return x.TlsKey
	}
	return ""
}

var File_ns_profiles_v3_proto protoreflect.FileDescriptor

const file_ns_profiles_v3_proto_rawDesc = "" +
	"\n" +
	"\x14ns/profiles_v3.proto\x12\x05ns_v3\"\x93\x06\n" +
	"\x0eServiceProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x17\n" +
	"\aul_rate\x18\x02 \x01(\rR\x06ulRate\x12$\n" +
	"\x0eul_bucket_size\x18\x03 \x01(\rR\fulBucketSize\x127\n" +
	"\x0eul_rate_policy\x18\x04 \x01(\x0e2\x11.ns_v3.RatePolicyR\fulRatePolicy\x12\x17\n" +
	"\adl_rate\x18\x05 \x01(\rR\x06dlRate\x12$\n" +
	"\x0edl_bucket_size\x18\x06 \x01(\rR\fdlBucketSize\x127\n" +
	"\x0edl_rate_policy\x18\a \x01(\x0e2\x11.ns_v3.RatePolicyR\fdlRatePolicy\x12&\n" +
	"\x0fadd_gw_metadata\x18\b \x01(\bR\raddGwMetadata\x12-\n" +
	"\x13dev_status_req_freq\x18\t \x01(\rR\x10devStatusReqFreq\x129\n" +
	"\x19report_dev_status_battery\x18\n" +
	" \x01(\bR\x16reportDevStatusBattery\x127\n" +
	"\x18report_dev_status_margin\x18\v \x01(\bR\x15reportDevStatusMargin\x12\x15\n" +
	"\x06dr_min\x18\f \x01(\rR\x05drMin\x12\x15\n" +
	"\x06dr_max\x18\r \x01(\rR\x05drMax\x12!\n" +
	"\fchannel_mask\x18\x0e \x01(\fR\vchannelMask\x12\x1d\n" +
	"\n" +
	"pr_allowed\x18\x0f \x01(\bR\tprAllowed\x12\x1d\n" +
	"\n" +
	"hr_allowed\x18\x10 \x01(\bR\thrAllowed\x12\x1d\n" +
	"\n" +
	"ra_allowed\x18\x11 \x01(\bR\traAllowed\x12\x1e\n" +
	"\vnwk_geo_loc\x18\x12 \x01(\bR\tnwkGeoLoc\x12\x1d\n" +
	"\n" +
	"target_per\x18\x13 \x01(\rR\ttargetPer\x12(\n" +
	"\x10min_gw_diversity\x18\x14 \x01(\rR\x0eminGwDiversity\x12\x1f\n" +
	"\vgws_private\x18\x15 \x01(\bR\n" +
	"gwsPrivate\"\x99\x06\n" +
	"\rDeviceProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12(\n" +
	"\x10supports_class_b\x18\x02 \x01(\bR\x0esupportsClassB\x12&\n" +
	"\x0fclass_b_timeout\x18\x03 \x01(\rR\rclassBTimeout\x12(\n" +
	"\x10ping_slot_period\x18\x04 \x01(\rR\x0epingSlotPeriod\x12 \n" +
	"\fping_slot_dr\x18\x05 \x01(\rR\n" +
	"pingSlotDr\x12$\n" +
	"\x0eping_slot_freq\x18\x06 \x01(\rR\fpingSlotFreq\x12(\n" +
	"\x10supports_class_c\x18\a \x01(\bR\x0esupportsClassC\x12&\n" +
	"\x0fclass_c_timeout\x18\b \x01(\rR\rclassCTimeout\x12\x1f\n" +
	"\vmac_version\x18\t \x01(\tR\n" +
	"macVersion\x12.\n" +
	"\x13reg_params_revision\x18\n" +
	" \x01(\tR\x11regParamsRevision\x12\x1c\n" +
	"\n" +
	"rx_delay_1\x18\v \x01(\rR\brxDelay1\x12#\n" +
	"\x0erx_dr_offset_1\x18\f \x01(\rR\vrxDrOffset1\x12\"\n" +
	"\rrx_datarate_2\x18\r \x01(\rR\vrxDatarate2\x12\x1a\n" +
	"\trx_freq_2\x18\x0e \x01(\rR\arxFreq2\x120\n" +
	"\x14factory_preset_freqs\x18\x0f \x03(\rR\x12factoryPresetFreqs\x12\x19\n" +
	"\bmax_eirp\x18\x10 \x01(\rR\amaxEirp\x12$\n" +
	"\x0emax_duty_cycle\x18\x11 \x01(\rR\fmaxDutyCycle\x12#\n" +
	"\rsupports_join\x18\x12 \x01(\bR\fsupportsJoin\x12\x1b\n" +
	"\trf_region\x18\x13 \x01(\tR\brfRegion\x12/\n" +
	"\x14supports_32bit_f_cnt\x18\x14 \x01(\bR\x11supports32bitFCnt\x12(\n" +
	"\x10adr_algorithm_id\x18\x15 \x01(\tR\x0eadrAlgorithmId\"\x82\x01\n" +
	"\x0eRoutingProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x13\n" +
	"\x05as_id\x18\x02 \x01(\tR\x04asId\x12\x17\n" +
	"\aca_cert\x18\x03 \x01(\tR\x06caCert\x12\x19\n" +
	"\btls_cert\x18\x04 \x01(\tR\atlsCert\x12\x17\n" +
	"\atls_key\x18\x05 \x01(\tR\x06tlsKey* \n" +
	"\n" +
	"RatePolicy\x12\b\n" +
	"\x04DROP\x10\x00\x12\b\n" +
	"\x04MARK\x10\x01BP\n" +
	"\x17io.chirpstack.api_v3.nsB\rProfilesProtoP\x01Z$github.com/brocaar/chirpstack-api/nsb\x06proto3"

var (
	file_ns_profiles_v3_proto_rawDescOnce sync.Once
	file_ns_profiles_v3_proto_rawDescData []byte
)

func file_ns_profiles_v3_proto_rawDescGZIP() []byte {
	file_ns_profiles_v3_proto_rawDescOnce.Do(func() {
		file_ns_profiles_v3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ns_profiles_v3_proto_rawDesc), len(file_ns_profiles_v3_proto_rawDesc)))
	})
	return file_ns_profiles_v3_proto_rawDescData
}

var file_ns_profiles_v3_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ns_profiles_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ns_profiles_v3_proto_goTypes = []any{
	(RatePolicy)(0),        // 0: ns_v3.RatePolicy
	(*ServiceProfile)(nil), // 1: ns_v3.ServiceProfile
	(*DeviceProfile)(nil),  // 2: ns_v3.DeviceProfile
	(*RoutingProfile)(nil), // 3: ns_v3.RoutingProfile
}
var file_ns_profiles_v3_proto_depIdxs = []int32{
	0, // 0: ns_v3.ServiceProfile.ul_rate_policy:type_name -> ns_v3.RatePolicy
	0, // 1: ns_v3.ServiceProfile.dl_rate_policy:type_name -> ns_v3.RatePolicy
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ns_profiles_v3_proto_init() }
func file_ns_profiles_v3_proto_init() {
	if File_ns_profiles_v3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ns_profiles_v3_proto_rawDesc), len(file_ns_profiles_v3_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ns_profiles_v3_proto_goTypes,
		DependencyIndexes: file_ns_profiles_v3_proto_depIdxs,
		EnumInfos:         file_ns_profiles_v3_proto_enumTypes,
		MessageInfos:      file_ns_profiles_v3_proto_msgTypes,
	}.Build()
	File_ns_profiles_v3_proto = out.File
	file_ns_profiles_v3_proto_goTypes = nil
	file_ns_profiles_v3_proto_depIdxs = nil
}
