// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: geo/geo_v3.proto

package geo

import (
	context "context"
	common "github.com/brocaar/chirpstack-api/go/v3/common"
	gw "github.com/brocaar/chirpstack-api/go/v3/gw"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resolved location.
	Location      *common.Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResult) Reset() {
	*x = ResolveResult{}
	mi := &file_geo_geo_v3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResult) ProtoMessage() {}

func (x *ResolveResult) ProtoReflect() protoreflect.Message {
	mi := &file_geo_geo_v3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResult.ProtoReflect.Descriptor instead.
func (*ResolveResult) Descriptor() ([]byte, []int) {
	return file_geo_geo_v3_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveResult) GetLocation() *common.Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type FrameRXInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uplink Gateway meta-data.
	RxInfo        []*gw.UplinkRXInfo `protobuf:"bytes,1,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameRXInfo) Reset() {
	*x = FrameRXInfo{}
	mi := &file_geo_geo_v3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRXInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRXInfo) ProtoMessage() {}

func (x *FrameRXInfo) ProtoReflect() protoreflect.Message {
	mi := &file_geo_geo_v3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRXInfo.ProtoReflect.Descriptor instead.
func (*FrameRXInfo) Descriptor() ([]byte, []int) {
	return file_geo_geo_v3_proto_rawDescGZIP(), []int{1}
}

func (x *FrameRXInfo) GetRxInfo() []*gw.UplinkRXInfo {
	if x != nil {
		return x.RxInfo
	}
	return nil
}

type ResolveTDOARequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device ID.
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Frame meta-data.
	FrameRxInfo *FrameRXInfo `protobuf:"bytes,2,opt,name=frame_rx_info,json=frameRXInfo,proto3" json:"frame_rx_info,omitempty"`
	// Device reference altitude.
	DeviceReferenceAltitude float64 `protobuf:"fixed64,3,opt,name=device_reference_altitude,json=deviceReferenceAltitude,proto3" json:"device_reference_altitude,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResolveTDOARequest) Reset() {
	*x = ResolveTDOARequest{}
	mi := &file_geo_geo_v3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTDOARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTDOARequest) ProtoMessage() {}

func (x *ResolveTDOARequest) ProtoReflect() protoreflect.Message {
	mi := &file_geo_geo_v3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTDOARequest.ProtoReflect.Descriptor instead.
func (*ResolveTDOARequest) Descriptor() ([]byte, []int) {
	return file_geo_geo_v3_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveTDOARequest) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *ResolveTDOARequest) GetFrameRxInfo() *FrameRXInfo {
	if x != nil {
		return x.FrameRxInfo
	}
	return nil
}

func (x *ResolveTDOARequest) GetDeviceReferenceAltitude() float64 {
	if x != nil {
		return x.DeviceReferenceAltitude
	}
	return 0
}

type ResolveMultiFrameTDOARequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device ID.
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEUI,proto3" json:"dev_eui,omitempty"`
	// Frames meta-data.
	FrameRxInfoSet []*FrameRXInfo `protobuf:"bytes,2,rep,name=frame_rx_info_set,json=frameRXInfoSet,proto3" json:"frame_rx_info_set,omitempty"`
	// Device reference altitude.
	DeviceReferenceAltitude float64 `protobuf:"fixed64,3,opt,name=device_reference_altitude,json=deviceReferenceAltitude,proto3" json:"device_reference_altitude,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResolveMultiFrameTDOARequest) Reset() {
	*x = ResolveMultiFrameTDOARequest{}
	mi := &file_geo_geo_v3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMultiFrameTDOARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMultiFrameTDOARequest) ProtoMessage() {}

func (x *ResolveMultiFrameTDOARequest) ProtoReflect() protoreflect.Message {
	mi := &file_geo_geo_v3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMultiFrameTDOARequest.ProtoReflect.Descriptor instead.
func (*ResolveMultiFrameTDOARequest) Descriptor() ([]byte, []int) {
	return file_geo_geo_v3_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveMultiFrameTDOARequest) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *ResolveMultiFrameTDOARequest) GetFrameRxInfoSet() []*FrameRXInfo {
	if x != nil {
		return x.FrameRxInfoSet
	}
	return nil
}

func (x *ResolveMultiFrameTDOARequest) GetDeviceReferenceAltitude() float64 {
	if x != nil {
		return x.DeviceReferenceAltitude
	}
	return 0
}

type ResolveTDOAResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resolve result.
	Result        *ResolveResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveTDOAResponse) Reset() {
	*x = ResolveTDOAResponse{}
	mi := &file_geo_geo_v3_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveTDOAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveTDOAResponse) ProtoMessage() {}

func (x *ResolveTDOAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geo_geo_v3_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveTDOAResponse.ProtoReflect.Descriptor instead.
func (*ResolveTDOAResponse) Descriptor() ([]byte, []int) {
	return file_geo_geo_v3_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveTDOAResponse) GetResult() *ResolveResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type ResolveMultiFrameTDOAResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resolve result.
	Result        *ResolveResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveMultiFrameTDOAResponse) Reset() {
	*x = ResolveMultiFrameTDOAResponse{}
	mi := &file_geo_geo_v3_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveMultiFrameTDOAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveMultiFrameTDOAResponse) ProtoMessage() {}

func (x *ResolveMultiFrameTDOAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geo_geo_v3_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveMultiFrameTDOAResponse.ProtoReflect.Descriptor instead.
func (*ResolveMultiFrameTDOAResponse) Descriptor() ([]byte, []int) {
	return file_geo_geo_v3_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveMultiFrameTDOAResponse) GetResult() *ResolveResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_geo_geo_v3_proto protoreflect.FileDescriptor

const file_geo_geo_v3_proto_rawDesc = "" +
	"\n" +
	"\x10geo/geo_v3.proto\x12\x06geo_v3\x1a\x0egw/gw_v3.proto\x1a\x16common/common_v3.proto\"@\n" +
	"\rResolveResult\x12/\n" +
	"\blocation\x18\x01 \x01(\v2\x13.common_v3.LocationR\blocation\";\n" +
	"\vFrameRXInfo\x12,\n" +
	"\arx_info\x18\x01 \x03(\v2\x13.gw_v3.UplinkRXInfoR\x06rxInfo\"\xa2\x01\n" +
	"\x12ResolveTDOARequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEUI\x127\n" +
	"\rframe_rx_info\x18\x02 \x01(\v2\x13.geo_v3.FrameRXInfoR\vframeRXInfo\x12:\n" +
	"\x19device_reference_altitude\x18\x03 \x01(\x01R\x17deviceReferenceAltitude\"\xb3\x01\n" +
	"\x1cResolveMultiFrameTDOARequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEUI\x12>\n" +
	"\x11frame_rx_info_set\x18\x02 \x03(\v2\x13.geo_v3.FrameRXInfoR\x0eframeRXInfoSet\x12:\n" +
	"\x19device_reference_altitude\x18\x03 \x01(\x01R\x17deviceReferenceAltitude\"D\n" +
	"\x13ResolveTDOAResponse\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.geo_v3.ResolveResultR\x06result\"N\n" +
	"\x1dResolveMultiFrameTDOAResponse\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x15.geo_v3.ResolveResultR\x06result2\xcc\x01\n" +
	"\x18GeolocationServerService\x12H\n" +
	"\vResolveTDOA\x12\x1a.geo_v3.ResolveTDOARequest\x1a\x1b.geo_v3.ResolveTDOAResponse\"\x00\x12f\n" +
	"\x15ResolveMultiFrameTDOA\x12$.geo_v3.ResolveMultiFrameTDOARequest\x1a%.geo_v3.ResolveMultiFrameTDOAResponse\"\x00Ba\n" +
	"\x18io.chirpstack.api_v3.geoB\x16GeolocationServerProtoP\x01Z+github.com/brocaar/chirpstack-api/go/v3/geob\x06proto3"

var (
	file_geo_geo_v3_proto_rawDescOnce sync.Once
	file_geo_geo_v3_proto_rawDescData []byte
)

func file_geo_geo_v3_proto_rawDescGZIP() []byte {
	file_geo_geo_v3_proto_rawDescOnce.Do(func() {
		file_geo_geo_v3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geo_geo_v3_proto_rawDesc), len(file_geo_geo_v3_proto_rawDesc)))
	})
	return file_geo_geo_v3_proto_rawDescData
}

var file_geo_geo_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_geo_geo_v3_proto_goTypes = []any{
	(*ResolveResult)(nil),                 // 0: geo_v3.ResolveResult
	(*FrameRXInfo)(nil),                   // 1: geo_v3.FrameRXInfo
	(*ResolveTDOARequest)(nil),            // 2: geo_v3.ResolveTDOARequest
	(*ResolveMultiFrameTDOARequest)(nil),  // 3: geo_v3.ResolveMultiFrameTDOARequest
	(*ResolveTDOAResponse)(nil),           // 4: geo_v3.ResolveTDOAResponse
	(*ResolveMultiFrameTDOAResponse)(nil), // 5: geo_v3.ResolveMultiFrameTDOAResponse
	(*common.Location)(nil),               // 6: common_v3.Location
	(*gw.UplinkRXInfo)(nil),               // 7: gw_v3.UplinkRXInfo
}
var file_geo_geo_v3_proto_depIdxs = []int32{
	6, // 0: geo_v3.ResolveResult.location:type_name -> common_v3.Location
	7, // 1: geo_v3.FrameRXInfo.rx_info:type_name -> gw_v3.UplinkRXInfo
	1, // 2: geo_v3.ResolveTDOARequest.frame_rx_info:type_name -> geo_v3.FrameRXInfo
	1, // 3: geo_v3.ResolveMultiFrameTDOARequest.frame_rx_info_set:type_name -> geo_v3.FrameRXInfo
	0, // 4: geo_v3.ResolveTDOAResponse.result:type_name -> geo_v3.ResolveResult
	0, // 5: geo_v3.ResolveMultiFrameTDOAResponse.result:type_name -> geo_v3.ResolveResult
	2, // 6: geo_v3.GeolocationServerService.ResolveTDOA:input_type -> geo_v3.ResolveTDOARequest
	3, // 7: geo_v3.GeolocationServerService.ResolveMultiFrameTDOA:input_type -> geo_v3.ResolveMultiFrameTDOARequest
	4, // 8: geo_v3.GeolocationServerService.ResolveTDOA:output_type -> geo_v3.ResolveTDOAResponse
	5, // 9: geo_v3.GeolocationServerService.ResolveMultiFrameTDOA:output_type -> geo_v3.ResolveMultiFrameTDOAResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_geo_geo_v3_proto_init() }
func file_geo_geo_v3_proto_init() {
	if File_geo_geo_v3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geo_geo_v3_proto_rawDesc), len(file_geo_geo_v3_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geo_geo_v3_proto_goTypes,
		DependencyIndexes: file_geo_geo_v3_proto_depIdxs,
		MessageInfos:      file_geo_geo_v3_proto_msgTypes,
	}.Build()
	File_geo_geo_v3_proto = out.File
	file_geo_geo_v3_proto_goTypes = nil
	file_geo_geo_v3_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GeolocationServerServiceClient is the client API for GeolocationServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GeolocationServerServiceClient interface {
	// ResolveTDOA resolves the location based on TDOA.
	ResolveTDOA(ctx context.Context, in *ResolveTDOARequest, opts ...grpc.CallOption) (*ResolveTDOAResponse, error)
	// ResolveMultiFrameTDOA resolves the location using TDOA, based on
	// multiple frames.
	ResolveMultiFrameTDOA(ctx context.Context, in *ResolveMultiFrameTDOARequest, opts ...grpc.CallOption) (*ResolveMultiFrameTDOAResponse, error)
}

type geolocationServerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeolocationServerServiceClient(cc grpc.ClientConnInterface) GeolocationServerServiceClient {
	return &geolocationServerServiceClient{cc}
}

func (c *geolocationServerServiceClient) ResolveTDOA(ctx context.Context, in *ResolveTDOARequest, opts ...grpc.CallOption) (*ResolveTDOAResponse, error) {
	out := new(ResolveTDOAResponse)
	err := c.cc.Invoke(ctx, "/geo_v3.GeolocationServerService/ResolveTDOA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geolocationServerServiceClient) ResolveMultiFrameTDOA(ctx context.Context, in *ResolveMultiFrameTDOARequest, opts ...grpc.CallOption) (*ResolveMultiFrameTDOAResponse, error) {
	out := new(ResolveMultiFrameTDOAResponse)
	err := c.cc.Invoke(ctx, "/geo_v3.GeolocationServerService/ResolveMultiFrameTDOA", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeolocationServerServiceServer is the server API for GeolocationServerService service.
type GeolocationServerServiceServer interface {
	// ResolveTDOA resolves the location based on TDOA.
	ResolveTDOA(context.Context, *ResolveTDOARequest) (*ResolveTDOAResponse, error)
	// ResolveMultiFrameTDOA resolves the location using TDOA, based on
	// multiple frames.
	ResolveMultiFrameTDOA(context.Context, *ResolveMultiFrameTDOARequest) (*ResolveMultiFrameTDOAResponse, error)
}

// UnimplementedGeolocationServerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGeolocationServerServiceServer struct {
}

func (*UnimplementedGeolocationServerServiceServer) ResolveTDOA(context.Context, *ResolveTDOARequest) (*ResolveTDOAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveTDOA not implemented")
}
func (*UnimplementedGeolocationServerServiceServer) ResolveMultiFrameTDOA(context.Context, *ResolveMultiFrameTDOARequest) (*ResolveMultiFrameTDOAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveMultiFrameTDOA not implemented")
}

func RegisterGeolocationServerServiceServer(s *grpc.Server, srv GeolocationServerServiceServer) {
	s.RegisterService(&_GeolocationServerService_serviceDesc, srv)
}

func _GeolocationServerService_ResolveTDOA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveTDOARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeolocationServerServiceServer).ResolveTDOA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geo_v3.GeolocationServerService/ResolveTDOA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeolocationServerServiceServer).ResolveTDOA(ctx, req.(*ResolveTDOARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeolocationServerService_ResolveMultiFrameTDOA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveMultiFrameTDOARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeolocationServerServiceServer).ResolveMultiFrameTDOA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geo_v3.GeolocationServerService/ResolveMultiFrameTDOA",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeolocationServerServiceServer).ResolveMultiFrameTDOA(ctx, req.(*ResolveMultiFrameTDOARequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GeolocationServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "geo_v3.GeolocationServerService",
	HandlerType: (*GeolocationServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveTDOA",
			Handler:    _GeolocationServerService_ResolveTDOA_Handler,
		},
		{
			MethodName: "ResolveMultiFrameTDOA",
			Handler:    _GeolocationServerService_ResolveMultiFrameTDOA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geo/geo_v3.proto",
}
