// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: nc/nc_v3.proto

package nc

import (
	context "context"
	gw "github.com/IoTOpen/chirpstack-v3-api/go/v3/gw"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MType int32

const (
	MType_UNKNOWN               MType = 0
	MType_JOIN_REQUEST          MType = 1
	MType_JOIN_ACCEPT           MType = 2
	MType_UNCONFIRMED_DATA_UP   MType = 3
	MType_UNCONFIRMED_DATA_DOWN MType = 4
	MType_CONFIRMED_DATA_UP     MType = 5
	MType_CONFIRMED_DATA_DOWN   MType = 6
	MType_REJOIN_REQUEST        MType = 7
)

// Enum value maps for MType.
var (
	MType_name = map[int32]string{
		0: "UNKNOWN",
		1: "JOIN_REQUEST",
		2: "JOIN_ACCEPT",
		3: "UNCONFIRMED_DATA_UP",
		4: "UNCONFIRMED_DATA_DOWN",
		5: "CONFIRMED_DATA_UP",
		6: "CONFIRMED_DATA_DOWN",
		7: "REJOIN_REQUEST",
	}
	MType_value = map[string]int32{
		"UNKNOWN":               0,
		"JOIN_REQUEST":          1,
		"JOIN_ACCEPT":           2,
		"UNCONFIRMED_DATA_UP":   3,
		"UNCONFIRMED_DATA_DOWN": 4,
		"CONFIRMED_DATA_UP":     5,
		"CONFIRMED_DATA_DOWN":   6,
		"REJOIN_REQUEST":        7,
	}
)

func (x MType) Enum() *MType {
	p := new(MType)
	*p = x
	return p
}

func (x MType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MType) Descriptor() protoreflect.EnumDescriptor {
	return file_nc_nc_v3_proto_enumTypes[0].Descriptor()
}

func (MType) Type() protoreflect.EnumType {
	return &file_nc_nc_v3_proto_enumTypes[0]
}

func (x MType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MType.Descriptor instead.
func (MType) EnumDescriptor() ([]byte, []int) {
	return file_nc_nc_v3_proto_rawDescGZIP(), []int{0}
}

type HandleUplinkMetaDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// TX meta-data.
	TxInfo *gw.UplinkTXInfo `protobuf:"bytes,2,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// RX meta-data.
	RxInfo []*gw.UplinkRXInfo `protobuf:"bytes,3,rep,name=rx_info,json=rxInfo,proto3" json:"rx_info,omitempty"`
	// PHYPayload byte count.
	PhyPayloadByteCount uint32 `protobuf:"varint,4,opt,name=phy_payload_byte_count,json=phyPayloadByteCount,proto3" json:"phy_payload_byte_count,omitempty"`
	// MAC-Command byte count.
	MacCommandByteCount uint32 `protobuf:"varint,5,opt,name=mac_command_byte_count,json=macCommandByteCount,proto3" json:"mac_command_byte_count,omitempty"`
	// Application payload byte count.
	ApplicationPayloadByteCount uint32 `protobuf:"varint,6,opt,name=application_payload_byte_count,json=applicationPayloadByteCount,proto3" json:"application_payload_byte_count,omitempty"`
	// Message type.
	MessageType   MType `protobuf:"varint,7,opt,name=message_type,json=messageType,proto3,enum=nc_v3.MType" json:"message_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleUplinkMetaDataRequest) Reset() {
	*x = HandleUplinkMetaDataRequest{}
	mi := &file_nc_nc_v3_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleUplinkMetaDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleUplinkMetaDataRequest) ProtoMessage() {}

func (x *HandleUplinkMetaDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nc_nc_v3_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleUplinkMetaDataRequest.ProtoReflect.Descriptor instead.
func (*HandleUplinkMetaDataRequest) Descriptor() ([]byte, []int) {
	return file_nc_nc_v3_proto_rawDescGZIP(), []int{0}
}

func (x *HandleUplinkMetaDataRequest) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *HandleUplinkMetaDataRequest) GetTxInfo() *gw.UplinkTXInfo {
	if x != nil {
		return x.TxInfo
	}
	return nil
}

func (x *HandleUplinkMetaDataRequest) GetRxInfo() []*gw.UplinkRXInfo {
	if x != nil {
		return x.RxInfo
	}
	return nil
}

func (x *HandleUplinkMetaDataRequest) GetPhyPayloadByteCount() uint32 {
	if x != nil {
		return x.PhyPayloadByteCount
	}
	return 0
}

func (x *HandleUplinkMetaDataRequest) GetMacCommandByteCount() uint32 {
	if x != nil {
		return x.MacCommandByteCount
	}
	return 0
}

func (x *HandleUplinkMetaDataRequest) GetApplicationPayloadByteCount() uint32 {
	if x != nil {
		return x.ApplicationPayloadByteCount
	}
	return 0
}

func (x *HandleUplinkMetaDataRequest) GetMessageType() MType {
	if x != nil {
		return x.MessageType
	}
	return MType_UNKNOWN
}

type HandleDownlinkMetaDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Multicast Group ID (UUID).
	MulticastGroupId []byte `protobuf:"bytes,2,opt,name=multicast_group_id,json=multicastGroupId,proto3" json:"multicast_group_id,omitempty"`
	// TX meta-data.
	TxInfo *gw.DownlinkTXInfo `protobuf:"bytes,3,opt,name=tx_info,json=txInfo,proto3" json:"tx_info,omitempty"`
	// PHYPayload byte count.
	PhyPayloadByteCount uint32 `protobuf:"varint,4,opt,name=phy_payload_byte_count,json=phyPayloadByteCount,proto3" json:"phy_payload_byte_count,omitempty"`
	// MAC-Command byte count.
	MacCommandByteCount uint32 `protobuf:"varint,5,opt,name=mac_command_byte_count,json=macCommandByteCount,proto3" json:"mac_command_byte_count,omitempty"`
	// Application payload byte count.
	ApplicationPayloadByteCount uint32 `protobuf:"varint,6,opt,name=application_payload_byte_count,json=applicationPayloadByteCount,proto3" json:"application_payload_byte_count,omitempty"`
	// Message type.
	MessageType MType `protobuf:"varint,7,opt,name=message_type,json=messageType,proto3,enum=nc_v3.MType" json:"message_type,omitempty"`
	// Gateway ID.
	GatewayId     []byte `protobuf:"bytes,8,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleDownlinkMetaDataRequest) Reset() {
	*x = HandleDownlinkMetaDataRequest{}
	mi := &file_nc_nc_v3_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleDownlinkMetaDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleDownlinkMetaDataRequest) ProtoMessage() {}

func (x *HandleDownlinkMetaDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nc_nc_v3_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleDownlinkMetaDataRequest.ProtoReflect.Descriptor instead.
func (*HandleDownlinkMetaDataRequest) Descriptor() ([]byte, []int) {
	return file_nc_nc_v3_proto_rawDescGZIP(), []int{1}
}

func (x *HandleDownlinkMetaDataRequest) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *HandleDownlinkMetaDataRequest) GetMulticastGroupId() []byte {
	if x != nil {
		return x.MulticastGroupId
	}
	return nil
}

func (x *HandleDownlinkMetaDataRequest) GetTxInfo() *gw.DownlinkTXInfo {
	if x != nil {
		return x.TxInfo
	}
	return nil
}

func (x *HandleDownlinkMetaDataRequest) GetPhyPayloadByteCount() uint32 {
	if x != nil {
		return x.PhyPayloadByteCount
	}
	return 0
}

func (x *HandleDownlinkMetaDataRequest) GetMacCommandByteCount() uint32 {
	if x != nil {
		return x.MacCommandByteCount
	}
	return 0
}

func (x *HandleDownlinkMetaDataRequest) GetApplicationPayloadByteCount() uint32 {
	if x != nil {
		return x.ApplicationPayloadByteCount
	}
	return 0
}

func (x *HandleDownlinkMetaDataRequest) GetMessageType() MType {
	if x != nil {
		return x.MessageType
	}
	return MType_UNKNOWN
}

func (x *HandleDownlinkMetaDataRequest) GetGatewayId() []byte {
	if x != nil {
		return x.GatewayId
	}
	return nil
}

type HandleUplinkMACCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Device EUI (8 bytes).
	DevEui []byte `protobuf:"bytes,1,opt,name=dev_eui,json=devEui,proto3" json:"dev_eui,omitempty"`
	// Command identifier (specified by the LoRaWAN specs).
	Cid uint32 `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	// MAC-command payload(s).
	Commands      [][]byte `protobuf:"bytes,6,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleUplinkMACCommandRequest) Reset() {
	*x = HandleUplinkMACCommandRequest{}
	mi := &file_nc_nc_v3_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleUplinkMACCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleUplinkMACCommandRequest) ProtoMessage() {}

func (x *HandleUplinkMACCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nc_nc_v3_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleUplinkMACCommandRequest.ProtoReflect.Descriptor instead.
func (*HandleUplinkMACCommandRequest) Descriptor() ([]byte, []int) {
	return file_nc_nc_v3_proto_rawDescGZIP(), []int{2}
}

func (x *HandleUplinkMACCommandRequest) GetDevEui() []byte {
	if x != nil {
		return x.DevEui
	}
	return nil
}

func (x *HandleUplinkMACCommandRequest) GetCid() uint32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *HandleUplinkMACCommandRequest) GetCommands() [][]byte {
	if x != nil {
		return x.Commands
	}
	return nil
}

type HandleRejectedUplinkFrameSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrameSet      *gw.UplinkFrameSet     `protobuf:"bytes,1,opt,name=frame_set,json=frameSet,proto3" json:"frame_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRejectedUplinkFrameSetRequest) Reset() {
	*x = HandleRejectedUplinkFrameSetRequest{}
	mi := &file_nc_nc_v3_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRejectedUplinkFrameSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRejectedUplinkFrameSetRequest) ProtoMessage() {}

func (x *HandleRejectedUplinkFrameSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nc_nc_v3_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRejectedUplinkFrameSetRequest.ProtoReflect.Descriptor instead.
func (*HandleRejectedUplinkFrameSetRequest) Descriptor() ([]byte, []int) {
	return file_nc_nc_v3_proto_rawDescGZIP(), []int{3}
}

func (x *HandleRejectedUplinkFrameSetRequest) GetFrameSet() *gw.UplinkFrameSet {
	if x != nil {
		return x.FrameSet
	}
	return nil
}

var File_nc_nc_v3_proto protoreflect.FileDescriptor

const file_nc_nc_v3_proto_rawDesc = "" +
	"\n" +
	"\x0enc/nc_v3.proto\x12\x05nc_v3\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0egw/gw_v3.proto\"\xf2\x02\n" +
	"\x1bHandleUplinkMetaDataRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEui\x12,\n" +
	"\atx_info\x18\x02 \x01(\v2\x13.gw_v3.UplinkTXInfoR\x06txInfo\x12,\n" +
	"\arx_info\x18\x03 \x03(\v2\x13.gw_v3.UplinkRXInfoR\x06rxInfo\x123\n" +
	"\x16phy_payload_byte_count\x18\x04 \x01(\rR\x13phyPayloadByteCount\x123\n" +
	"\x16mac_command_byte_count\x18\x05 \x01(\rR\x13macCommandByteCount\x12C\n" +
	"\x1eapplication_payload_byte_count\x18\x06 \x01(\rR\x1bapplicationPayloadByteCount\x12/\n" +
	"\fmessage_type\x18\a \x01(\x0e2\f.nc_v3.MTypeR\vmessageType\"\x95\x03\n" +
	"\x1dHandleDownlinkMetaDataRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEui\x12,\n" +
	"\x12multicast_group_id\x18\x02 \x01(\fR\x10multicastGroupId\x12.\n" +
	"\atx_info\x18\x03 \x01(\v2\x15.gw_v3.DownlinkTXInfoR\x06txInfo\x123\n" +
	"\x16phy_payload_byte_count\x18\x04 \x01(\rR\x13phyPayloadByteCount\x123\n" +
	"\x16mac_command_byte_count\x18\x05 \x01(\rR\x13macCommandByteCount\x12C\n" +
	"\x1eapplication_payload_byte_count\x18\x06 \x01(\rR\x1bapplicationPayloadByteCount\x12/\n" +
	"\fmessage_type\x18\a \x01(\x0e2\f.nc_v3.MTypeR\vmessageType\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\b \x01(\fR\tgatewayId\"f\n" +
	"\x1dHandleUplinkMACCommandRequest\x12\x17\n" +
	"\adev_eui\x18\x01 \x01(\fR\x06devEui\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\rR\x03cid\x12\x1a\n" +
	"\bcommands\x18\x06 \x03(\fR\bcommands\"Y\n" +
	"#HandleRejectedUplinkFrameSetRequest\x122\n" +
	"\tframe_set\x18\x01 \x01(\v2\x15.gw_v3.UplinkFrameSetR\bframeSet*\xaf\x01\n" +
	"\x05MType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x10\n" +
	"\fJOIN_REQUEST\x10\x01\x12\x0f\n" +
	"\vJOIN_ACCEPT\x10\x02\x12\x17\n" +
	"\x13UNCONFIRMED_DATA_UP\x10\x03\x12\x19\n" +
	"\x15UNCONFIRMED_DATA_DOWN\x10\x04\x12\x15\n" +
	"\x11CONFIRMED_DATA_UP\x10\x05\x12\x17\n" +
	"\x13CONFIRMED_DATA_DOWN\x10\x06\x12\x12\n" +
	"\x0eREJOIN_REQUEST\x10\a2\x8a\x03\n" +
	"\x18NetworkControllerService\x12T\n" +
	"\x14HandleUplinkMetaData\x12\".nc_v3.HandleUplinkMetaDataRequest\x1a\x16.google.protobuf.Empty\"\x00\x12X\n" +
	"\x16HandleDownlinkMetaData\x12$.nc_v3.HandleDownlinkMetaDataRequest\x1a\x16.google.protobuf.Empty\"\x00\x12X\n" +
	"\x16HandleUplinkMACCommand\x12$.nc_v3.HandleUplinkMACCommandRequest\x1a\x16.google.protobuf.Empty\"\x00\x12d\n" +
	"\x1cHandleRejectedUplinkFrameSet\x12*.nc_v3.HandleRejectedUplinkFrameSetRequest\x1a\x16.google.protobuf.Empty\"\x00Bb\n" +
	"\x17io.chirpstack.api_v3.ncB\x16NetworkControllerProtoP\x01Z-github.com/IoTOpen/chirpstack-v3-api/go/v3/ncb\x06proto3"

var (
	file_nc_nc_v3_proto_rawDescOnce sync.Once
	file_nc_nc_v3_proto_rawDescData []byte
)

func file_nc_nc_v3_proto_rawDescGZIP() []byte {
	file_nc_nc_v3_proto_rawDescOnce.Do(func() {
		file_nc_nc_v3_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nc_nc_v3_proto_rawDesc), len(file_nc_nc_v3_proto_rawDesc)))
	})
	return file_nc_nc_v3_proto_rawDescData
}

var file_nc_nc_v3_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nc_nc_v3_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nc_nc_v3_proto_goTypes = []any{
	(MType)(0),                                  // 0: nc_v3.MType
	(*HandleUplinkMetaDataRequest)(nil),         // 1: nc_v3.HandleUplinkMetaDataRequest
	(*HandleDownlinkMetaDataRequest)(nil),       // 2: nc_v3.HandleDownlinkMetaDataRequest
	(*HandleUplinkMACCommandRequest)(nil),       // 3: nc_v3.HandleUplinkMACCommandRequest
	(*HandleRejectedUplinkFrameSetRequest)(nil), // 4: nc_v3.HandleRejectedUplinkFrameSetRequest
	(*gw.UplinkTXInfo)(nil),                     // 5: gw_v3.UplinkTXInfo
	(*gw.UplinkRXInfo)(nil),                     // 6: gw_v3.UplinkRXInfo
	(*gw.DownlinkTXInfo)(nil),                   // 7: gw_v3.DownlinkTXInfo
	(*gw.UplinkFrameSet)(nil),                   // 8: gw_v3.UplinkFrameSet
	(*empty.Empty)(nil),                         // 9: google.protobuf.Empty
}
var file_nc_nc_v3_proto_depIdxs = []int32{
	5,  // 0: nc_v3.HandleUplinkMetaDataRequest.tx_info:type_name -> gw_v3.UplinkTXInfo
	6,  // 1: nc_v3.HandleUplinkMetaDataRequest.rx_info:type_name -> gw_v3.UplinkRXInfo
	0,  // 2: nc_v3.HandleUplinkMetaDataRequest.message_type:type_name -> nc_v3.MType
	7,  // 3: nc_v3.HandleDownlinkMetaDataRequest.tx_info:type_name -> gw_v3.DownlinkTXInfo
	0,  // 4: nc_v3.HandleDownlinkMetaDataRequest.message_type:type_name -> nc_v3.MType
	8,  // 5: nc_v3.HandleRejectedUplinkFrameSetRequest.frame_set:type_name -> gw_v3.UplinkFrameSet
	1,  // 6: nc_v3.NetworkControllerService.HandleUplinkMetaData:input_type -> nc_v3.HandleUplinkMetaDataRequest
	2,  // 7: nc_v3.NetworkControllerService.HandleDownlinkMetaData:input_type -> nc_v3.HandleDownlinkMetaDataRequest
	3,  // 8: nc_v3.NetworkControllerService.HandleUplinkMACCommand:input_type -> nc_v3.HandleUplinkMACCommandRequest
	4,  // 9: nc_v3.NetworkControllerService.HandleRejectedUplinkFrameSet:input_type -> nc_v3.HandleRejectedUplinkFrameSetRequest
	9,  // 10: nc_v3.NetworkControllerService.HandleUplinkMetaData:output_type -> google.protobuf.Empty
	9,  // 11: nc_v3.NetworkControllerService.HandleDownlinkMetaData:output_type -> google.protobuf.Empty
	9,  // 12: nc_v3.NetworkControllerService.HandleUplinkMACCommand:output_type -> google.protobuf.Empty
	9,  // 13: nc_v3.NetworkControllerService.HandleRejectedUplinkFrameSet:output_type -> google.protobuf.Empty
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_nc_nc_v3_proto_init() }
func file_nc_nc_v3_proto_init() {
	if File_nc_nc_v3_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nc_nc_v3_proto_rawDesc), len(file_nc_nc_v3_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nc_nc_v3_proto_goTypes,
		DependencyIndexes: file_nc_nc_v3_proto_depIdxs,
		EnumInfos:         file_nc_nc_v3_proto_enumTypes,
		MessageInfos:      file_nc_nc_v3_proto_msgTypes,
	}.Build()
	File_nc_nc_v3_proto = out.File
	file_nc_nc_v3_proto_goTypes = nil
	file_nc_nc_v3_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NetworkControllerServiceClient is the client API for NetworkControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NetworkControllerServiceClient interface {
	// HandleUplinkMetaData handles uplink meta-rata.
	HandleUplinkMetaData(ctx context.Context, in *HandleUplinkMetaDataRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// HandleDownlinkMetaData handles downlink meta-data.
	HandleDownlinkMetaData(ctx context.Context, in *HandleDownlinkMetaDataRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// HandleUplinkMACCommand handles an uplink mac-command.
	// This method will only be called in case the mac-command request was
	// enqueued throught the API or when the CID is >= 0x80 (proprietary
	// mac-command range).
	HandleUplinkMACCommand(ctx context.Context, in *HandleUplinkMACCommandRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// HandleRejectedUplinkFrameSet handles a rejected uplink.
	// And uplink can be rejected in the case the device has not (yet) been
	// provisioned, because of invalid frame-counter, MIC, ...
	HandleRejectedUplinkFrameSet(ctx context.Context, in *HandleRejectedUplinkFrameSetRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type networkControllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkControllerServiceClient(cc grpc.ClientConnInterface) NetworkControllerServiceClient {
	return &networkControllerServiceClient{cc}
}

func (c *networkControllerServiceClient) HandleUplinkMetaData(ctx context.Context, in *HandleUplinkMetaDataRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/nc_v3.NetworkControllerService/HandleUplinkMetaData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkControllerServiceClient) HandleDownlinkMetaData(ctx context.Context, in *HandleDownlinkMetaDataRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/nc_v3.NetworkControllerService/HandleDownlinkMetaData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkControllerServiceClient) HandleUplinkMACCommand(ctx context.Context, in *HandleUplinkMACCommandRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/nc_v3.NetworkControllerService/HandleUplinkMACCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkControllerServiceClient) HandleRejectedUplinkFrameSet(ctx context.Context, in *HandleRejectedUplinkFrameSetRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/nc_v3.NetworkControllerService/HandleRejectedUplinkFrameSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkControllerServiceServer is the server API for NetworkControllerService service.
type NetworkControllerServiceServer interface {
	// HandleUplinkMetaData handles uplink meta-rata.
	HandleUplinkMetaData(context.Context, *HandleUplinkMetaDataRequest) (*empty.Empty, error)
	// HandleDownlinkMetaData handles downlink meta-data.
	HandleDownlinkMetaData(context.Context, *HandleDownlinkMetaDataRequest) (*empty.Empty, error)
	// HandleUplinkMACCommand handles an uplink mac-command.
	// This method will only be called in case the mac-command request was
	// enqueued throught the API or when the CID is >= 0x80 (proprietary
	// mac-command range).
	HandleUplinkMACCommand(context.Context, *HandleUplinkMACCommandRequest) (*empty.Empty, error)
	// HandleRejectedUplinkFrameSet handles a rejected uplink.
	// And uplink can be rejected in the case the device has not (yet) been
	// provisioned, because of invalid frame-counter, MIC, ...
	HandleRejectedUplinkFrameSet(context.Context, *HandleRejectedUplinkFrameSetRequest) (*empty.Empty, error)
}

// UnimplementedNetworkControllerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNetworkControllerServiceServer struct {
}

func (*UnimplementedNetworkControllerServiceServer) HandleUplinkMetaData(context.Context, *HandleUplinkMetaDataRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleUplinkMetaData not implemented")
}
func (*UnimplementedNetworkControllerServiceServer) HandleDownlinkMetaData(context.Context, *HandleDownlinkMetaDataRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleDownlinkMetaData not implemented")
}
func (*UnimplementedNetworkControllerServiceServer) HandleUplinkMACCommand(context.Context, *HandleUplinkMACCommandRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleUplinkMACCommand not implemented")
}
func (*UnimplementedNetworkControllerServiceServer) HandleRejectedUplinkFrameSet(context.Context, *HandleRejectedUplinkFrameSetRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleRejectedUplinkFrameSet not implemented")
}

func RegisterNetworkControllerServiceServer(s *grpc.Server, srv NetworkControllerServiceServer) {
	s.RegisterService(&_NetworkControllerService_serviceDesc, srv)
}

func _NetworkControllerService_HandleUplinkMetaData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleUplinkMetaDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControllerServiceServer).HandleUplinkMetaData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nc_v3.NetworkControllerService/HandleUplinkMetaData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControllerServiceServer).HandleUplinkMetaData(ctx, req.(*HandleUplinkMetaDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkControllerService_HandleDownlinkMetaData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleDownlinkMetaDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControllerServiceServer).HandleDownlinkMetaData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nc_v3.NetworkControllerService/HandleDownlinkMetaData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControllerServiceServer).HandleDownlinkMetaData(ctx, req.(*HandleDownlinkMetaDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkControllerService_HandleUplinkMACCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleUplinkMACCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControllerServiceServer).HandleUplinkMACCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nc_v3.NetworkControllerService/HandleUplinkMACCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControllerServiceServer).HandleUplinkMACCommand(ctx, req.(*HandleUplinkMACCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkControllerService_HandleRejectedUplinkFrameSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRejectedUplinkFrameSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkControllerServiceServer).HandleRejectedUplinkFrameSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nc_v3.NetworkControllerService/HandleRejectedUplinkFrameSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkControllerServiceServer).HandleRejectedUplinkFrameSet(ctx, req.(*HandleRejectedUplinkFrameSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NetworkControllerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nc_v3.NetworkControllerService",
	HandlerType: (*NetworkControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleUplinkMetaData",
			Handler:    _NetworkControllerService_HandleUplinkMetaData_Handler,
		},
		{
			MethodName: "HandleDownlinkMetaData",
			Handler:    _NetworkControllerService_HandleDownlinkMetaData_Handler,
		},
		{
			MethodName: "HandleUplinkMACCommand",
			Handler:    _NetworkControllerService_HandleUplinkMACCommand_Handler,
		},
		{
			MethodName: "HandleRejectedUplinkFrameSet",
			Handler:    _NetworkControllerService_HandleRejectedUplinkFrameSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nc/nc_v3.proto",
}
